### ISSUE TITLE
Label "Settings" in /settings/users/ is missing translation

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#12971]
### Steps to reproduce
1. Login as admin with german language settings
2. Open /settings/users
3. See bottom left

### Expected behaviour
Label "Settings" should be shown as "Einstellungen"

### Actual behaviour
Label "Settings" show "Settings"

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
14.0.4 and 15.0.0

### Client configuration
**Browser:**
Firefox v63

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers

**Comment by skjnldsv** [comment]
We fixed the translation methods not long ago.
Is this translation available on transifex? If so then we need to update it there. If not then we have a bigger problem ;)

**Comment by rakekniven** [comment]
We have a lot of strings called "Settings" at Transifex.
I cannot locate source string. Does someone knows the resource and line of code?

**Comment by rullzer** [comment]
It is because the translation comes from the vue-components: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppNavigation/AppNavigation.vue#L40

@skjnldsv I guess it is better t inject this translation via the components?

**Comment by skjnldsv** [comment]
@rullzer Yes, I realised this this afternoon! We forgot about this part :p 
Sorry, I forgot to update this post @rakekniven

**Comment by rakekniven** [comment]
Hello,

are there any news regarding this issue?
Still present in v15.0.2
