### ISSUE TITLE
Upload via shared link fails on nextcloud 16.0.0RC2

### ISSUE THREAD

**Issue by rmanibus** [nextcloud/server#14986]
### Steps to reproduce
1. create a folder in nextcloud
2. share this folder via public link (select allow editing)
3. on the public link, try to upload a new file

### Expected behaviour
The file should be imported in nextcloud

### Actual behaviour
nothing happens. There is an error in the JS console and a ressource not found error in nextcloud logs (see below)

### Server configuration

**Operating system**:
ubuntu 18.04

**Web server:**
apache 2.4

**Database:**
mysql 8

**PHP version:**
php7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.0 beta3
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.0
  - admin_audit: 1.6.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.0.5
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/drive.pandore2015.fr",
        "dbtype": "mysql",
        "version": "16.0.0.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 1,
        "theme": "",
        "updater.release.channel": "beta",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/",
        "loglevel": "1",
        "dbport": "",
        "installed": true,
        "mail_smtpauthtype": "LOGIN",
        "log_type": "owncloud",
        "logfile": "\/home\/data\/nextcloud.log",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "audioplayer",
            "calendar",
            "files_markdown",
            "occweb",
            "sharerenamer"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 67.0b6
**Operating system:**
Windows10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"vajcfDSVNMYw221dE912","level":3,"time":"2019-04-08T09:16:33+00:00","remoteAddr":"83.202.81.194","user":"--","app":"jsresourceloader","method":"GET","url":"\/s\/4SgkqPMxniTqGFa","message":"Could not find resource core\/vendor\/marked\/marked.min.js to load","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.0.5"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). 4SgkqPMxniTqGFa:1:1
La ressource à l’adresse « https://REDACTED/apps/files/ » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
4SgkqPMxniTqGFa
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. main.js:750:58
Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://REDACTED/core/js/dist/share_backend.js?v=a022c0f6-2
URL du lien source : share_backend.js.map

Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://REDACTED/core/js/dist/main.js?v=a022c0f6-2
URL du lien source : main.js.map

Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : https://REDACTED/apps/files_videoplayer/js/main.js?v=a022c0f6-2
URL du lien source : main.js.map

TypeError: OCA.Files.Semaphore is not a constructorfile-upload.js:564:19
    submitUploads https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:564
    onNoConflicts https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:992
    checkExistingFiles https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:777
    add https://REDACTED/apps/files/js/file-upload.js?v=a022c0f6-2:1010
    _trigger https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    _onAdd jQuery
    each https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:28
    _onAdd jQuery
    i/e.widget/</a[t]</< https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    _onChange jQuery
    u https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    add https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    always https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    _onChange jQuery
    i/e.widget/</a[t]</< https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    a https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:290
    dispatch https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
    handle https://REDACTED/core/js/dist/main.js?v=a022c0f6-2:39
```
</details>

**Comment by rmanibus** [comment]
Still in 16.0.0RC1

**Comment by IcyKim** [comment]
I have the same

**Comment by rmanibus** [comment]
I think that in the file

```apps/files_sharing/lib/Controller/ShareController.php
```

we need to add

```
\OCP\Util::addScript('files', 'semaphore');
```
I will try this fix later today

**Comment by rmanibus** [comment]
adding the following at line 415 Fix the issue
```
\OCP\Util::addScript('files', 'merged');
```
but I'm not used to NC frontend dev, can someone confirm that it's the way to go ?

**Comment by violoncelloCH** [comment]
cc @nextcloud/sharing

**Comment by tgurr** [comment]
I'm experiencing the same issue after upgrading to stable 16.0.0, https://github.com/nextcloud/server/pull/15173 seems to work for me. I can't believe that 16.0.0 was released with this problem still open and such a major and basic feature being broken.

**Comment by maloo1** [comment]
Just ran into this too, for me selecting "File drop (upload only)" does allow uploads although this is less than optimal...

**Comment by charsi** [comment]
confirmed on Ubuntu 19.04. Neither chrom(ium) nor firefox work.

**Comment by AnwariasEu** [comment]
> adding the following at line 415 Fix the issue
> 
> ```
> \OCP\Util::addScript('files', 'merged-index');
> ```
> 
> but I'm not used to NC frontend, can someone confirm that it's the way to go ?

Had the same problem.

Your fix worked for me.
Thanks!

**Comment by rso42** [comment]
Bug confirmed on Ubuntu 18.04. Bug exists in any Browser: Chrome (Win/Mac), Firefox (Mac), Safari(Mac).

I would consider working web frontend uploads a main feature of Nextcloud.
Please fix with next update.

**Comment by MorrisJobke** [comment]
Fix is in #15432

**Comment by rso42** [comment]
Thank you very much! :)

**Comment by AInteriorB** [comment]
#15432 does not solve the problem here. Still not able to drag&drop files on a public shared editable folder. 
Thested with Google Chrom 74.0.3729.131 
On Nextcloud 16.0.0 with hot fix

**Comment by MB-BS** [comment]
> There's an error in the nextcloud log:
> `Error | jsresourceloader | Could not find resource core/vendor/marked/marked.min.js to load`

Got this error too!

**Comment by rullzer** [comment]
Should be fixed in 16.0.1

**Comment by enoch85** [comment]
@rullzer 16.0.1: 

```
[jsresourceloader] Error: Could not find resource core/vendor/marked/marked.min.js to load

GET /s/zjsqkrSpzqJGE9N
from 141.35.40.14 at 2019-05-16T11:39:24+02:00
```

Note that the external IP is not mine though. Does that mean that I will have this in my logs ever until the servers that use my shared link are updated to 16.0.1 as well?

**Comment by IGLOU-EU** [comment]
Same on NC 16.0.1

Nc log:
`{"reqId":"XOQTRX8AAQEAAFMJ0k8AAAAQ","level":3,"time":"2019-05-21T15:03:33+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"--","app":"jsresourceloader","method":"GET","url":"/index.php/s/fSWCBS4cxMC6BRE","message":"Could not find resource core/vendor/marked/marked.min.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"16.0.1.1","id":"5ce41345da39d"}`

Client log:
`https://***REMOVED SENSITIVE VALUE***/index.php/apps/files_sharing/publicpreview/fSWCBS4cxMC6BRE?x=1908&y=220&a=true&file=Peek%202019-05-20%2021-23.gif&scalingup=0
Request method:GET
Remote address:51.159.6.44:443
Status code:
404
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade`

**Comment by ajhong2** [comment]
Still seems to be an issue as of 16.0.1

**Comment by kaoschris** [comment]
We still have this Issue... it Uploads the File but returns an Internal Server Error 500.

Braikpoint on Upload is 39 in main.js
[Image 002.pdf](https://github.com/nextcloud/server/files/3223678/Image.002.pdf)
[Image 001.pdf](https://github.com/nextcloud/server/files/3223679/Image.001.pdf)
