### ISSUE TITLE
Drop area only on filestable, not on highlighted area

### ISSUE THREAD

**Issue by AInteriorB** [nextcloud/server#15493]
I have often wondered why a file is not being uploaded after it has been dragged and dropped into nextcloud. Then I found out that it depends on the chosen drop area. The whole app-content area is highlightet as a dropZone. If you drop your file next to the summery line (below the last file), it works. But if you go further down, it doesn't work although this area is also marked as a dropping area.

More technical: you must drop your file on "app-content-files" although the entire div id="app-content" is getting the "file-drag" class while dragging. 

### Steps to reproduce
1. Drag a file
2. Drop it below table id="filestable"

### Expected behaviour
The upload of the file should start

### Actual behaviour
nothing happens

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache/2.4.38
**Database:** MariaDB 10.3.14
**PHP version:** PHP 7.3.4
**Nextcloud version:** 16.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** update
**Where did you install Nextcloud from:** web updater

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - audioplayer: 2.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - user_ldap
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Comment by AInteriorB** [comment]
@MorrisJobke @icewind1991 @ChristophWurst @nickvergessen , can you have a look on this? Since #5672 you must aim on your drag&drop.

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by kayvanaarssen** [comment]
We have the same issue since the update to 16.0.2.1
Also checked permissions etc. etc. but no joy.

**Comment by MorrisJobke** [comment]
Maybe also #16170 solved this for you?

**Comment by AInteriorB** [comment]
Jap, is solved by #16170. Thanks!

**Comment by AInteriorB** [comment]
Sorry, I need to reopen this issue, @MorrisJobke @icewind1991 @skjnldsv . It **is** solved for logged-in users, it **is not** solved if you access a folder via shared link.

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by PVince81** [comment]
Still happening on Nextcloud 22.2.0

the drop zone does get highlighted, strange that the logic isn't firing:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/277525/141339561-1f1464db-09e7-4d79-8a37-88380ec3fcf5.png">

maybe something is filtering it out by selector or something

if someone fancies debugging this, it might be happening here: https://github.com/nextcloud/server/blob/v22.2.0/apps/files/js/filelist.js#L3598

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
