### ISSUE TITLE
Unshare remote owncloud directory

### ISSUE THREAD

**Issue by modules** [nextcloud/server#1625]
### Steps to reproduce
1. Adding a remote share from owncloud   via "add to your Xcloud"
2. Share is available now
3. Remove share  via "Unshare" action
### Expected behaviour

Remote share should be removed from my local instance
### Actual behaviour

An error message shows up "Error deleting file "XXXX" and the folder is still present.
### Server configuration

**Operating system**: Debian jessie

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.6.24

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from a nextcloud 9 version. Share was added in that previous version

**Where did you install Nextcloud from:** source

**List of activated apps:**
<details>
Enabled:
- activity: 2.3.2
- admin_audit: 1.0.0
- announcementcenter: 2.0.0
- bookmarks: 0.9.0
- calendar: 1.4.0
- comments: 1.0.0
- contacts: 1.4.0.0
- dav: 1.0.0
- external: 1.2
- federatedfilesharing: 1.0.1
- federation: 1.0.1
- files: 1.5.2
- files_automatedtagging: 1.1.1
- files_pdfviewer: 0.8.1
- files_sharing: 1.0.0
- files_texteditor: 2.1
- files_trashbin: 1.0.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- ownbackup: 0.3.8
- password_policy: 1.0.0
- provisioning_api: 1.0.0
- serverinfo: 1.1.1
- systemtags: 1.0.2
- templateeditor: 0.1
- theming: 1.0.1
- updatenotification: 1.0.1
- workflowengine: 1.0.1

Disabled:
- dashboard
- encryption
- files_accesscontrol
- files_external
- files_retention
- mail
- music
- news
- notes
- shorten
- survey_client
- user_external
- user_ldap
- user_saml
  </details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
{
    "system": {
        "instanceid": "ocsucsv5n576",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "xxx.xxx.xxx"
        ],
        "datadirectory": "\/var\/nextcloud-data",
        "overwrite.cli.url": "https:\/\/xxx.xxx.xxx",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "cloud",
        "mail_domain": "paupau.net",
        "defaultapp": "calendar",
        "logfile": "\/var\/nextcloud-data\/nextcloud.log",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": ""
    }
}

```

</details>

**Are you using encryption:** no
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Exception: {"Message":"HTTP\/1.1 503 Storage not 
available","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0
 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(178): 
OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('XXXX')\n#1 
\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(285):
 Sabre\\DAV\\Tree->delete('XXXX')\n#2 [internal function]: 
Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), 
Object(Sabre\\HTTP\\Response))\n#3 
\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105):
 call_user_func_array(Array, Array)\n#4 
\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): 
Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#5 
\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): 
Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), 
Object(Sabre\\HTTP\\Response))\n#6 
\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(60): 
Sabre\\DAV\\Server->exec()\n#7 
\/var\/www\/nextcloud\/remote.php(165): 
require_once('\/var\/www\/nextcl...')\n#8 
{main}","File":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":162,"User":"XXXX"}
```

</details>

See also: https://help.nextcloud.com/t/unshare-remote-cloud-directory/3376

**Comment by stefan-langenmaier** [comment]
I have no new information, but just wanted to confirm that the problem still exists with nextcloud 10.0.1

**Comment by tobiasnix** [comment]
Updated to 11.0.1 with the same issue. Is there any chance to delete that folder the dirty way/manually (on shell or in datatbase)?

**Comment by stefan-langenmaier** [comment]
I fixed my local problem, by asking the other account from the remote server to unshare the folder.

**Comment by tobiasnix** [comment]
Would like todo that but the other server is no longer available.

**Comment by bamonroe** [comment]
Having the same issue. Remote server no longer exists, and I cannot remove the shared folder from my own instance. Nextcloud 11.0.1, PHP 7.1.1, Mariadb 10.1.21, Arch Linux.

**Comment by tobiasnix** [comment]
I found one reference to the external share in my database that i just deleted. Seems like that is a workaround.

    MariaDB [nextcloud]> select * from oc_share_external;
    +----+----------------------+-----------+-----------------+----------+---------+--------+--------+------------+----------------------------------+----------+
    | id | remote               | remote_id | share_token     | password | name    | owner  | user   | mountpoint | mountpoint_hash                  | accepted |
    +----+----------------------+-----------+-----------------+----------+---------+--------+--------+------------+----------------------------------+----------+
    |  2 | http://XXXXXXX/cloud |        -1 | duXXXXXXXmTlCBL |          | /XXX    | XXX    |   XXX  | /XXX       | 25ca74b23eb1e2eeb76a0dXXXX0ce4   |        1 |
    +----+----------------------+-----------+-----------------+----------+---------+--------+--------+------------+----------------------------------+----------+

**Comment by CSammy** [comment]
This is still an issue with version 14.0.4.

I was able to make two federated shares disappear using the hint of @tobiasnix, hoping I didn't break anything doing that. Since then, synchronization works again with the desktop client. Before, it hung on those shares and aborted.

**Comment by skjnldsv** [comment]
@blizzz this sounds weirdly similar to the other unshare issues?
