### ISSUE TITLE
Error Loading FileName.JPG

### ISSUE THREAD

**Issue by xcnmv** [nextcloud/server#21740]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Some of the pictures were uploaded through the web interface and shared, others placed on the server folder, and discovered with occ.

### Expected behaviour
Tell us what should happen
The jpg picture should display

### Actual behaviour
Tell us what happens instead
Windows with an error saying: Error Loading FileName.jpg

### Server configuration

**Operating system:**
Ubuntu/ Linux 5.4.0-40-generic x86_64

**Web server:**
Apache2

**Database:**
PostgreSQL 12.2 (Ubuntu 12.2-4) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-8ubuntu1) 9.3.0, 64-bit

**PHP version:**
7.4.3

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
it was https://www.hanssonit.se/nextcloud-vm/ downloaded and installed on about 30/31 of May. It was some 18 version

**Where did you install Nextcloud from:**
https://www.hanssonit.se/nextcloud-vm/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
$ sudo -u www-data php /var/www/nextcloud/occ app:list
Enabled:
  - accessibility: 1.5.0
  - admin_audit: 1.9.0
  - audioplayer: 2.10.1
  - audioplayer_editor: 0.2.2
  - breezedark: 19.0.2
  - camerarawpreviews: 0.7.4
  - cloud_federation_api: 1.2.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.4
  - diffuse: 2.5.3
  - documentserver_community: 0.1.7
  - end_to_end_encryption: 1.5.1
  - epubreader: 1.4.2
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_external: 1.10.0
  - files_linkeditor: 1.1.1
  - files_markdown: 2.3.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.8.0
  - files_photospheres: 1.19.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 1.1.1
  - groupfolders: 6.0.6
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - music: 0.14.1
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - occweb: 0.0.7
  - onlyoffice: 4.3.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - printer: 0.0.3
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.3
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - user_usage_report: 1.3.2
  - video_converter: 0.1.4
  - viewer: 1.3.0
  - wopi: 3.5.5
  - workflowengine: 2.1.0
Disabled:
  - activity
  - calendar
  - checksum
  - comments
  - contacts
  - dropit
  - encryption
  - facerecognition
  - gpxedit
  - gpxmotion
  - gpxpod
  - issuetemplate
  - ocr
  - socialsharing_email
  - socialsharing_facebook
  - systemtags
  - user_ldap
  - whiteboard

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$ sudo -u www-data php /var/www/nextcloud/occ config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.1.106",
            "owncloud.hopto.org",
            "owncloud.hopto.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/owncloud.hopto.org\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": "true",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": "false",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "logtimezone": "Europe\/London",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "occweb"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** sshfs mounted as files folder of one user (also affected, but all users are affected even the ones using the installed folder structure on the vm)

### Client configuration
**Browser:**
Brave (~Chromium)
**Operating system:**
Ubuntu 20.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

When I am opening jpg, there is plenty of these sql errors: PDOException","Message":"SQLSTATE[42883]. This is just a few lines from the log
```
{"reqId":"abbgIfJzM87QwDhgwAt1","level":3,"time":"2020-07-07T23:22:05+01:00","remoteAddr":"217.138.207.140","user":"userOne","app":"index","method":"GET","url":"/core/preview?fileId=945839&x=2560&y=1440&a=true","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE (\"userid\" = ?) AND (\"configkey\" = ?) AND (\"appid\" = ?)' with params [\"userOne\", \"read\", \"user_usage_report\"]:\n\nSQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1063,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":79,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1054,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1054,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":117}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"19.0.0.12"}
{"reqId":"2BVIxOOJf8QMq6LjIqqY","level":3,"time":"2020-07-07T23:22:05+01:00","remoteAddr":"217.138.207.140","user":"userOne","app":"index","method":"GET","url":"/core/preview?fileId=945877&x=2560&y=1440&a=true","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE (\"userid\" = ?) AND (\"configkey\" = ?) AND (\"appid\" = ?)' with params [\"userOne\", \"read\", \"user_usage_report\"]:\n\nSQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1063,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":79,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1054,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1054,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":117}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"19.0.0.12"}
{"reqId":"mAK6PEE3fGN1y2PkC5kd","level":3,"time":"2020-07-07T23:22:05+01:00","remoteAddr":"217.138.207.140","user":"userOne","app":"index","method":"GET","url":"/core/preview?fileId=945858&x=2560&y=1440&a=true","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE (\"userid\" = ?) AND (\"configkey\" = ?) AND (\"appid\" = ?)' with params [\"userOne\", \"read\", \"user_usage_report\"]:\n\nSQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1063,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":79,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1054,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text + integer\nLINE 1: ...oc_preferences\" SET \"configvalue\" = \"configvalue\" + 1 WHERE ...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.","Code":"42883","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1054,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":81,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":63,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/AppInfo/Application.php","line":54,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\UserUsageReport\\AppInfo\\{closure}","class":"OCA\\UserUsageReport\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":70,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":103,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":117}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"19.0.0.12"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

a) The javascript console log
```
$ @ comments.js:50
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ comments.js:50
Viewer.js:97 Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead OCA.Viewer.open({ path: '/Master&Puppy-Pollok Country Park/20200701125411.jpg' })
value @ viewer.js?v=8c53f409-7:374
Viewer.vue:223 Opening viewer for file  /Master&Puppy-Pollok Country Park/20200701125411.jpg
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125411.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125501.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125501.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125511.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125411.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125518.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125501.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125511.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125526.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125511.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
preview:1 Failed to load resource: the server responded with a status of 500 ()
Mime.js:127 Error loading /Master&Puppy-Pollok Country Park/20200701125518.jpg Event
(anonymous) @ viewer.js?v=8c53f409-7:287
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ comments.js:50
get @ comments.js:50
_onResize @ merged-index.js?v=8c53f409-7:4572
Se @ appconfig.js:34
(anonymous) @ appconfig.js:34
(anonymous) @ appconfig.js:34
o @ appconfig.js:34
(anonymous) @ appconfig.js:34
```
</details>

**Comment by nooblag** [comment]
This issue could be connected to/duplicate of this https://github.com/nextcloud/server/issues/21646?

**Comment by xcnmv** [comment]
> This issue could be connected to/duplicate of this #21646?

I cannot confirm or deny. 
I am attaching a screenshot of my issue for the user perspetive
![Screenshot from 2020-07-08 15-06-26](https://user-images.githubusercontent.com/64264724/86928672-c40b0600-c12c-11ea-9b07-21d0468fa7fa.png)

**Comment by nooblag** [comment]
If you disable `user_usage_report` app, does the error go away?

**Comment by xcnmv** [comment]
> If you disable `user_usage_report` app, does the error go away?
!!BINGO!!

Thanks, that fixed it, but I am quite confident this configuration worked on 18.XX version

**Comment by nooblag** [comment]
Yep, there is a bug in that app that's causing the problem. Looks like they're fixing it (https://github.com/nextcloud/user_usage_report/issues/45)

**Comment by szaimen** [comment]
Seems like this was fixed in nextcloud/user_usage_report#45

**Comment by wtangofoxtrot** [comment]
I just had this issue after upgrading my docker instance to nextcloud:22 and deactivating the user_usage_report appears to have fixed it.

**Comment by jecal22** [comment]
I too  have just upgraded my server to Nextcloud 22 and noticed the same error when trying to display images (Videos worked fine).  I found this issue and disabled user_usage_report and found that images are now displaying properly without the error.  Seems the bug for user_usage_report has returned with Nextcloud 22.

**Comment by Thomanji** [comment]
Same here, after Upgrade to Nextcloud 22 the error is back. Hopefully the author can make the adjustment to be compatible with version 22.

**Comment by ricardoretsos** [comment]
Same here, after a fresh install using Nextcloud 22.

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/pull/27852

**Comment by killarbyte** [comment]
> 
> 
> If you disable `user_usage_report` app, does the error go away?

ty worked for me

**Comment by Bables55** [comment]
I had the same error with NC22 and solved it with the same solution.
NC22.1.1

**Comment by muelli75** [comment]
Same here, Nextcloud 22.1.1, fixed by disabling "user_usage_report"-app.

**Comment by synthead** [comment]
User usage report is not on my server, and I'm seeing this same issue:

![image](https://user-images.githubusercontent.com/820984/154910639-8e6cd16d-9c90-4d23-bf06-e4bf4b0c4e58.png)

What the file looks like in the browser:

![image](https://user-images.githubusercontent.com/820984/154910707-0a94a98b-421b-45e3-8a32-c2fbb837ba24.png)

I have confirmed that the file on the client and the server are the same (compared with md5sum).

This is on Nextcloud 23.0.1.

**Comment by nooblag** [comment]
@synthead Maybe open a fresh issue for 23.0.1 since this got closed.

**Comment by synthead** [comment]
Leaving this here in case this helps anyone else: for very large images, NC will refuse to create thumbnails unless you raise this value:

https://github.com/nextcloud/server/blob/88ded737ce61a7d05f871ab6c79281baa04b8cff/config/config.sample.php#L1079-L1086

I set mine to `512` and all the affected images started rendering just fine!

**Comment by nlekatsas** [comment]
> Leaving this here in case this helps anyone else: for very large images, NC will refuse to create thumbnails unless you raise this value:
> 
> https://github.com/nextcloud/server/blob/88ded737ce61a7d05f871ab6c79281baa04b8cff/config/config.sample.php#L1079-L1086
> 
> I set mine to `512` and all the affected images started rendering just fine!

THIS solved my recent issues with Nextcloud. I got a new phone with a 48MP sensor and only _some_ images were too big and errored out, some loaded fine which was confusing me. Bumped this to 512megs and everything is perfect, thank you!

**Comment by rightsaidfred99** [comment]
Can confirm above posts, raising it to 512 fixed it.

**Comment by alexpovel** [comment]
For some more context (and to make this even more search index-able): I also ran into this issue (duh), using a 42 MP camera.

The issue is confusing because image dimensions and image file sizes are somewhat decoupled. For example, exporting from Lightroom (or any other tool) might see an image with *lower* pixel count be *larger* in size than a second  image just next to it in the series. This is at the same JPEG quality of course.

The above `preview_max_memory` setting uses pixel count as a proxy. It might be a suitable one (no idea), but will lead to situations where, say, a 10 MB image won't load in Nextcloud where as a 20 MB one (of lower, below-threshold resolution) would. Just a thing to keep in mind. I had lots such cases.

My camera has a native resolution of 7952 x 5304 (but at just 24 bits), which is above the threshold: `7952 * 5304 * 32 / 8 / 1_000_000 ~= 168.71` Megabyte (then there's Mebibytes also, but whatever). I could confirm this to be the issue and for increasing `preview_max_memory` to be the fix.

So, `512` Megabytes will be good for 128 MP images. I set it to `256`, good for 64 MP, unless this config setting's meaning changes in the future. Setting no limit (`-1`) sounds like a footgun, but don't quote me on that.

**Comment by bplein** [comment]
changing `preview_max_memory` fixed it for me as well on NC 24. It would be great if errors based on a too-low value could be trapped and surfaced somewhere, either via preview-generator or by NC itself.

**Comment by piratenpanda** [comment]
I'm on a VPS with $GB RAM and as soon as I change the default of 'preview_max_memory' to 512 generating thumbnails from My Canon R5 files fills the 4GB RAM until php8.1-fpm gets killed by OOM. Am I missing some other config option?
