### ISSUE TITLE
NC20 RC1 Error: Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#23595]
{"reqId":"9yaAdOoMwV7IWvG9vrS2","level":3,"time":"2020-10-20T19:36:05+00:00","remoteAddr":"","user":"","app":"PHP","method":"GET","url":"/ocs/v1.php/cloud/user?format=json","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php","line":190,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php","line":137,"function":"fillStorageInfo","class":"OCA\\Provisioning_API\\Controller\\AUserData","type":"->"},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php","line":414,"function":"getUserData","class":"OCA\\Provisioning_API\\Controller\\AUserData","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getCurrentUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.1.0","id":"5f8f3c25b8c5a"}

**Comment by Chartman123** [comment]
I get this error message in my logs after updating to 20.0.1. Could it be, that there was a problem with the backport or a regression?

**Comment by MorrisJobke** [comment]
> I get this error message in my logs after updating to 20.0.1. Could it be, that there was a problem with the backport or a regression?

The fix will be shipped in 20.0.2 because it was too late for 20.0.1

**Comment by timohzbs** [comment]
Hello,

when a new user logs into my instance the welcomewizard screen ist just blank with a blue brackround. 
This is my log right after a first login of a user on Nextcloud 20.0.1:

```
root@nextcloud:/var/www/nextcloud# cat nextcloud.log

{"reqId":"asHAp4UaZkalhy6AouR2","level":3,"time":"October 29, 2020 10:39:37","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/apps/files/?dir=/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"ywUeDV7A18D1vRxWtIUq","level":3,"time":"October 29, 2020 10:39:38","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/getstoragestats.php?dir=%2F","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Helper.php","line":51,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/AjaxController.php","line":47,"function":"buildFileStorageStatistics","class":"OCA\\Files\\Helper","type":"::"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getStorageStats","class":"OCA\\Files\\Controller\\AjaxController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"Hloh9WVCVzq9W3pwLRNn","level":3,"time":"October 29, 2020 10:39:39","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/apps/files/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"2dZyx4L66SMwkqwx5xnb","level":3,"time":"October 29, 2020 10:39:39","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/apps/files/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"QJfHUS1xUioI3tHtS463","level":3,"time":"October 29, 2020 11:18:57","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/apps/files/?dir=/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"1ftXKjKZfWmKMXeMxtWt","level":3,"time":"October 29, 2020 11:18:59","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/apps/files/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"PTSIJhVX4XXyGKqJviXP","level":3,"time":"October 29, 2020 11:18:59","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/getstoragestats.php?dir=%2F","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Helper.php","line":51,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/AjaxController.php","line":47,"function":"buildFileStorageStatistics","class":"OCA\\Files\\Helper","type":"::"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getStorageStats","class":"OCA\\Files\\Controller\\AjaxController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}
{"reqId":"ZDMQrrd9Cv7f9x57hBew","level":3,"time":"October 29, 2020 11:19:00","remoteAddr":"192.168.1.25","user":"test","app":"PHP","method":"GET","url":"/apps/files/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.1.1"}

```

Is this a known bug?

**Comment by axheli** [comment]
yes, the fix is on #23606

**Comment by timohzbs** [comment]
> yes, the fix is on #23606

I checked my files, they are exactly like in #23606 but still get my errors.

**Comment by axheli** [comment]
i would copy the whole file and replace it i can assure you that fixes the issue

**Comment by nunesgh** [comment]
Hi,

Are the following errors somehow related to the one fixed by https://github.com/nextcloud/server/pull/23606?

```
{"reqId":"JMzPdaVsiQxG0Oz3Ycrx","level":1,"time":"2020-10-28T23:46:09+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"no app in context","method":"GET","url":"/apps/files_trashbin/preview?fileId=3735&file=Testing.md%2FTesting.md.d1603928764&c=1603928764","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1","id":"***REMOVED SENSITIVE VALUE***"}

{"reqId":"0fuS3bYPdMOjrjrzzS8V","level":1,"time":"2020-10-28T23:46:11+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Linux) mirall/3.0.2-20200924.150911.068ad89d8-1.0~focal1 (Nextcloud)","version":"20.0.1.1","id":"***REMOVED SENSITIVE VALUE***"}
```

My server started logging those around the same time the `[PHP] Error: Error: Undefined offset: 3 at /***REMOVED SENSITIVE VALUE***/nextcloud/lib/private/legacy/OC_Helper.php#548` error first appeared, as reported on https://github.com/nextcloud/server/issues/23208.

**Comment by andyrue** [comment]
I just installed the latest stable nextcloud from snap and ran into this error. I can't upload any files and I'm assuming it's related to this error? Is there a way I can get a working version? I tried using the latest/beta channel, but still getting this.

**Comment by axheli** [comment]
@andyrue please apply the following fix  #23606 as @MorrisJobke said "The fix will be shipped in 20.0.2 because it was too late for 20.0.1"
Thanks!

**Comment by andyrue** [comment]
@axheli How can I do that with a snap? My understanding was snaps couldn't be modified like that.

**Comment by axheli** [comment]
@andyrue find your snap dir might be located in /var/snap/nextcloud/current/nextcloud/ then navigate to the files in the ticket.

**Comment by andyrue** [comment]
@axheli Hmm. That's where I first looked, but there are just a few config files. I have never used a snap before so my first Google search about modifying the files said I couldn't modify the files so I left it at that. I appreciate your help!

**Comment by kyrofa** [comment]
@andyrue you can't hack the snap like that. You can refresh to `edge` to get the fix on master, but I'd recommend just waiting for 20.0.2.

**Comment by FiloSpaTeam** [comment]
I'm having this on Nextcloud 21.0.3. Some suggestions?
