### ISSUE TITLE
Call to undefined method when changing user password in 21.0.0 and 20.0.7

### ISSUE THREAD

**Issue by Thalagyrt** [nextcloud/server#25815]
Hello! Sorry if this is a duplicate or known issue - I couldn't find anything in search matching the stack trace, though.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Attempt to set a password for an existing user via CLI, or web UI

### Expected behaviour

User's password should be changed

### Actual behaviour

A 500 is thrown, or from the console:

```
www-data@79bee1554090:~/html$ ./occ user:resetpassword <redacted>
Enter a new password: 
Confirm the new password: 
An unhandled exception has been thrown:
Error: Call to undefined method OCP\User\Events\PasswordUpdatedEvent::getLoginName() in /var/www/html/apps/files_external/lib/Listener/StorePasswordListener.php:61
Stack trace:
#0 /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php(76): OCA\Files_External\Listener\StorePasswordListener->handle(Object(OCP\User\Events\PasswordUpdatedEvent))
#1 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCP\User\Events\PasswordUpdatedEvent), 'OCP\\User\\Events...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\User\\Events...', Object(OCP\User\Events\PasswordUpdatedEvent))
#3 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(86): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCP\User\Events\PasswordUpdatedEvent), 'OCP\\User\\Events...')
#4 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(98): OC\EventDispatcher\EventDispatcher->dispatch('OCP\\User\\Events...', Object(OCP\User\Events\PasswordUpdatedEvent))
#5 /var/www/html/lib/private/Server.php(566): OC\EventDispatcher\EventDispatcher->dispatchTyped(Object(OCP\User\Events\PasswordUpdatedEvent))
#6 [internal function]: OC\Server->OC\{closure}(Object(OC\User\User), '<redacted>', NULL)
#7 /var/www/html/lib/private/Hooks/EmitterTrait.php(107): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/lib/private/Hooks/PublicEmitter.php(41): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postSetPassword', Array)
#9 /var/www/html/lib/private/User/User.php(302): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postSetPassword', Array)
#10 /var/www/html/core/Command/User/ResetPassword.php(124): OC\User\User->setPassword('<redacted>')
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\User\ResetPassword->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\ResetPassword), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/console.php(100): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)

21.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Yes, updated from 20.0.7 just now trying to resolve this - bug is also present in 20.0.7

**Where did you install Nextcloud from:**

Docker hub, official `nextcloud:latest` image

Apologies for truncating the rest of the issue template here, I don't think the other requested information necessarily pertains as this happens from the CLI? Let me know if you need any additional information and I'll gather it!

**Comment by kesselb** [comment]
Introduced by https://github.com/nextcloud/server/pull/25224.

**Comment by kesselb** [comment]
```
Index: apps/files_external/lib/Listener/StorePasswordListener.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/files_external/lib/Listener/StorePasswordListener.php b/apps/files_external/lib/Listener/StorePasswordListener.php
--- a/apps/files_external/lib/Listener/StorePasswordListener.php	(revision b89fbaf52d06faa8828d3c0520d54ca280ee6bf6)
+++ b/apps/files_external/lib/Listener/StorePasswordListener.php	(date 1614377987957)
@@ -50,18 +50,22 @@
 			return;
 		}
 
-		$stored = $this->credentialsManager->retrieve($event->getUser()->getUID(), LoginCredentials::CREDENTIALS_IDENTIFIER);
-		$update = isset($stored['password']) && $stored['password'] !== $event->getPassword();
-		if (!$update && $event instanceof UserLoggedInEvent) {
-			$update = isset($stored['user']) && $stored['user'] !== $event->getLoginName();
+		$stored = (array)$this->credentialsManager->retrieve($event->getUser()->getUID(), LoginCredentials::CREDENTIALS_IDENTIFIER);
+		$credentials = $stored;
+
+		/** Case 1: PasswordUpdateEvent with saved credentials => Update password */
+		if ($event instanceof PasswordUpdatedEvent
+			&& isset($credentials['user'], $credentials['password'])) {
+			$credentials['password'] = $event->getPassword();
 		}
 
-		if ($stored && $update) {
-			$credentials = [
-				'user' => $event->getLoginName(),
-				'password' => $event->getPassword()
-			];
+		/** Case 2: UserLoggedInEvent => Update user or password */
+		if ($event instanceof UserLoggedInEvent) {
+			$credentials['user'] = $event->getLoginName();
+			$credentials['password'] = $event->getPassword();
+		}
 
+		if ($stored !== $credentials) {
 			$this->credentialsManager->store($event->getUser()->getUID(), LoginCredentials::CREDENTIALS_IDENTIFIER, $credentials);
 		}
 	}
```

Should fix it.

**Comment by Thalagyrt** [comment]
Just wanted to confirm I applied your patch locally, @kesselb, and all is functioning as expected now. I'll wait for an official release in the future once a fix is merged. Thanks much!

**Comment by bangert** [comment]
i've experienced the same issue and the proposed patch solved it. only some accounts seem to be affected by this.

**Comment by bp99-novin** [comment]
Similar problem here (I was trying to change an LDAP password from the web GUI, not via `occ`), patch seems to have fixed the issue.

**Comment by bluesky-ca** [comment]
I am still getting this issue in 21.0.4 when using the API call to change a user's password:
.../ocs/v1.php/cloud/users/$user  -d key="password" -d value=$pass

I tried v2.php and get the same error - the password is updated, but the return statuscode is 998.  If I change it back to a previous password I get statuscode 100.  
 I looked at the API docs and don't see any other way to change user's password - if there is one please let me know.

**Comment by jpfox156** [comment]
The issue still remains in more recent versions of nextcloud. I can confirm that these patches work with v 22.2.3 and resolve the issue.

**Comment by wollud1969** [comment]
This issue still appears for me using the Docker image nextcloud:23.0.0:

```
wn@ampere:~/container-start-scripts$ docker ps | grep nextcloud
f8bf2ff98def        nextcloud:23.0.0                                   "/entrypoint.sh apac…"   15 minutes ago      Up 15 minutes                                                      nextcloud
wn@ampere:~/container-start-scripts$ 
```

```
www-data@f8bf2ff98def:~/html$ ./occ user:resetpassword bruno
Enter a new password: 
Confirm the new password: 
An unhandled exception has been thrown:
Error: Call to undefined method OCP\User\Events\PasswordUpdatedEvent::getLoginName() in /var/www/html/apps/files_external/lib/Listener/StorePasswordListener.php:61
Stack trace:
#0 /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php(87): OCA\Files_External\Listener\StorePasswordListener->handle(Object(OCP\User\Events\PasswordUpdatedEvent))
#1 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCP\User\Events\PasswordUpdatedEvent), 'OCP\\User\\Events...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\User\\Events...', Object(OCP\User\Events\PasswordUpdatedEvent))
#3 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(88): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCP\User\Events\PasswordUpdatedEvent), 'OCP\\User\\Events...')
#4 /var/www/html/lib/private/EventDispatcher/EventDispatcher.php(100): OC\EventDispatcher\EventDispatcher->dispatch('OCP\\User\\Events...', Object(OCP\User\Events\PasswordUpdatedEvent))
#5 /var/www/html/lib/private/Server.php(579): OC\EventDispatcher\EventDispatcher->dispatchTyped(Object(OCP\User\Events\PasswordUpdatedEvent))
#6 [internal function]: OC\Server->OC\{closure}(Object(OC\User\User), 'Ps-1976-2791', NULL)
#7 /var/www/html/lib/private/Hooks/EmitterTrait.php(106): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/lib/private/Hooks/PublicEmitter.php(40): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postSetPassword', Array)
#9 /var/www/html/lib/private/User/User.php(328): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postSetPassword', Array)
#10 /var/www/html/core/Command/User/ResetPassword.php(122): OC\User\User->setPassword('Ps-1976-2791')
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\User\ResetPassword->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\ResetPassword), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/console.php(99): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('/var/www/html/c...')
#18 {main}www-data@f8bf2ff98def:~/html$ ^C
www-data@f8bf2ff98def:~/html$ 
exit
```

Do you plan to fix this in the release?

Thank and cheers

**Comment by dtibi** [comment]
Thanks @kesselb ! This fixed the issue for me. I was able to update the users password.

**Comment by lucadelu** [comment]
I can confirm the problem is still present on 22.2.8 and the patch work fine

**Comment by kesselb** [comment]
PR: https://github.com/nextcloud/server/pull/32016

22.2.10 / 23.0.7 / 24.0.3
