### ISSUE TITLE
Phone number can't be set at user profile

### ISSUE THREAD

**Issue by gr4ssi** [nextcloud/server#25931]
### Steps to reproduce
1. Install Nextcloud 21.0.0
2. try to set user phone numberin profile

### Expected behaviour
It should save the phone number.

### Actual behaviour
Error Message: Ungültige Telefonnummer kann nicht festgelegt werden

I used 017612345678 as a phone number...
then 0049712345678
then +49123456789
it all didn't work... 

![image](https://user-images.githubusercontent.com/19840345/109978763-816eed00-7cfe-11eb-8ffc-5266948c052b.png)

### Server configuration
cloud server - installed via the nextcloud_production_install.sh script.
postgres / php 7.4 on ubuntu 20.04, 2 cpu's 4GB RAM

**Comment by hellblue** [comment]
I received the same message, but the phone number is still saved in my profile

**Comment by gr4ssi** [comment]
The error miraculously disappeared after a day. Now I can enter the phone number just fine, no warnings. :-/

**Comment by HigH-HawK** [comment]
Someone reported this on the forums: https://help.nextcloud.com/t/unable-to-set-phone-number/111782

He however confirmed, that it does not save the phone number for him.

**Comment by simonspa** [comment]
The issue lies in this piece of code:

https://github.com/nextcloud/server/blob/master/lib/private/Accounts/AccountManager.php#L94-L121

which essentially means:

 * the field only accepts phone numbers with country code (starting with `+` that is) if **no** `default_phone_region` is configured
 * the field **only accepts phone numbers from the configured region** if the `default_phone_region` is configured.

Especially the latter seems to be a string restriction because it essentially means **all users of an instance have to be from the same country**, or at {least|worse} their phone numbers have to be.

**Comment by simonspa** [comment]
This is the original PR: https://github.com/nextcloud/server/pull/24486

@nickvergessen is there a way to allow multiple/all phone number regions?

**Comment by nickvergessen** [comment]
I think the actual problem you are facing is https://github.com/nextcloud/server/pull/26370
The feedback was not cleared in between and after a successful save. Update to 21.0.1 and test again.


https://github.com/nextcloud/server/blob/master/lib/private/Accounts/AccountManager.php#L94-L121

it actually means:

 * the field only accepts phone numbers with country code (starting with `+` that is) if **no** `default_phone_region` is configured
 * the field accepts phone numbers **with country code and** phone numbers **without country code from the configured region** if the `default_phone_region` is configured.

**Comment by simonspa** [comment]
Okay, I see, and I could reproduce this now. How about also accepting numbers starting with double-zero in case there is no region set? They also represent valid international-format phone numbers and should be allowed IMHO.

Also, when reading the documentation of `libphonenumber` to me it seems like using `EN` as default region is not the best way to go - maybe we should [pass `null` as region in that case](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#parse)?

**Comment by nickvergessen** [comment]
Well there is a warning in the admin section to add the default region, so not going to optimize the unset-case.
And as soon as you set a default phone region double-zero also works, so I think that's also already solved.

And as said, this issue would mostlikely not be here when the "failed" error would disappear on success which we solved with 21.0.1 already, so I will close this.

**Comment by brokert** [comment]
This obviously has not been resolved still have an issue after just installing in 2023

**Comment by Tummerhore** [comment]
Same (with NC 27.1.2). Please reopen this issue.
I type in a number, a checkmark shows that it's valid but when I reload the page I see that the number has not been saved. Note, that I get no error message like shown above.

**Comment by aurisnoctis** [comment]
Nextcloud version 29.0.5 (Nextcloud Hub 8), hosted by Webo

1. phone number can be entered and is saved in profile (persistently visible when editing profile) ✔️ 
2. phone number is **not** shown in profile view (when not in edit mode) ❌ 
3. phone number **is** shown in system address book ✔️ 

How can the phone number be made visible in the profile?

➡️ Is this related to the problem here or should I open a new issue?

https://help.nextcloud.com/t/unable-to-set-phone-number/111782/8 suggests either `‘default_phone_region’ => ‘optional’,` or `‘default_phone_region’ => ‘DE’,` or maybe both (?).

Would **setting any of this fix our problem** that the phone number is set and visible in the system address book but currently not shown in the profile?

Thanks in advance 👍 

### Screenshots for the 3 points above
![2024-08-22_171935_firefox](https://github.com/user-attachments/assets/1c2009e0-0367-4682-998b-61200c48dff6)
_________________________________________
![2024-08-22_171810_firefox](https://github.com/user-attachments/assets/99f7571c-b901-45a5-85e7-1f5daa1dbea4)
_________________________________________
![2024-08-22_171756_firefox](https://github.com/user-attachments/assets/43fcdb1a-6973-4ea5-95b6-1938281a58c2)
