### ISSUE TITLE
21.0.3 OC\HintException: Memcache \OC\Memcache\APCu not available

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#27781]
Nextcloud 21.0.3.1 (after upgrade from 21.0.2.1)
Debian 10.10 Buster
Apache 2.4
PHP 7.3.27

After the upgrade on my machine there is a condition not appearing in any NC version before:
```
$ sudo -u www-data php /var/www/nextcloud/occ  maintenance:repair
An unhandled exception has been thrown:
OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
```
No logging entry found. **This makes the NC cron job unavailable** apparently.

No such issue in any version before 21.0.3. All settings in place.

see also: https://help.nextcloud.com/t/cron-not-running-in-nc-21-0-3/119415/7?u=tp75

**Comment by andrewheeler82** [comment]
Hello, I had the same problem. For me the solution was apc.enable_cli = 1 in php.ini !!!

**Comment by HuguesDug** [comment]
Same problem: I had to switch memcache to redis.

In general the update to 21.0.3 went wrong. I had to go for manual install, then, blocked in maintenance mode, then repaired manually and now  still strugling with a invalid_hash for core/js/mimetypelist.js.

I should have wait for the upgrade. My install is more or less broken.

**Comment by mstinsky** [comment]
I can confirm after upgrading from 21.0.3 to 21.0.3 the cronjob does not seem to run anymore, without showing an error.
Enabling `apc.enable_cli = 1` fixes the issue.

**Comment by BernieO** [comment]
As a workaround you can use a parameter to tell PHP to run cli commands with APCu enabled. For example
```
sudo -u www-data php --define apc.enable_cli=1  /var/www/nextcloud/occ  maintenance:repair
```
Also adding `--define apc.enable_cli=1` to the according crontab line, the cronjob will get executed again.

**Comment by TP75** [comment]
Aha, you provided a more complete solution in this report already. thanks again.

This fix solves the issue on my machine and the NC cron job is available again.

**However, there should be a more general fix provided by the NC devs hopefully.**

Please note on my machine there was not any upgrade or change to the PHP 7.3.27 installation or the settings provided. This configuration allowed all Nextcloud versions before 21.0.3 running without the a.m. issue.

This points at NC 21.0.3 and some PHP code issue, I presume. Your mileage may vary.

**Comment by andrewheeler82** [comment]
Yes, I also received this error with the update from 21.0.2 to 21.0.3. I haven't changed anything on my system. I have noticed for a long time that the developers no longer have their Nextcloud project under control, errors creep in again and again that somehow nobody notices and as soon as the version is published these errors appear.

**Comment by andyxheli** [comment]
Needed to add apc.enable_cli=1 to /etc/php/8.0/mods-available/apcu.ini

#25770

**Comment by TP75** [comment]
Thanks @andrewheeler82 and I sadly consent.
Apparently, the new Nextcloud policy is taking from big business now: "**It's not a bug it's a feature.**"

https://docs.nextcloud.com/server/21/admin_manual/configuration_server/caching_configuration.html#id1

The admin manual has been changed to reflect this change of design only recently, I presume.  This seems to be an intentional change to the PHP coding in NC 22 and obviously was backported to NC 21.0.3 without any notice to the community.  Please prove me wrong, but this is my picture after reading the below reports which are one month old.  
  * https://github.com/nextcloud/server/pull/25770
  * https://github.com/nextcloud/server/issues/27608
If this is the case, this apparent negligence and way of change from Nextcloud would be especially hurting to community people like me who were running a stable NC environment for years.

**Comment by BernieO** [comment]
> The admin manual has been changed to reflect this change of design only recently, I presume. 

Actually, the recommendation to set `apc.enable_cli` to `1` in the `php.ini` config file has been added in Dec 2018 and was backported to the documentation of NC13:
https://github.com/nextcloud/documentation/commit/c5fa1b6859edfc20477719cf77488a797719e7c3#diff-48dc187eeb03371b5ad6886b33043bf060884809c1d51a3568c5d29e40e3bf13

https://docs.nextcloud.com/server/13/admin_manual/configuration_server/caching_configuration.html#id1

Additionally the notice about appending `--define apc.enable_cli=1` to the cron job call was added in June 2020 and backported to the documentation of NC17:  
https://github.com/nextcloud/documentation/commit/38a0a33e4edc3b7bc18f05ecf190eaf010dea1f4#diff-48dc187eeb03371b5ad6886b33043bf060884809c1d51a3568c5d29e40e3bf13

https://docs.nextcloud.com/server/17/admin_manual/configuration_server/caching_configuration.html#id1

**Comment by andrewheeler82** [comment]
I look through the documentation at regular intervals. Maybe I missed the apc.enable_cli = 1 change. But really now within a smaller release. Activate something like that and the user looks like a dork.

**Comment by hardingt** [comment]
Also got bit by this one after upgrading from 20.0.2 to 20.0.3. Adding apc.enable_cli=1 to /etc/php/8.0/mods-available/apcu.ini worked for me as well.

**Comment by zaku903** [comment]
Got the same issue after upgraded to 21.0.3 days ago, just solved by increase apc.shm_size in php setting to 64M from default 32M. By adding apc.enable_cli=1 only not work for me.

**Comment by userofgithub023897** [comment]
@zaku903 Thank you very much!!! 
This fixed it!
Cron and occ work fine again.

**Comment by tomasmark79** [comment]
Debian 10 with ISPConfig ignore website PHP settings, so require to set CLI in config file.

path for 7.3 is:
`/etc/php/7.3/mods-available/apcu_bc.ini`

add these two lines
`
apc.enable_cli=1
apc.shm_size=512M
`
This fix issue. I think that an issue is cause PHP updated with APT.

**Comment by battosai30** [comment]
> Also got bit by this one after upgrading from 20.0.2 to 20.0.3. Adding apc.enable_cli=1 to /etc/php/8.0/mods-available/apcu.ini worked for me as well.

Thank you, after hours searching why cron wasn't working, everything goes well  now !   
apc.enable_cli=1 was active in php.ini but it was not enough

php 8 - Debian 10 - NC 22 bêta

**Comment by snowflakeas** [comment]
`apc.enable_cli=1`

not working for me (running on a synology NAS (not docker)). 

cron stopped working as well. 
After numerous changes to various php.ini files I've given up. 
NC 21 is borked :-s
Disappointing that that NC does not sort this out automatically in the installer - I don't really have the interest or time any more to manage this kind of stuff.


`PHP Warning:  PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/local/lib/php73/modules/mcrypt.so (/usr/local/lib/php73/modules/mcrypt.so: cannot open shared object file: No such file or directory), /usr/local/lib/php73/modules/mcrypt.so.so (/usr/local/lib/php73/modules/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by battosai30** [comment]
> `apc.enable_cli=1`
> 
> not working for me (running on a synology NAS (not docker)).
`

Did you put it in apcu.ini ? For me putting it in php.ini wasn't enough

**Comment by snowflakeas** [comment]
> > `apc.enable_cli=1`
> > not working for me (running on a synology NAS (not docker)).
> > `
> 
> Did you put it in apcu.ini ? For me putting it in php.ini wasn't enough

No idea where to find apcu.ini

The whole setup with Synology sucks - because the php installs are through Synology - hence none of the web "cookbooks" work. 
My NC has been working since 16, but stuff has not been working smoothly the past 2 releases (cron problems etc)

**Comment by BottomNotch** [comment]
I've been struggling with this for a few hours and finally found my issue.  I had php-apcu installed, but I needed php7.3-apcu installed, obviously replace that with whatever version of php you're using.

**Comment by chippey5** [comment]
According to [#2039](https://github.com/nextcloud/vm/issues/2039) and the linked merge [#2040](https://github.com/nextcloud/vm/pull/2040) this issue is solved by using [Redis](https://docs.nextcloud.com/server/21/admin_manual/configuration_server/caching_configuration.html#id2) instead of APCu as a memcaching backend.

Note: I had to change to PHP 7.4 for this to work, as using PHP 7.3 prior to this didn't work in my case.

**Comment by szaimen** [comment]
I suppose the final way to fix the resulting issue will be discussed in https://github.com/nextcloud/server/issues/27608
Until thats done, make sure that you configured your server correctly.

**Comment by buzter** [comment]
Using a Synology DS too and found a possible solution for @snowflakes:
Add a "user_settings.ini" in "/usr/local/etc/php74/cli/conf.d" with the following content: 
"extension = apcu.so
[apc]
apc.shm_size = 64M
apc.enable_cli = 1"
Works fine for me. Found this solution in the synology forum (https://www.synology-forum.de/threads/nextcloudhub-21-0-1-und-cron.114219/page-2). Best regards

**Comment by adrien-n** [comment]
As @chippey5 said, there are mixed recommendations between the commit and the documentation. I am completely lost as to what to do. Using apc.enable_cli seems potentially unsafe (should it be used only with the instance turned off?) and the documentation says to prefer APCu.

I wanted to run an occ command but I guess this is also the reason my nextcloud cron jobs have not run in 4 days (when I updated to the most recent version available). If that's true, it's possible that a lot more users are going to notice issues in the coming weeks. Clarifying the documentation would probably avoid a lot of questions.

**Comment by brettferrell** [comment]
> Hello, I had the same problem. For me the solution was apc.enable_cli = 1 in php.ini !!!

Thanks man, this fixed me as well!

**Comment by Sieboldianus** [comment]
The issue occured during update from 20.0.12 to 21.0.4

For me, the problem was that I edited the wrong `php.ini`.

I edited
```
/etc/php/7.3/apache2/php.ini
```

But I should have edited
```
/etc/php/7.3/cli/php.ini
```

In this file, I needed to enable the extensions:
```
extension=redis.so
extension=igbinary.so
```

Then the upgrade worked.

**Comment by filerem** [comment]
> Using a Synology DS too and found a possible solution for @snowflakes:
> Add a "user_settings.ini" in "/usr/local/etc/php74/cli/conf.d" with the following content:
> "extension = apcu.so
> [apc]
> apc.shm_size = 64M
> apc.enable_cli = 1"
> Works fine for me. Found this solution in the synology forum (https://www.synology-forum.de/threads/nextcloudhub-21-0-1-und-cron.114219/page-2). Best regards

thanks ! for me, it's located here : 
/etc/php/7.3/cli/conf.d/20-apcu.ini 
i had your solution without quote, restart apache, and it's work fine !

**Comment by c-orazio** [comment]
Hi, 
on unbuntu 20 had the same problem after update, to fix it required to add both line in /etc/php/7.4/apache2/php.ini, one was not enough (then no problem to run OCC): 
apc.enable_cli=1
apc.shm_size = 256

thanks to all!

**Comment by R0Wi** [comment]
Updated the commandline updater docs in https://github.com/nextcloud/documentation/pull/7136 😎

**Comment by erdoukki** [comment]
```
admin@myNextCloud:~$ sudo -u www-data php -f /var/www/nextcloud/cron.php
OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
```
```
admin@myNextCloud:~$ sudo nano /etc/php/7.4/cli/conf.d/20-apcu.ini 

admin@myNextCloud:~$ sudo cat /etc/php/7.4/cli/conf.d/20-apcu.ini
extension=apcu.so
apc.enable_cli=1
apc.shm_size=64M
```
```
admin@myNextCloud:~$ sudo -u www-data php -f /var/www/nextcloud/cron.php
```
Fixed on Debian 11 (bullseye) with NextCloud 22.1.1

**Comment by mzch** [comment]
I have `21.1.1`I and Deban 11 (bullseye) but this hasn't been fixed yet in my VPS.
Is this really caused by php setting? I tried `adding apc.enale_cli=1` in php.ini, apcu.ini and apcu_bc.ini.

```
$ php --ini
Configuration File (php.ini) Path: /etc/php/7.4/cli
Loaded Configuration File:         /etc/php/7.4/cli/php.ini
Scan for additional .ini files in: /etc/php/7.4/cli/conf.d
Additional .ini files parsed:      /etc/php/7.4/cli/conf.d/10-opcache.ini,
/etc/php/7.4/cli/conf.d/10-pdo.ini,
/etc/php/7.4/cli/conf.d/15-xml.ini,
/etc/php/7.4/cli/conf.d/20-apcu.ini,
/etc/php/7.4/cli/conf.d/20-bcmath.ini,
/etc/php/7.4/cli/conf.d/20-bz2.ini,
/etc/php/7.4/cli/conf.d/20-calendar.ini,
/etc/php/7.4/cli/conf.d/20-ctype.ini,
/etc/php/7.4/cli/conf.d/20-curl.ini,
/etc/php/7.4/cli/conf.d/20-dom.ini,
/etc/php/7.4/cli/conf.d/20-exif.ini,
/etc/php/7.4/cli/conf.d/20-ffi.ini,
/etc/php/7.4/cli/conf.d/20-fileinfo.ini,
/etc/php/7.4/cli/conf.d/20-ftp.ini,
/etc/php/7.4/cli/conf.d/20-gd.ini,
/etc/php/7.4/cli/conf.d/20-gettext.ini,
/etc/php/7.4/cli/conf.d/20-gmp.ini,
/etc/php/7.4/cli/conf.d/20-iconv.ini,
/etc/php/7.4/cli/conf.d/20-igbinary.ini,
/etc/php/7.4/cli/conf.d/20-imagick.ini,
/etc/php/7.4/cli/conf.d/20-imap.ini,
/etc/php/7.4/cli/conf.d/20-intl.ini,
/etc/php/7.4/cli/conf.d/20-json.ini,
/etc/php/7.4/cli/conf.d/20-mbstring.ini,
/etc/php/7.4/cli/conf.d/20-msgpack.ini,
/etc/php/7.4/cli/conf.d/20-pdo_pgsql.ini,
/etc/php/7.4/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/7.4/cli/conf.d/20-pgsql.ini,
/etc/php/7.4/cli/conf.d/20-phar.ini,
/etc/php/7.4/cli/conf.d/20-posix.ini,
/etc/php/7.4/cli/conf.d/20-readline.ini,
/etc/php/7.4/cli/conf.d/20-redis.ini,
/etc/php/7.4/cli/conf.d/20-shmop.ini,
/etc/php/7.4/cli/conf.d/20-simplexml.ini,
/etc/php/7.4/cli/conf.d/20-sockets.ini,
/etc/php/7.4/cli/conf.d/20-sqlite3.ini,
/etc/php/7.4/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.4/cli/conf.d/20-sysvsem.ini,
/etc/php/7.4/cli/conf.d/20-sysvshm.ini,
/etc/php/7.4/cli/conf.d/20-tidy.ini,
/etc/php/7.4/cli/conf.d/20-tokenizer.ini,
/etc/php/7.4/cli/conf.d/20-xmlreader.ini,
/etc/php/7.4/cli/conf.d/20-xmlrpc.ini,
/etc/php/7.4/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.4/cli/conf.d/20-xsl.ini,
/etc/php/7.4/cli/conf.d/20-zip.ini,
/etc/php/7.4/cli/conf.d/25-apcu_bc.ini,
/etc/php/7.4/cli/conf.d/25-memcached.ini
```

**Comment by R0Wi** [comment]
> tried adding ` apc.enale_cli=1` in php.ini, apcu.ini

You have a typo in the settings key

Try to add `apc.enable_cli=1` to the end of `/etc/php/7.4/cli/php.ini` or append `define apc.enable_cli=1` to you php command like documented here for example: https://docs.nextcloud.com/server/17/admin_manual/configuration_server/caching_configuration.html#id1

**Comment by mzch** [comment]
Oh, it's a mistake in that post. :-P Actually I add `apc.enable_cli=1` but it doesn't fix  this error. I also tried add `--define apc.enable_cli=1` but I got the same result.

**Comment by erdoukki** [comment]
@mzch 
Have you tried to modify /etc/php/7.4/cli/conf.d/20-apcu.ini ?
Can you do a `cat /etc/php/7.4/cli/conf.d/20-apcu.ini` ?
Is the module enable ?

**Comment by R0Wi** [comment]
@mzch which command exactly produces the error? And like @erdoukki proposed could you check you enabled the `php-apcu` module by typing `php -m`?

**Comment by mzch** [comment]
- php -m (php7.4)
```
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
libxml
mbstring
memcached
msgpack
openssl
pcntl
pcre
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm`
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
1. I add `apc.enable_cli=1` to `cli/php.ini`: Failed.
2. I add `apc.enable_cli=1` to `cli/conf.d/20-apcu.ini`: Failed.
3. I run `php -d apc.enable_cli=1 cron.php`: Faied.

What can I do something else?

**Comment by R0Wi** [comment]
Ok looks good to me. Could you please provide the php-command which fails and maybe some log snippet?

**Comment by mzch** [comment]
Cron log is only `OC\HintException: [0]: Memcache \OC\emcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)`...

**Comment by mzch** [comment]
Hi,

I installed another NextCloud instance, then it's running successfully by adding `apc.enable_cli=1`...
In my original instance with trouble I ran `apcu_check.php`:

```
apcu loaded: 1
ini apc.enabled: 1
ini apc.enable_cli: 1
apc version (need min. 4.0.6): 5.1.19
apcu version (need min. 5.1.0): 5.1.19

```
Perhaps my original instance has something broken. Thanks @R0Wi :)

**Comment by leonardohlee** [comment]
> 1 in ph

where is your php.ini located ?

**Comment by matzl** [comment]
Thanks for the help!
By the way: Are we supposed to read the whole documentation for every update? And maybe I'm too old for this, but I find it quite annoying that I need to update every 4 months :cry: (including all the problems that come with it, i.e. it just took me two days because I broke my database because of a required database update, needed to update and adjust several things and so on).
I hope this agile nightly-built banana product mentality from nowadays changes back towards a "release one product a year that actually works" mentality. It would save millions of people billions of hours of their life. I feel like I spend 20% of my work and leisure time updating and then fixing software again...

**Comment by thepate94227** [comment]
> As a workaround you can use the parameter `--define apc.enable_cli=1` to tell PHP to run cli commands with APCu enabled.
> 
> Example:
> 
> ```
> sudo -u www-data php --define apc.enable_cli=1  /var/www/nextcloud/occ  maintenance:repair
> ```
> 
> Also, adding `--define apc.enable_cli=1` to the according crontab line, the cronjob will get executed again.

I tried your command, but i still get the error :

> OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

Do someone know why? In my /var/www/nextcloud/config/config.php file there is the line "'memcache.local' => '\\OC\\Memcache\\APCu',"

And how can i add the `--define apc.enable_cli=1` to the according crontab line? 

My currently version is 22.2.5, but with 22.2.4 i also had this problem. Before this version, i didn't have any errors.

**Comment by andyxheli** [comment]
@thepate94227 

Do you have this apc.enable_cli=1 added to you apcu.ini file ? 

Should be located in /etc/php/8.0/mods-available/ or /etc/php/7.4/mods-available/

Its recommended to have that for mem chacing makes nc running better. 

  'memcache.local' => '\\OC\\Memcache\\APCu',

**Comment by thepate94227** [comment]
@andyxheli thank you for your quick reply! 
In this file you mentioned (/etc/php/7.4/mods-available/apcu.ini) there is only one line:
extension=apcu.so

Is this correct? 
I just added your line (apc.enable_cli=1). What should i do next?

**Comment by andyxheli** [comment]
@thepate94227 You're very welcome!

1. please add apc.enable_cli=1 under extension=apcu.so
2. sudo service apache2 restart 
3. Should be all good 
4. Then to test do cd /var/www/nextcloud 
5. once your into the dir then do a sudo -u www-data php occ and see if it runs with no errors

**Comment by thepate94227** [comment]
@andyxheli thanks again for your help! Now everythin work! 👍

**Comment by andyxheli** [comment]
You're Welcome! Happy to help

**Comment by awestin1** [comment]
For anyone who tried all these fixes but still had it fail, I was able to fix it by installing php-redis . Some other thread seemed to indicate apcu was being phased out, so I tried:  sudo apt install php-redis . After that, all worked!

**Comment by gjanos89** [comment]
Hi Everyone,
I have tried with the same issue all of the above. Added the apc.enable_cli=1 basically in every php.ini and apcu.ini, apcu_bc.ini that I could find. Still nothing...
Then I realised the issue on my instance --> I have php version 7.4, 8.0 and 8.1 installed, so I had to specify in the OCC commands and with that in my crontab setup which version to use. So instead of ....php occ...., now I have ....php7.4 occ....
(note: it was originally installed years ago, so I had to check under /etc/php/ all 3 versions to see which one contained the apache2 folder to figure out for me it was 7.4)

OLD:
`*/5 * * * * php -f /var/www/html/nextcloud/cron.php`
NEW:
`*/5 * * * * php7.4 -f /var/www/html/nextcloud/cron.php`

Also running OCC command example:
`cd /var/www/html/nextcloud/ `
(note: check your path, maybe yours is without the /html)

`sudo -u www-data php occ `
runs to error
`sudo -u www-data php7.4 occ`
executes

I hope it helps someone...

**Comment by Sieboldianus** [comment]
My best advice: Migrate Nextcloud to the official Docker Image and configure unattended updates. A blessing, not having to manage dependencies anymore..

**Comment by chiuyau** [comment]
> apc.enable_cli=1
This is helpful!

**Comment by chiuyau** [comment]
> The issue occured during update from 20.0.12 to 21.0.4
> 
> For me, the problem was that I edited the wrong `php.ini`.
> 
> I edited
> 
> ```
> /etc/php/7.3/apache2/php.ini
> ```
> 
> But I should have edited
> 
> ```
> /etc/php/7.3/cli/php.ini
> ```
> 
> In this file, I needed to enable the extensions:
> 
> ```
> extension=redis.so
> extension=igbinary.so
> ```
> 
> Then the upgrade worked.

This is helpful!

**Comment by Reiikz** [comment]
> apc.enable_cli = 1

thanks a bunch!
My cron job wasn't running and now is :3

**Comment by brunodegoyrans** [comment]
> Using a Synology DS too and found a possible solution for @snowflakes: Add a "user_settings.ini" in "/usr/local/etc/php74/cli/conf.d" with the following content: "extension = apcu.so [apc] apc.shm_size = 64M apc.enable_cli = 1" Works fine for me. Found this solution in the synology forum (https://www.synology-forum.de/threads/nextcloudhub-21-0-1-und-cron.114219/page-2). Best regards

Using also a synology NAS but with PHP8.0. Add a new nextcloud.ini in usr/local/etc/php80/cli/conf.d did NOT work for me, even after a restart. I had to add `extension = apcu.so` into the already existing /usr/local/etc/php80/cli/conf.d.extension.ini

**Comment by himura267** [comment]
https://kr11.opsarang1.com/, Pool Salon, Office, Rest Hotel, Gangnam Pool Salon, Gangnam Office, Gangnam Rest Hotel, Gangnam Gunma, Gangnam Massage, 
Gangnam Business Trip, Gangnam Kiss Room, Gangnam Cafe

**Comment by himura267** [comment]
https://opsarang.com/ Pool salon, office, rest hotel, Gangnam pool salon, Gangnam office, Gangnam rest hotel, 
Gangnam gunma, Gangnam massage, Gangnam business trip, Gangnam kiss room, Gangnam cafe
