### ISSUE TITLE
[Bug]: Creating a password-protected link for shares takes ~1min due to dns_get_record() error

### ISSUE THREAD

**Issue by shredderique** [nextcloud/server#32014]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If a user wants to share a folder or file and checks the box in order to provide a password nothing happens.
After a very long timeout the password field appears correctly with a generated password.

Log reports
> dns_get_record(): A temporary server error occurred. at /data/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#57

### Steps to reproduce

0. Probably this bug is triggered just when behind a proxy (see config, I cannot try to reproduce without)
1. Upload a file
2. Create a link to share
3. Enable the checkbox to password-protect
4. Wait for one minute or even longer
5. Apply the pregenerated password
6. Repeat ad lib, the issue is reproducible

### Expected behavior

The dns_get_record() error should not occur and there should be no notable delay.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloudtest.zkrd.de",
            "nextcloudtest",
            "optimatch.zkrd.de"
        ],
        "overwrite.cli.url": "https:\/\/optimatch.zkrd.de\/nextcloudtest",
        "version": "22.2.6.2",
        "dbport": "",
        "logtimezone": "Europe\/Berlin",
        "default_phone_region": "DE",
        "installed": true,
        "proxy": "proxy.dmz.local:8080",
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "appstore.experimental.enabled": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": "0",
        "logfile": "\/var\/log\/nextcloud.log",
        "logdateformat": "F d, Y H:i:s",
        "skeletondirectory": "\/data\/nextcloud\/skeleton",
        "maintenance": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 3600,
        "session_keepalive": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "auto, 30",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "mail_sendmailmode": "smtp",
        "defaultapp": "files",
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bruteforcesettings: 2.4.0
  - circles: 22.3.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - drawio: 1.0.2
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_antivirus: 3.2.2
  - files_external: 1.13.1
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - group_everyone: 0.1.10
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.5
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - systemtags: 1.12.0
  - text: 3.3.1
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.2
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - encryption
  - survey_client: 0.1.5
```

### Nextcloud Signing status

```shell
Behind proxy tunneling fails
```

### Nextcloud Logs

```shell
{"reqId":"pZXnwIDPLje5jc5SqSnv","level":0,"time":"April 19, 2022 14:40:40","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_sharing","method":"PUT","url":"/nextcloud/ocs/v2.php/apps/fil
es_sharing/api/v1/shares/1698","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; L
inux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"sYUQl0ldYaQTJyOqzNhq","level":0,"time":"April 19, 2022 14:40:42","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_antivirus","method":"GET","url":"/nextcloud/ocs/v2.php/apps/p
assword_policy/api/v1/generate","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; 
Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"sYUQl0ldYaQTJyOqzNhq","level":0,"time":"April 19, 2022 14:40:42","remoteAddr":"172.20.50.55","user":"skombrink","app":"drawio","method":"GET","url":"/nextcloud/ocs/v2.php/apps/password_p
olicy/api/v1/generate","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86
_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"sYUQl0ldYaQTJyOqzNhq","level":0,"time":"April 19, 2022 14:40:42","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_sharing","method":"GET","url":"/nextcloud/ocs/v2.php/apps/pas
sword_policy/api/v1/generate","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Li
nux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"xT8kJrsJZH4ExCkf1OXn","level":0,"time":"April 19, 2022 14:40:51","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_antivirus","method":"GET","url":"/nextcloud/ocs/v2.php/apps/n
otifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubunt
u; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"xT8kJrsJZH4ExCkf1OXn","level":0,"time":"April 19, 2022 14:40:51","remoteAddr":"172.20.50.55","user":"skombrink","app":"drawio","method":"GET","url":"/nextcloud/ocs/v2.php/apps/notificati
ons/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux 
x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"xT8kJrsJZH4ExCkf1OXn","level":0,"time":"April 19, 2022 14:40:51","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_sharing","method":"GET","url":"/nextcloud/ocs/v2.php/apps/not
ifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu;
 Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"sYUQl0ldYaQTJyOqzNhq","level":3,"time":"April 19, 2022 14:40:52","remoteAddr":"172.20.50.55","user":"skombrink","app":"PHP","method":"GET","url":"/nextcloud/ocs/v2.php/apps/password_poli
cy/api/v1/generate","message":"dns_get_record(): A temporary server error occurred. at /data/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#57","userAgent":"Mozilla/5.0 (X11; Ubuntu; L
inux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2","exception":{"Exception":"Error","Message":"dns_get_record(): A temporary server error occurred. at /data/www/nextcloud/lib/
private/Http/Client/DnsPinMiddleware.php#57","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/data/www/nextcloud/lib/private/Http/Client/DnsPinMiddlew
are.php","line":57,"function":"dns_get_record"},{"file":"/data/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":74,"function":"soaRecord","class":"OC\\Http\\Client\\DnsPinMiddlew
are","type":"->"},{"file":"/data/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":132,"function":"dnsResolve","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->"},{"file":"/
data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["**
* sensitive parameters replaced ***"]},{"file":"/data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type
":"->"},{"file":"/data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** s
ensitive parameters replaced ***"]},{"file":"/data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"
},{"file":"/data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive par
ameters replaced ***"]},{"file":"/data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/data/www/
nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/data/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.p
hp","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->"},{"file":"/data/www/nextcloud/lib/private/Http/Client/Client.php","line":223,"function":"request","class":"GuzzleH
ttp\\Client","type":"->"},{"file":"/data/www/nextcloud/apps/password_policy/lib/Validator/HIBPValidator.php","line":67,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/da
ta/www/nextcloud/apps/password_policy/lib/PasswordValidator.php","line":79,"function":"validate","class":"OCA\\Password_Policy\\Validator\\HIBPValidator","type":"->"},{"file":"/data/www/nextcloud/
apps/password_policy/lib/Generator.php","line":88,"function":"validate","class":"OCA\\Password_Policy\\PasswordValidator","type":"->"},{"file":"/data/www/nextcloud/apps/password_policy/lib/Control
ler/APIController.php","line":77,"function":"generate","class":"OCA\\Password_Policy\\Generator","type":"->"},{"file":"/data/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,
"function":"generate","class":"OCA\\Password_Policy\\Controller\\APIController","type":"->"},{"file":"/data/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"execu
teController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/data/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\H
ttp\\Dispatcher","type":"->"},{"file":"/data/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/data/www/nextcloud/ocs/
v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/data/www/nextcloud/ocs/v2.php","line":23,"args":["/data/www/nextcloud/ocs/v1.php"],"function":"require_once"
}],"File":"/data/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"R0gfFo4uOPHwMQH1dCVK","level":0,"time":"April 19, 2022 14:41:22","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_antivirus","method":"GET","url":"/nextcloud/ocs/v2.php/apps/n
otifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubunt
u; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"R0gfFo4uOPHwMQH1dCVK","level":0,"time":"April 19, 2022 14:41:22","remoteAddr":"172.20.50.55","user":"skombrink","app":"drawio","method":"GET","url":"/nextcloud/ocs/v2.php/apps/notificati
ons/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux 
x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"R0gfFo4uOPHwMQH1dCVK","level":0,"time":"April 19, 2022 14:41:22","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_sharing","method":"GET","url":"/nextcloud/ocs/v2.php/apps/not
ifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu;
 Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"e3IKEOZRfc59MoTFRl3L","level":0,"time":"April 19, 2022 14:41:52","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_antivirus","method":"GET","url":"/nextcloud/ocs/v2.php/apps/n
otifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubunt
u; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"e3IKEOZRfc59MoTFRl3L","level":0,"time":"April 19, 2022 14:41:52","remoteAddr":"172.20.50.55","user":"skombrink","app":"drawio","method":"GET","url":"/nextcloud/ocs/v2.php/apps/notificati
ons/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux 
x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
{"reqId":"e3IKEOZRfc59MoTFRl3L","level":0,"time":"April 19, 2022 14:41:52","remoteAddr":"172.20.50.55","user":"skombrink","app":"files_sharing","method":"GET","url":"/nextcloud/ocs/v2.php/apps/not
ifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu;
 Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"22.2.6.2"}
```

### Additional info

Maybe related https://github.com/nextcloud/server/issues/28105?
This bug was present as of Nextcloud server version 22.2.3

**Comment by shredderique** [comment]
I meanwhile upgraded to 23.0.3 and the issue persists.

**Comment by kesselb** [comment]
I guess the error was fixed by https://github.com/php/php-src/commit/45f52285f6ee251dc40f31c365b0eb9e6a3e0881. 

The fix is released with php 7.4.27, php 8.0.14, php 8.1.0

**Comment by shredderique** [comment]
Of course, it is 7.4.3-4ubuntu2.10
Unfortunately this is the most recent version on Ubuntu LTS 20.4.

**Comment by kesselb** [comment]
Can be fixed by updating to php 7.4.27.

**Comment by shredderique** [comment]
I have upgraded to php version 7.4.30-1+ubuntu20.04.1+deb.sury.org+1 and the issue persists.
