### ISSUE TITLE
[Bug]: Unhandled exception when running occ encryption:decrypt-all

### ISSUE THREAD

**Issue by b12f** [nextcloud/server#32818]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to decrypt a nextcloud instance for migration, I ran into an exception when running the following command:

```
docker-compose run --user www-data nextcloud php occ encryption:decrypt-all
```

It was running for a while, but when I left the process unattended this exception was thrown:

```
 decrypt files for user $redacted_user_b (2 of 8): /$redacted_user_b/files/Mail/byb@$redacted_filename,
 [>]An unhandled exception has been thrown:
TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php:784
Stack trace:
#0 /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php(784): fclose(false)
#1 /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php(679): OC\Files\Storage\Wrapper\Encryption->copyBetweenStorage(Object(OC\Files\Storage\Wrapper\Encryption), 'files/Mail/byb@...', 'files/Mail/byb@...', false, false)
#2 /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php(361): OC\Files\Storage\Wrapper\Encryption->copyFromStorage(Object(OC\Files\Storage\Wrapper\Encryption), 'files/Mail/byb@...', 'files/Mail/byb@...')
#3 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(290): OC\Files\Storage\Wrapper\Encryption->copy('files/Mail/byb@...', 'files/Mail/byb@...')
#4 /var/www/html/lib/private/Files/View.php(935): OC\Files\Storage\Wrapper\Wrapper->copy('files/Mail/byb@...', 'files/Mail/byb@...')
#5 /var/www/html/lib/private/Encryption/DecryptAll.php(264): OC\Files\View->copy('/$redacted_user_b/files/Mail...', '/$redacted_user_b /files/Mail...')
#6 /var/www/html/lib/private/Encryption/DecryptAll.php(229): OC\Encryption\DecryptAll->decryptFile('/$redacted_user_b /files/Mail...')
#7 /var/www/html/lib/private/Encryption/DecryptAll.php(188): OC\Encryption\DecryptAll->decryptUsersFiles($redacted_user_b, Object(Symfony\Component\Console\Helper\ProgressBar), '$redacted_user_b (2 of 8)')
#8 /var/www/html/lib/private/Encryption/DecryptAll.php(99): OC\Encryption\DecryptAll->decryptAllUsersFiles($redacted_user_a)
#9 /var/www/html/core/Command/Encryption/DecryptAll.php(173): OC\Encryption\DecryptAll->decryptAll(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), '')
#10 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Encryption\DecryptAll->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Encryption\DecryptAll), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/console.php(99): OC\Console\Application->run()
#16 /var/www/html/occ(11): require_once('/var/www/html/c...')
#17 {main}
```

After that, I updated the image:

```
# docker-compose pull
Pulling nextcloud          ... done
Pulling redis-nextcloud    ... done
Pulling postgres-nextcloud ... done
# docker-compose restart
Restarting postgres-nextcloud ... done
Restarting nextcloud          ... done
Restarting redis-nextcloud    ... done
```

And tried again:

```
# docker-compose run --user www-data nextcloud php occ encryption:decrypt-all -vvv
Nextcloud is in maintenance mode, hence the database isn't accessible.
Cannot perform any command except 'maintenance:mode --off'

Maintenance mode must be disabled when starting decryption,
in order to load the relevant encryption modules correctly.
Your instance will automatically be put to maintenance mode
during the actual decryption of the files.
```

Apparently after this crash, the instance had remained in maintenance mode. I disabled it and tried again

```
# docker-compose run --user www-data nextcloud php occ maintenance:mode --off
Maintenance mode disabled
# docker-compose run --user www-data nextcloud php occ encryption:decrypt-all -vvv
Server side encryption not enabled. Nothing to do.
```

If I understand this correctly, the decryption process marked the server as decrypted before this was actually the case. I'm not sure how to best continue here. Can I force a rerun of the decryption with something like `--ignore-errors`?

### Steps to reproduce

1. Enable encryption, have encrypted files. A few files appear not to have been encrypted for this user at all, but I'm unsure why that is.
2. Try to disable decryption via the `occ` command
3. Leave the process running

### Expected behavior

The decryption command should not completely fail if one file fails to decrypt, I'd expect an option to override errors, or at least to be able to just re-run the command to keep trying to decrypt. The server should not be marked as decrypted before all files have been decrypted.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Other

### Database engine version

psql (PostgreSQL) 10.21 (Debian 10.21-1.pgdg90+1)

### Is this bug present after an update or on a fresh install?

Stays present after update

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.0.1
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.6
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - drawio: 1.0.2
  - encryption: 2.11.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - keeweb: 0.6.8
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.1
  - maps: 0.1.9
  - nextcloud_announcements: 1.12.0
  - notes: 4.2.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - ownpad: 0.6.16
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - bruteforcesettings
  - end_to_end_encryption
  - files_external
  - files_trashbin
  - integration_github
  - spreed
  - user_ldap
```

### Additional info

The sha of the docker image that was running during decryption is `e848004dfd99bb0e23bc841d3e6f078494f49dcc59b875083853aebf611cb9ac`(`nextcloud:latest` from about 6 months ago)

**Comment by kesselb** [comment]
I would suggest to rollback to your backup before the decryption, update the nextcloud a newer version (to have https://github.com/nextcloud/server/pull/30160) and run the decryption again. 

Closing the issue because the code is already fixed by https://github.com/nextcloud/server/pull/30160.

**Comment by b12f** [comment]
Hi @kesselb and thanks for your quick response. 

I've taken your advice and imported the database and files on a fresh install. I then updated nextcloud to 24.0.1 and updated all apps to match. Afterwards, I scanned the filesystem for files with `files:scan`.

#30160 does not fix this issue since the error is from the code above. It seems like an `fopen` is not working for the encrypted source file (I checked, and for the one error I found it seems like this file is missing).

I guess my ideal here would be that the reason the file cannot be decrypted would be logged, but decryption continues afterwards. Instead, [the exception is rethrown](https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/Wrapper/Encryption.php#L829). This causes a single broken or missing file to block decryption for the whole instance.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/0619207f13792250aea775a2c3133d41ab625980/lib/private/Files/Storage/Wrapper/Encryption.php#L781-L785

Sounds good to me. So in your case $source is already false, streamCopy does not care and the fclose in L784 fails. That could be a missing file yes. 

https://github.com/nextcloud/server/pull/30160 does not help here indeed. I guess it would work to move fclose (including the is_resource check) to a finally block. But someone with more knowledge about encryption should have a look. 

cc @PVince81 @artonge

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
