### ISSUE TITLE
[Bug]: Tried to log in "username" but could not verify token

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#33919]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Not sure what's causing this the user is LDAP backend

### Steps to reproduce

1.Open brower 
2.go to server.domain.com
3.takes to me dashboard 

### Expected behavior

Should not see this error in logs

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - officeonline: 1.1.3
  - password_policy: 1.15.0
  - photos: 1.7.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0-beta.2
  - survey_client: 1.13.0
  - suspicious_login: 4.2.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.6.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.4.0
  - circles: 23.1.1
  - encryption
  - files_downloadactivity: 1.13.0
  - groupfolders: 12.0.1
  - impersonate: 1.11.0
  - notify_push: 0.4.0
  - socialsharing_email: 2.5.0
  - support: 1.8.0
  - twofactor_admin: 3.2.0
```

### Nextcloud Logs

```shell
{"reqId":"RSUtKkS7Br5VdD2bT5QY","level":3,"time":"2022-09-06T13:53:34+00:00","remoteAddr":"10.0.10.90","user":"--","app":"core","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fapps%2Fdashboard%2F","message":"Tried to log in "username" but could not verify token","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.8","data":{"app":"core"},"id":"63175db7214f1"}
```

### Additional info

![image](https://user-images.githubusercontent.com/59488153/188667332-eade6002-9ea4-45ab-bf65-d5af348cfbe2.png)

**Comment by szaimen** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Whohoo. I've rarely been so happy to see an error in the logs.

So, this is from https://github.com/nextcloud/server/pull/33772. Can you tell if this log was triggered by one (or a few) users? You could cross-check with the access logs and the IPs.

My suspicion is that this happens when the users open their browser in the morning. Over night the server's php session has expired and the user probably had more than one tab open. The browser then sends off multiple concurrent requests and each of them tries to recover the session from cookies. But then only one request actually wins because it will take the valid token. The other requests show up too late, when the valid token had already been cleared from the database.

Just a theory but curios to hear if this could have been the case for you or your users.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/33930 adds more debugging insights. If you can, apply the patch on your instance, set the log level to debug for a day and then check if `Regenerating cookie login token for {uid} after successful verification` shows up shortly before the first `Tried to log in {uid} but could not verify token`. That would confirm my theory.

**Comment by andyxheli** [comment]
I think your right because I believe I did have alot of tabs open from the night and in the morning I open a few sessions and accessed the server but the other tabs where closed. Once I get in the office I will test and let you know

**Comment by andyxheli** [comment]
@ChristophWurst should i set the level to debug in config.php file currently its set to 2 or should I just out the logger on the web to debug ?

**Comment by andyxheli** [comment]
@ChristophWurst I think we're good i applied the #33930 

seen this in the debug logs 

{"reqId":"VdFFfpQ5RgUst3jHnVid","level":0,"time":"2022-09-07T14:33:29+00:00","remoteAddr":"1.5.5.11","user":"--","app":"core","method":"GET","url":"/","message":"Regenerating cookie login token for admin after successful verification","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.8","data":{"app":"core"}}

**Comment by ChristophWurst** [comment]
Okay but do you see a bunch of `Tried to log in admin but could not verify token` logged afterwards?

One single `Regenerating cookie login token for admin after successful verification` is fine. It means a request revived a valid session.

**Comment by andyxheli** [comment]
Just tried it and 

![image](https://user-images.githubusercontent.com/59488153/188944873-f0228e6d-3b0a-492f-9ae3-8275b09d83b7.png)

**Comment by andyxheli** [comment]
Tried it from a different pc  
<html>
<body>


Debug | core | Regenerating cookie login token for axheli after successful verification |   | a minute ago
-- | -- | -- | -- | --
Error | core | Tried to log in axheli but could not verify token |   | a minute ago
Debug | core | Regenerating cookie login token for axheli after successful verification |   | a minute ago


</body>
</html>

But should that error be under  debug ?

**Comment by andyxheli** [comment]
Yea I think either warring or info since it really giving you info and technically since its not something to worry about . What do you think ? Id suggest info but what ever you think is best :)

**Comment by ChristophWurst** [comment]
The bigger picture is that once I have clear insight into the token verification errors and what leads up to them, I want to actually fix them. They shouldn't be part of the auth flow. A token mismatch should only be detected for malicious users, not for someone who opened their browser in the morning with Nextcloud pages open.

**Comment by andyxheli** [comment]
Ahhh i see that makes a lot more sense if you need any testing from my end I'm happy to help.

**Comment by Rello** [comment]
having the same issue on my NC25
only additional info I find is that the php/sessions/ directory had multiple entries per attempt.
dont know if relevant?

**Comment by ChristophWurst** [comment]
@Rello do you have https://github.com/nextcloud/server/pull/33930 applied as well? Would be interesting to know if a token was used successfully before other requests failed to use the same.

**Comment by Rello** [comment]
I am on beta 6 - and this should have been merged, correct?

**Comment by ChristophWurst** [comment]
It is not merged. Right now this is an optional patch.

**Comment by LokeYourLord** [comment]
Just wanted to chime in that I am facing the same issue. Some accounts straight up can not login at all on their Browsers, and need to use temporary accounts to get into the drive.

**Comment by ChristophWurst** [comment]
> Just wanted to chime in that I am facing the same issue. Some accounts straight up can not login at all on their Browsers, and need to use temporary accounts to get into the drive.

Could you ask one of the affected users to clear their cookies and see if that helps?

**Comment by LokeYourLord** [comment]
> > Just wanted to chime in that I am facing the same issue. Some accounts straight up can not login at all on their Browsers, and need to use temporary accounts to get into the drive.
> 
> Could you ask one of the affected users to clear their cookies and see if that helps?

Uhh, I was physically at his PC earlier, so when that happens again, I'll make sure to try that. On another note, it even happened to me on my main, super admin account. My interface sometimes opened for a quick sec before it gave me a countdown for logging me out, and when I went quickly into settings from there, it stopped and fixed it. Truly weird.

**Comment by tsipizic** [comment]
> > Just wanted to chime in that I am facing the same issue. Some accounts straight up can not login at all on their Browsers, and need to use temporary accounts to get into the drive.
> 
> Could you ask one of the affected users to clear their cookies and see if that helps?

I am also affected by that and cookie cleaning/private window did not help. Server reboot/PHP cache clean helped though

**Comment by LokeYourLord** [comment]
> > > Just wanted to chime in that I am facing the same issue. Some accounts straight up can not login at all on their Browsers, and need to use temporary accounts to get into the drive.
> > 
> > 
> > Could you ask one of the affected users to clear their cookies and see if that helps?
> 
> I am also affected by that and cookie cleaning/private window did not help. Server reboot/PHP cache clean helped though

That's what I did as well as soon as 3 accounts had that issue (and I can't create hundreds of temporary accounts as a workaround), and it solved it. But I also can't reboot the server daily really.

**Comment by solracsf** [comment]
This is not a v25 bug only; I get this same error on 23.0.10.

```
{
  "reqId": "dccjg6BA5aG2UhFJyBRU",
  "level": 3,
  "time": "2022-10-15T14:42:38+00:00",
  "user": "--",
  "app": "core",
  "method": "GET",
  "url": "/csrftoken",
  "message": "Tried to log in username but could not verify token",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0",
  "version": "23.0.10.1",
  "data": {
    "app": "core"
  },
  "id": "634ac795cdd29"
}
```

**Comment by Sieboldianus** [comment]
I got it on 24, too.

**Comment by andyxheli** [comment]
Yes, same got the errors on 24.0.6

**Comment by ChristophWurst** [comment]
The error condition had been there for a very very long time. The only thing that changed is that we now log it and https://github.com/nextcloud/server/pull/33772 was backported to 24 and 23.

**Comment by solracsf** [comment]
In case of SAML, it's just spamming the logs with more than 4K entries today (less than 100 users).

**Comment by evilaliv3** [comment]
As an update we have other evidences of this bugs on this discussion: https://github.com/nextcloud/all-in-one/discussions/1300

Here i'm testing myself a new setup on Nextcloud AIO and i'm the only user

**Comment by andyxheli** [comment]
Also seems like sessions get logged off very often now on NC 25

**Comment by eibex** [comment]
I started getting this on 24.0.6.
It wasn't happening with Chrome but it is now happening with Firefox.

The logs don't offer any information other than my IP and the action (`POST` login).

I am not using LDAP or other user databases. I am using the default NC backend. The only thing that comes to mind that doesn't always play nice with logins is 2FA (e.g. sometimes you need to login twice with IPv6).

**Comment by pmlejnek** [comment]
> This is not a v25 thing only (as it has been backported); I get this same error on **v23**.0.10 _(after upgrade from v23.0.9)_. **Using SSO/SAML app**. Different users logged, a few lines per user.
> 
> As far as i can see, it triggers for every user.
> 
> ```
> {
>   "reqId": "dccjg6BA5aG2UhFJyBRU",
>   "level": 3,
>   "time": "2022-10-15T14:42:38+00:00",
>   "user": "--",
>   "app": "core",
>   "method": "GET",
>   "url": "/csrftoken",
>   "message": "Tried to log in username but could not verify token",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0",
>   "version": "23.0.10.1",
>   "data": {
>     "app": "core"
>   },
>   "id": "634ac795cdd29"
> }
> ```



> This is not a v25 thing only (as it has been backported); I get this same error on **v23**.0.10 _(after upgrade from v23.0.9)_. **Using SSO/SAML app**. Different users logged, a few lines per user.
> 
> As far as i can see, it triggers for every user.
> 
> ```
> {
>   "reqId": "dccjg6BA5aG2UhFJyBRU",
>   "level": 3,
>   "time": "2022-10-15T14:42:38+00:00",
>   "user": "--",
>   "app": "core",
>   "method": "GET",
>   "url": "/csrftoken",
>   "message": "Tried to log in username but could not verify token",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0",
>   "version": "23.0.10.1",
>   "data": {
>     "app": "core"
>   },
>   "id": "634ac795cdd29"
> }
> ```

The same for me, after the same version upgrade.

**Comment by pmlejnek** [comment]
> This is not a v25 thing only (as it has been backported); I get this same error on **v23**.0.10 _(after upgrade from v23.0.9)_. **Using SSO/SAML app**. Different users logged, a few lines per user.
> 
> As far as i can see, it triggers for every user.
> 
> ```
> {
>   "reqId": "dccjg6BA5aG2UhFJyBRU",
>   "level": 3,
>   "time": "2022-10-15T14:42:38+00:00",
>   "user": "--",
>   "app": "core",
>   "method": "GET",
>   "url": "/csrftoken",
>   "message": "Tried to log in username but could not verify token",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0",
>   "version": "23.0.10.1",
>   "data": {
>     "app": "core"
>   },
>   "id": "634ac795cdd29"
> }
> ```

The same for me, after the same version upgrade.

**Comment by mikeage** [comment]
Upgraded to 25.0.0.18 about 5 days ago... hit this just now. Restarting the server container "fixed" it, but clearing cookies and localstorage did not.

**Comment by DrMurx** [comment]
I'm hitting this issue too when I open a browser that has been logged into my Nextcloud the day before.

My setup is Nextcloud FPM from docker library and nginx, which in turn is behind a ingress proxy.

Deleting the `nc_session_id` cookie in the login page helps.

**Comment by Gandalf1783** [comment]
I can double this. Deleting my cookies solved my login issue.
However, in my case the error message was always "Tried to log in administrator but could not....".
It was always administrator, no matter which username I typed.

**Comment by JohnEridium** [comment]
I'm having the same or very similar problem, where the error occurs occasionally when I'm trying to log in from my iPhone in Safari (iOS 16.1). For some reason, I don't have this Problem on my iMac in Safari (macOS 13.0).

**Comment by LokeYourLord** [comment]
> I'm having the same or very similar problem, where the error occurs occasionally when I'm trying to log in from my iPhone in Safari (iOS 16.1). For some reason, I don't have this Problem on my iMac in Safari (macOS 13.0).
> Edit: NC version is 24.0.6

It's Browser indifferent, and is entirely random when it happens actually. I had first happen to Chromium only users (Chrome, Brave, all that dreck), and then GeckoEngine (Firefox) users, and then all others here and there.

**Comment by Gandalf1783** [comment]
I had reverted my Nextcloud VM using a backup, and what seemed to fix it permanently was to rerun the update, so it would update the database. 

What also helped, was a new install with a new database, and then changing the database credentials back to the old ones. Had no issues since.

Since even on new installations using the old database resulted in the same issues above, it could be a table that was not updated correctly?

**Comment by ChristophWurst** [comment]
There will always be concurrent requests where one of the requests takes the valid token and causes the other requests to fail. This is bad in isolation but unavoidable. We need to find a way to retry those failed requests with the then valid cookie and session.

Until then I suggest to lower the log level of this "error" to info: https://github.com/nextcloud/server/pull/35007. That is because it's not really an application error but rather a bad authentication state. The admins can't fix this, as we have seen above. So there is also no need to alarm them with log spams.

**Comment by szaimen** [comment]
Honestly, I guess this is a bit more important than thought because the failed login attempts seem to trigger the brute-force protection IIRC...

**Comment by ChristophWurst** [comment]
That would be new for me. Do you have any proof for that claim?

**Comment by ChristophWurst** [comment]
I can only repeat that this is not a new error or condition. This same token mismatch happened in the past. But it happened silently.

**Comment by Larx** [comment]
> I can only repeat that this is not a new error or condition. This same token mismatch happened in the past. But it happened silently.

In previous versions, I also noticed that you could get logged out randomly/occasionally. But you could always re-log in (sometimes two attempts were needed).
But currently I get logged out and am no longer able to log before I clear the cookies of the site. This is a major inconvenience, unfortunately.

**Comment by fuomag9** [comment]
So it was not only me then! I get logged out a lot and need two attempts to relogin.

**Comment by DasMuelli** [comment]
Have the same on NC 25.01

```{"reqId":"EUOVMHQPYMxoAB3ZCKgf","level":3,"time":"2022-11-13T18:40:06+00:00","remoteAddr":"2003:f9:5716:8000:4e0:7588:2dc7:5c75","user":"--","app":"core","method":"GET","url":"/login","message":"Tried to log in lars but could not verify token","userAgent":"Mozilla/5.0 (Linux; Android 13; Pixel 6 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36","version":"25.0.1.1","data":{"app":"core"}}```

What can I do?

**Comment by Gandalf1783** [comment]
Why isnt the cookie then just cleared?
If the Webserver responds with that, cant the JS in the Browser just clear the cookie and the user just can "relogin"? 

It could also simply display a error-message that you have to re-login in order to use the Nextcloud instance again.

**Comment by Larx** [comment]
> Why isnt the cookie then just cleared? If the Webserver responds with that, cant the JS in the Browser just clear the cookie and the user just can "relogin"?
> 
> It could also simply display a error-message that you have to re-login in order to use the Nextcloud instance again.

Please consider this at least as workaround. In the current situation I can only re-login after clearing the cookies, which fpr means that any other cookie for my domain will also be deleted and I loose settings and logins for any other web service hosted there (or is there any more fine grained cookie control method in Firefox than the domain name?).

**Comment by Gandalf1783** [comment]
I didnt mean to clear all of them, but if Nextcloud only deletes cookies of itself, e.g. that nextcloud account cookie.

**Comment by ChristophWurst** [comment]
A login loop also seems to happen when Redis is restarted while used for session storage

**Comment by aigarslv** [comment]
I am facing same issue and log is full with entries: **Tried to log in [UID] but could not verify token.** (I use LDAP) Some users are fine, others cannot work no matter what, they get sent back to login page after ~3 minutes. Issue persists even when user opens nextcloud in a different browser.

**Comment by markusTraber** [comment]
Same for me: **Tried to log in [UID] but could not verify token.**

- Nextcloud 25.0.1
- Docker
- LDAP
- NGINX

In my case it helps to clear cookies and reload. Otherwise I am stuck in a Login-Loop.

**Comment by phonon112358** [comment]
Same issue here:
Nextcloud 25.0.1, nginx, php 8.1 

clearing cookies/browser cache and rebooting the server didn't help for me .

**Comment by nilshellerhoff** [comment]
Just wanted to comment to say it's the same issue here:
- Nextcloud 24.0.7 (updated from 24.0.6 yesterday, maybe that's relevant)
- user could not login, would get a blank screen
- after removing the user from all groups it suddenly worked again

**Comment by ChristophWurst** [comment]
> EDIT: Also, applying #35007 doesn't help

That PR only changes the log level and not any logic.

**Comment by ChristophWurst** [comment]
I hope so but I also don't know. As you can read from my earlier comments this error only happens sporadically. We have not been able to trigger it reliably. I was lucky two times where it also happened on my dev environment. However, the issue went away before I could step through the code paths with my debugger. In that way, I was never able to reproduce the infinite login loop, only a temporary loop.

Once we know what the problem is we can try to improve and fix the situation.

**Comment by aigarslv** [comment]
@ChristophWurst I have attached a logfile of a possible problem. As I stated above - LDAP user can login, work for 5-6 minutes and then gets auto redirected to login screen. Stating that he is not logged in.

https://www.dropbox.com/s/61x624ddteju02i/logged_out.txt?dl=0

**Comment by ChristophWurst** [comment]
I have an idea but I'm honestly not sure if it helps eliminate all login loops or has any other side effects. But you can find a patch at https://github.com/nextcloud/server/pull/35419. I was able to test this shortly yesterday. But as mentioned before I'm not able to reliably send myself into the login loop so I can't test a second time until the problem randomly returns.

https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html for those who live a risky life and want to test the patch in production.

**Comment by phonon112358** [comment]
I tested the PR https://github.com/nextcloud/server/pull/35419 and can confirm that it solved the issue on my NC instance.

**Comment by phonon112358** [comment]
However, PR https://github.com/nextcloud/server/pull/35419 doesn't resolve the root issue in my opinion ... 
Why does one suddenly get logged out, but NC doesn't recognize that one got logged out?? 

https://github.com/nextcloud/server/pull/35419 is a good workaround but I guess not the real solution ....

**Comment by ChristophWurst** [comment]
I agree that it's not fixing the root of the issue but the symptoms.

**Comment by Larx** [comment]
Please release a fixed version asap, even if it's only a workaround. It's extremely annoying to get randomly logged out, and the only chance to re-login is to clear the cookies. If you don't know the workaround (and how to do it in your browser), the user experience is like a DoS ...

**Comment by LokeYourLord** [comment]
> Please release a fixed version asap, even if it's only a workaround. It's extremely annoying to get randomly logged out, and the only chance to re-login is to clear the cookies. If you don't know the workaround (and how to do it in your browser), the user experience is like a DoS ...

I personally haven't experienced the issue for a while, I don't know why however, but I'd agree. The issue is that, even when used for a team project or stuff like that (or any larger projects or even commercial projects, you name it), anyone who isn't tech-savvy or even partially intelligent when it comes to Computers, will just stop using it, complain that it isn't "lIkE gOoGlE" and then fuck off while throwing a hissy-fit. Some issues are kind of easier to deal with and ignore, but getting randomly logged out and being unable to login is such a core issue that the entire "feel" and experience of said product is basically entirely ruined. I mean, I have people bitch and complain to me (even though I didn't make it, I am only hosting our instance and am the Web-Admin), that the "Audio Player", despite only needing to be used for the most simple shit, isn't "feature-packed enough", lacking stuff like it actually being bigger so scrobbling along the bar is easier with higher precision, and a simple repeat button. So yeah, for many people this is actually a "quitting factor", and even though it might not be such a big deal to us Web/Network Admins, it will definitely make many users re-evaluate their usage of said product twice in the future.

**Comment by ChristophWurst** [comment]
@lark @LokeYourLord help us test https://github.com/nextcloud/server/pull/35419 on your production environments. If we have some more certainty that it fixes the symptoms but doesn't cause any other issues that we can ship the workaround.

**Comment by LokeYourLord** [comment]
> @lark @LokeYourLord help us test #35419 on your production environments. If we have some more certainty that it fixes the symptoms but doesn't cause any other issues that we can ship the workaround.

Uhh ok, I mean it would be risky for me kind of, but I'd be willing to test it. However as I've said, I haven't experienced it for quite a while ever since I upgraded to NC25 and fixed my "MySQL" issues I had (2006 error), and a bunch of other problems. IF it does return, I'll try out your patch though :) (because right now it would be kind of pointless as I am not facing said issue at all).

**Comment by ChristophWurst** [comment]
You can apply the patch nevertheless just to see if it has any other negative impact.

**Comment by nonplusnl** [comment]
Having the same issue, login fails after overnight browser reopening. Only happens when app extension Snappymail was active (see issue mentioned above), because Snappymail may be "too fast". Never had this issue before, and never have it when browser closes while other Nextcloud app is open. Still, an app being efficiently fast should not create the need to manually clear cookies before being able to login?

**Comment by brotkastn** [comment]
> @lark @LokeYourLord help us test #35419 on your production environments. If we have some more certainty that it fixes the symptoms but doesn't cause any other issues that we can ship the workaround.

I just had to apply  #35419 because some who could not login also did not want to clear his complete browsing history on his iPhone. I could still login after applying, and it seems to work for those who got stuck in the login loop.

**Comment by detrout** [comment]
I ran into this bug on Debian 11 using php7.4-fpm 7.4.33 and nextcloud 25.0.2 connecting with Firefox 108.0. I manually applied the patch in #35419 and was able to log in.

**Comment by LokeYourLord** [comment]
> You can apply the patch nevertheless just to see if it has any other negative impact.

Sorry, I've been really busy. But wanted to chime in that I had also applied the patch soon after, and it seems that so far there's been no case of login issues. To me, the bug seems fixed (or at least mitigated).

**Comment by ChristophWurst** [comment]
Interesting enough the login loops happened a lot for me on two instances around November 2022. For the past few weeks the issue has not shown once.

**Comment by JohnEridium** [comment]
I updated to Nextcloud 25.0.3.2 two days ago and I am facing this issue once again on iOS in Safari. Unfortunately, deleting the website data does not fix the issue for me (Settings --> Safari --> Advanced --> Website Data --> deleted data from my NC domain and restarted safari).

Which logs should I provide?


(Screenshot taken from graylog)
![image](https://user-images.githubusercontent.com/40388847/213581604-a202cabb-45b0-48db-a896-1c93eaa30f8f.jpeg)

**Comment by sherpadawan** [comment]
Same error on 25.0.1 ... really annoying, no bruteforce data in database, varnish cache refreshed on my gandi hosting ...
I am facin this issue for one year, quite regulary, but I used to fix it by resetting user password, and cleaning brute force via  occ
Nothing special in occ user:setting  ...
Noting weird in logs but the message which gave birth of this bug report.
Any clue ?

**Comment by LokeYourLord** [comment]
> Same error on 25.0.1 ... really annoying, no bruteforce data in database, varnish cache refreshed on my gandi hosting ...
> I am facin this issue for one year, quite regulary, but I used to fix it by resetting user password, and cleaning brute force via  occ, nowadays ot does not work anymore, stuck on the login screen !!
> Nothing special in occ user:setting  ...
> Noting weird in logs but the message which gave birth of this bug report.
> Any clue ?

Install the suggested fix, it works.

**Comment by sherpadawan** [comment]
I did it several times ... nothing better happened

**Comment by sherpadawan** [comment]
OK the fiwx works https://github.com/nextcloud/server/pull/35419/commits/f22101d4213768066d3dcbde81898dd64ce46445#diff-af67c083dc101bd3457884ce98ffe78e12f24150e1962d78bdbbe452173df3b9
`wget https://raw.githubusercontent.com/nextcloud/server/f22101d4213768066d3dcbde81898dd64ce46445/core/Controller/LoginController.php
cp LoginController.php core/Controller/`
Thanks a lot

**Comment by lemmy04** [comment]
I'm having this all of a sudden on an up-to-date 25.0.3 after upgrading php from pph7 to php8.
please release a fixed version ASAP, thanks!

**Comment by LokeYourLord** [comment]
> I'm having this all of a sudden on an up-to-date 25.0.3 after upgrading php from pph7 to php8.
> please release a fixed version ASAP, thanks!
> edit: the workaround from the post above this one works for me too.

The fix has been mentioned a quadrillion times here now. Apply that one and see if it works for you :)

**Comment by LokeYourLord** [comment]
> > > I'm having this all of a sudden on an up-to-date 25.0.3 after upgrading php from pph7 to php8.
> > > please release a fixed version ASAP, thanks!
> > > edit: the workaround from the post above this one works for me too.
> > 
> > 
> > The fix has been mentioned a quadrillion times here now. Apply that one and see if it works for you :)
> 
> Did that already, it works, it should be RELEASED is what I'm saying.

Well I mean in that case it ain't a huge problem for us, but I agree, I don't understand why it hasn't made it into the main release somehow yet when it seems to be working fine with no side effects to speak of. Makes you wonder 🤔

**Comment by ChristophWurst** [comment]
I'm sorry to break your negativity spiral but the fix went into stable25 and is the QA pipeline for 25.0.4. RC1 has the fix, if you want to upgrade early. Cheers.

**Comment by lemmy04** [comment]
that's great, all I wanted to know !

**Comment by LokeYourLord** [comment]
> I'm sorry to break your negativity spiral but the fix went into stable25 and is the QA pipeline for 25.0.4. RC1 has the fix, if you want to upgrade early. Cheers.

Not a negativity spiral, merely an observation. But good to know that it'll be out in the next one then ^^

**Comment by nderambure** [comment]
This is a really good news, thx for the fix and all the work ;)

**Comment by FelixBuehler** [comment]
I had the same error in my log and already used the fix. Now the error in my log is gone, but I still can't login. 
I also tried occ maintenance:repair, but still, I just can't login. It always loads for 5-30 seconds and then the login screen comes back up. No more logs to determine why. 

Anyone who can help me?


My log is flooded with multiple of these lines:
```
{"reqId":"DDEiwUmoxHZgU2LY0imQ","level":0,"time":"2023-02-13T14:36:28+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\DAV\\BackgroundJob\\UploadCleanup job with ID 430393","userAgent":"--","version":"25.0.3.2","data":{"app":"cron"}}
{"reqId":"DDEiwUmoxHZgU2LY0imQ","level":0,"time":"2023-02-13T14:36:28+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\DAV\\BackgroundJob\\UploadCleanup job with ID 430393 in 0 seconds","userAgent":"--","version":"25.0.3.2","data":{"app":"cron"}}
{"reqId":"uWddjjap8fP60sDZMnAa","level":0,"time":"2023-02-13T14:36:28+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 428385","userAgent":"--","version":"25.0.3.2","data":{"app":"cron"}}
```

**Comment by Hubsi3** [comment]
Hello, I'm using NC 26 and still the same problem in safari only. Does anyone have an idea? Same error in logs: [Tried to log in "username" but could not verify token].

Have to re-login every time, also on mobile (iOS Safari).

It was working fine with NC25...

**Comment by Yetangitu** [comment]
This problem does not seem to have been solved in v26.0.0.11 - even though https://github.com/nextcloud/server/pull/35419 was merged - seeing how as I'm currently unable to login using Firefox/Android on a device which had a single tab open yesterday. Deleting site data does not change this, nor does running occ maintenance:repair.

I _can_ login using a different browser but not with Firefox, all I get is an empty page showing the site logo and the footer - there is no error message but no login/password request either.

This does _not_ work:

 - deleting all site data and cookies for the domain
 - force-stopping and restarting Firefox/Android
 - rebooting the device
 - trying different network connections - wifi, 4G, VPN
 - deleting browsing history for the affected domain
 - using another open session to delete all sessions for the affected device (in _Settings->Security->Devices & Sessions_)

This _does_ work:

 - using a different browser
 - using private mode in Firefox

The error message in the log is the one which has been shown countless times already: `Tried to log in "username" but could not verify token`:

```
{"reqId":"aupvuif3Msicz86FxhbY","level":1,"time":"April 06, 2023 06:06:04","remoteAddr":"192.168.9.2","user":"--","app":"core","method":"GET","url":"/login","message":"Tried to log in frank but could not verify token","userAgent":"Mozilla/5.0 (Android 9; Mobile; rv:109.0) Gecko/112.0 Firefox/112.0","version":"26.0.0.11","data":{"app":"core"}}
{"reqId":"q8JEudtB0oT3gfNqLYye","level":1,"time":"April 06, 2023 06:06:04","remoteAddr":"192.168.9.2","user":"--","app":"core","method":"GET","url":"/apps/theming/image/background?v=27","message":"Tried to log in frank but could not verify token","userAgent":"Mozilla/5.0 (Android 9; Mobile; rv:109.0) Gecko/112.0 Firefox/112.0","version":"26.0.0.11","data":{"app":"core"}}
```
The _really_ annoying thing is that I do not get a chance to login at all since the login/password request does not show up - only the site logo and the footer on an otherwise empty page.

**Comment by ChristophWurst** [comment]
@Yetangitu check if your observations match with https://github.com/nextcloud/server/issues/37492 or file a new ticket please.

**Comment by Yetangitu** [comment]
Apart from the list of enabled/disabled apps that description seems to match, as does this one.

**Comment by fuomag9** [comment]
This has started happening again for me

**Comment by dafi87** [comment]
Still happening with NC27 as described here: https://github.com/nextcloud/server/issues/37492

**Comment by terba** [comment]
I have something like this also in 27.1.3. It started some months ago. I don't leave any tabs open ever, but when I fire up the browser (with only one empty tab) and request https://mynextcloud/apps/news, about twice a day messages start to appear on the upper right corner (I don't remember the text, but something like I'm not logged in) and I have to login again. But if I'm fast enough to close this tab, I can reopen the same url and I'm in. If I let it go, i will be logged out. Then I have to login twice to get to the TOTP dialog. I have the same in the logs when this occures (see below). Please solve this, as it is very annoying, as I have to find my phone for the TOTP on daily basis just to read the news.
```
"method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Tried to log in but could not verify token"
"method":"GET","url":"/apps/theming/theme/dark.css?plain=0&v=0c44906c","message":"Tried to log in but could not verify token"
"method":"GET","url":"/apps/theming/theme/default.css?plain=1&v=0c44906c","message":"Tried to log in but could not verify token"
"method":"GET","url":"/apps/theming/theme/light.css?plain=0&v=0c44906c","message":"Tried to log in but could not verify token"
"method":"GET","url":"/apps/theming/theme/light.css?plain=1&v=0c44906c","message":"Tried to log in but could not verify token"
"method":"GET","url":"/apps/theming/theme/dark-highcontrast.css?plain=0&v=0c44906c","message":"Tried to log in but could not verify token"
"method":"GET","url":"/apps/theming/theme/opendyslexic.css?plain=0&v=0c44906c","message":"Tried to log in but could not verify token"
"method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Tried to log in but could not verify token"
```
By the way is it ok require login for css data? Thanks in advance.
