### ISSUE TITLE
[Bug]: Server reported no ETag on CIFS share mounted over external storage function

### ISSUE THREAD

**Issue by ASokolovics** [nextcloud/server#34176]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

I have an issue with external storage mounted over SMB, the host ist Microfocus Open Enterprise Server 2018 SP3 with CIFS enabled, over said CIFS interface we are accessing underlying NSS Volumes and everything is working just fine when you access the shares using web interface of Nextcloud, problems start when we use Nextcloud client and try to sync shared volumes.

At some point Nextcloud client stops syncing and says “Server reported no ETag” at the same time I can find following error in Nextcloud log:

App: webdav
Message: Sabre\DAV\Exception\ServiceUnavailable: Storage with mount id 7 is not available

It says that storage is not accessible, but using Web Interface of Nextcloud I can browse whole share, see all files, open and edit them, so the issue seems to be only on webdav part of nextcloud which is used for the client. By the way, the log is kind of flooded with said error, as we have multiple shares its not always number 7, but it is the same error regarding same CIFS host server.

I hoped that it is some kind of cosmetic error message, but no, after client throws this error, it stops syncing and if you browse to the shares using explorer, you dont see all the subfolders of the share, only a part of it, but at the same time if you browse to this folders using web interface of nextcloud - everything ist there and can be accessed and modified without any issues. So Im kind of clueless right now, it is working fine on the web, but has massive issues on the client.

Best Regards,
Aleks

### Steps to reproduce

1. Mount large external CIFS Storage, aprox. 300GB.  (SMB Emulation on Linux)
2. Install Nextcloud Client.
3. Start to synchronize the share.
4. Wait till client starts reporting "Server reported no ETag".

### Expected behavior

Nextcloud client should synchronize the share without throwing "Server reported no ETag" error. Also after client reports this error, synchronisations stops and if you browse to the folders using explorer, there are folders that are missing, if you open same path using Web Interface and not Client, all folders and files in there are visible and can be accessed and modified.

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.rs-radolfzell.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.5.1",
        "overwrite.cli.url": "https:\/\/nextcloud.rs-radolfzell.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "https",
        "logtimezone": "Europe\/Berlin",
        "maintenance_window_start": 1,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": "",
        "templatedirectory": "",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - richdocumentscode: 22.5.502
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 78:OCA\DAV\Connector\Sabre\Directory->getChild()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 73:Sabre\DAV\Tree->getNodeForPath()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 73:Sabre\DAV\Tree->getNodeForPath()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 73:Sabre\DAV\Tree->getNodeForPath()
/var/www/nextcloud/apps/dav/lib/DAV/ViewOnlyPlugin.php - line 74:Sabre\DAV\Tree->getNodeForPath()
/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:OCA\DAV\DAV\ViewOnlyPlugin->checkViewOnly()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:Sabre\DAV\Server->emit()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:Sabre\DAV\Server->invokeMethod()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:Sabre\DAV\Server->start()
/var/www/nextcloud/apps/dav/lib/Server.php - line 358:Sabre\DAV\Server->exec()
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 166:require_once(“/var/www/ne … p”)
```

### Additional info

CIFS Share is hosted by Microfocus Open Enterprise Server 2018 SP3. (Based on SLES 12 SP5)

Nextcloud version: 24.0.5
Operating system and version: Debian 11.3
nginx version: 1.22.0
PHP version: 8.1.9
Nextcloud Client: Newest version, tested on Windows an Mac

**Comment by ASokolovics** [comment]
Any Ideas what is wrong here ?

**Comment by Gamechiefx** [comment]
I am having the same prblem. I would like to know why this isn't working.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by szaimen** [comment]
> I had a similar error after upgrading PHP from 7.4 to 8.1. The problem was a missing PHP module (smbclient). After installing it and restarting apache, it worked fine again.

**Comment by Adambean** [comment]
> > I had a similar error after upgrading PHP from 7.4 to 8.1. The problem was a missing PHP module (smbclient). After installing it and restarting apache, it worked fine again.

Unfortunately not. `php8.1-smbclient` is installed and enabled, but that hasn't resolved this.

**Comment by mrtumnus** [comment]
Same problem here.  I have several external SMB/CIFS shares 'grafted' into my Nextcloud service, and frequently encounter this issue in the Nextcloud sync client (on Windows 10).  I think it usually self-heals eventually, but it's quite frustrating when it happens because I get frequent notification pop-ups with the error messages, as well as possible unavailability of files/folders.

I am using php8.2 and have the smbclient plugin installed.

**Comment by IAMBUDE** [comment]
Interesting note here. 

I have the same issue with 3 external storages which are attached to our nextcloud installation.
When the ETAG issue appears, it can temporarily be fixed by simply opening an external storage in the web interface, waiting for it to load correctly and then allowing the client to sync again.

**Comment by mrtumnus** [comment]
> it can temporarily be fixed by simply opening an external storage in the web interface, waiting for it to load correctly and then allowing the client to sync again.

I've noticed the same thing - thanks for mentioning it.

**Comment by Danielson89** [comment]
I had resolved this issue by reinstalling smbclient.   Been working well since.

**Comment by Lewis8265** [comment]
Not sure why this was closed, as it certainly isn't fixed? I'm facing this right now including that when opening the external storage page of the admin settings that it all starts working again

**Comment by xTGHHx** [comment]
Yes, true. Opening the admin section with shares and error disappears!
