### ISSUE TITLE
[Bug]: NC 25 - Share menu not fully visible when it opens upwards

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#35938]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the browser window is smaller or when you use the mobile view the sharing menu may open upwards. However in this case it is only visible partially and the side area can not be scrolled either - so it becomes mostly useless.

![image](https://user-images.githubusercontent.com/6613614/210219170-75fb26e8-080a-44de-b9ee-a38645e4880a.png)

### Steps to reproduce

1. Open Nextcloud in the browser.
2. Make the browser window smaller vertically.
3. Open the sharing options of a file or folder.
4. Share the file or folder as link.
5. Click on the "..." menu next to the sharing symbol to open the sharing menu, so that it will open upwards (make sure the browser is small enough so the menu opens upwards and not downwards as usual).

### Expected behavior

The side area should be scrollable if needed. Also see #34777 which is a similar problem: since the sharing options can not be scrolled, they become unusable in smaller views.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0
        },
        "knowledgebaseenabled": false,
        "theme": "",
        "simpleSignUpLink.shown": false,
        "loglevel": 2,
        "log_authfailip": true,
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 30",
        "app_install_overwrite": [
            "apporder",
            "deck",
            "keeweb",
            "appointments",
            "drawio",
            "bookmarks",
            "spreed",
            "unroundedcorners",
            "fulltextsearch",
            "fulltextsearch_elasticsearch",
            "files_fulltextsearch",
            "files_fulltextsearch_tesseract",
            "passwords",
            "gpxpod"
        ],
        "has_rebuilt_cache": true,
        "default_language": "de",
        "default_phone_region": "DE",
        "check_data_directory_permissions": false,
        "log_rotate_size": 52428800,
        "profile.enabled": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bookmarks: 12.0.0
  - calendar: 4.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.2
  - dicomviewer: 1.2.4
  - drawio: 1.0.5
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_fulltextsearch: 25.0.0
  - files_fulltextsearch_tesseract: 25.0.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.3
  - fulltextsearch: 25.0.0
  - fulltextsearch_elasticsearch: 25.0.0
  - gpxpod: 5.0.4
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.2.0
  - contacts_avatar_patch: 1.0.0
  - encryption: 2.13.0
  - files_external: 1.15.0
  - onlyoffice: 7.6.8
  - quota_warning: 1.15.0
  - recommendations: 0.4.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - user_status: 1.5.0
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
(not relevant)
```

### Additional info

(not relevant)

**Comment by szaimen** [comment]
Hi, this is already be resolved in nextcloud vue 7.1.0. However all installed apps need to use that version otherwise it will get overwritten. So this would need to get reported to apps that are still using vue 7.0.0 to below 7.1.0.

**Comment by arnowelzel** [comment]
Is there any overview which of the core apps are already migrated to Vue 7.1.0 or when an update is planned? The reported issue happens in the files app provided with Nextcloud 25.0.2.

**Comment by szaimen** [comment]
Currently afaics are at least these apps not updated yet:
recognize, guests, groupfolders, deck and photos

@nextcloud/office can you take care of recognize and deck? 
I'll check guests, groupfolders and photos.

**Comment by juliushaertl** [comment]
- [ ] https://github.com/nextcloud/recognize/pull/589
- [ ] https://github.com/nextcloud/deck/pull/4353

**Comment by szaimen** [comment]
- [ ] guests https://github.com/nextcloud/guests/pull/974

**Comment by szaimen** [comment]
> So the "Files" app in Nextcloud is already updated and the issue will be fixed with the next Nextcloud update (25.0.3 or later)?

The files app is fixed since 25.0.2. However it depends on the other apps that you have installed.

**Comment by arnowelzel** [comment]
> > So the "Files" app in Nextcloud is already updated and the issue will be fixed with the next Nextcloud update (25.0.3 or later)?
> 
> The files app is fixed since 25.0.2. However it depends on the other apps that you have installed.

I'm a bit confused here - why does the behaviour of the "Files" app it depend on other apps? Does this mean if any app uses an older version of Vue only that version will be used globally?

**Comment by szaimen** [comment]
> Does this mean if any app uses an older version of Vue only that version will be used globally?

This is the case unfortuntely regarding the popver that you see there, yes.

**Comment by juliushaertl** [comment]
Actually the files sharing app should ship its own version of vue and not be affected by other apps unless I miss something, so maybe it is not fully fixed yet?

**Comment by szaimen** [comment]
> Actually the files sharing app should ship its own version of vue and not be affected by other apps unless I miss something, so maybe it is not fully fixed yet?

The css is indeed not scoped. See https://github.com/nextcloud/nextcloud-vue/blob/dd1d7630694e6fb16f3a94a6b07d108418156b1d/src/components/NcActions/NcActions.vue#L1178-L1184

**Comment by szaimen** [comment]
However not sure if that is even possible since it overwrites the height of another js lib...

**Comment by juliushaertl** [comment]
Ah right, we cannot scope that since the element is added to the body rather than the component itself.
