### ISSUE TITLE
[Bug]: Unable to scroll in nextcloud

### ISSUE THREAD

**Issue by PhilippHandle** [nextcloud/server#36086]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

since the update to nextcloud v25.x i'm unable to scroll.

setting the css #content { height: 100% } fixes the issue

### Steps to reproduce

1. update to nextcloud 25.x
2. unable to scroll

### Expected behavior

updated the docker image to nextcloud 25.0.2 and i'm unable to scroll

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.phandle.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.phandle.net",
        "overwritehost": "cloud.phandle.net",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_sendmailmode": "smtp",
        "default_phone_region": "de",
        "mysql.utf8mb4": true,
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "app_install_overwrite": [
            "breezedark"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - calendar: 4.2.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.15.0
  - bruteforcesettings
  - circles: 25.0.0
  - contactsinteraction: 1.6.0
  - encryption
  - federation: 1.15.0
  - files_external: 1.17.0
  - files_rightclick: 1.4.0
  - firstrunwizard: 2.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.0.0
  - twofactor_totp
  - updatenotification: 1.15.0
  - user_ldap
  - user_status: 1.5.0
  - weather_status: 1.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Hi, can you try to clear your browser cache and check it that makes it work? Also can you try in a different browser?

**Comment by szaimen** [comment]
Strange. I am asking because I cannot reproduce the issue.

**Comment by PhilippHandle** [comment]
another weird thing if i change the window size it works.
![image](https://user-images.githubusercontent.com/7166546/212046962-af927e0e-8b14-467d-b9ef-fb96d32a7043.png)
![image](https://user-images.githubusercontent.com/7166546/212047004-5176887b-d383-475b-a5b9-7bbf1bc33d90.png)

would it help if i create you an account to test?

**Comment by szaimen** [comment]
Please try again witb 25.0.3 which should be out soon.

**Comment by PhilippHandle** [comment]
ok will try, if i change the line `--body-height: calc(100% - env(safe-area-inset-bottom) - 50px - var(--body-container-margin));` to `--body-height: calc(100% - env(safe-area-inset-bottom) - 50px);` it works too
![image](https://user-images.githubusercontent.com/7166546/212050146-84cfc181-0a06-4048-85dc-b7092801cff8.png)

**Comment by PhilippHandle** [comment]
updated to v25.0.3 and the issue still exists. cleared browser and cloudflare cache. tested in chrome and firefox

**Comment by PhilippHandle** [comment]
ok i fetched a fresh nextcloud image and the version says nextcloud hub 3 (25.0.3) and mine cloud 25.0.3 whats the difference? i should be the same image
![image](https://user-images.githubusercontent.com/7166546/213214326-2aebf51f-145a-4b75-8a99-98e6b3aa080b.png)
![image](https://user-images.githubusercontent.com/7166546/213214378-0120daad-b5de-4316-948b-b5ee13df5f18.png)

**Comment by szaimen** [comment]
This could be caused by one of your installed apps. You could try to disable all non-default appa, clear the browser cache and check if that makes things works again.

**Comment by teambvd** [comment]
I have the same issue - seems like it might be related to the move from php 8.0 to 8.1, though still digging around in it

**Comment by IBBoard** [comment]
I think I'm getting this on a CentOS 8 server with PHP 7.4.

I've disabled everything in "Apps" and I can't scroll anywhere in the site (e.g. the Apps list)

Went to "Manage Data" in Firefox and removed all data for the domain, but no change.

[Nextcloud Hub 3](https://nextcloud.com/) (25.0.5) using Firefox 112.

**Comment by teambvd** [comment]
I was able to find the cause for mine - the upgrade had somehow killed my theming items (icons and background). After re-uploading them, the issue was corrected.

**Comment by p-handle** [comment]
@teambvd which folders do i need to upload?

**Comment by IBBoard** [comment]
I've got an override on the background colour, but no images (not even a logo).

If I go to Administration Settings > Theming and reset the background colour and login image then nothing changes.

If I go to Personal > Appearance and Accessibility and reset it to "Default Image" (after zooming out far enough to see that far down) then I get a blue background but I still don't get any scrolling.

What theming changes triggered the change?

**Comment by PhilippHandle** [comment]
So watchtower updated the docker image on 31th of mai and today i did the update/migration in the ui and know the scrolling works. I don't know what fixed the issue!
Currently running Cloud 26.0.2.

**Comment by IBBoard** [comment]
I've _finally_ managed to upgrade to v26 and v27 (I hadn't realised that they dropped support for PHP 7.4, which I was running on a CentOS 8 box). But I've _still_ not got scrolling.

Content in the News app also continues to be as wide as it wants to be (possibly related to the title/description length). I don't know if the two are related.

**Comment by skjnldsv** [comment]
Well, some app might be conflicting.
i would suggest to:
1. disable all non-official Nextcloud apps
2. see if scrolling works
3. if it does, enable them back one by one until it break again and you know which app is the culprit!

**Comment by IBBoard** [comment]
> Well, some app might be conflicting. i would suggest to:
> 
>     1. disable all non-official Nextcloud apps

Is there a specific designation for "official" apps? Is it anything under the NextCloud GitHub account?

I'm using:

* Bookmarks - 13.0.1
* Activity - 2.19.0
* Auditing / Logging - 1.17.0
* Brute-force settings - 2.7.0
* Calendar - 4.4.4
* Contacts - 5.3.2
* Deleted files - 1.17.0
* Log Reader - 2.12.0
* News - 23.0.0
* Nextcloud announcements - 1.16.0
* Notes - 4.8.1
* Notifications - 2.15.0
* Right click - 1.6.0
* Tasks - 0.15.0
* Update notification - 1.17.0
* Versions - 1.20.0

I don't remember enabling some of them (Right-click, Log Reader, etc).

They're all "Featured", so I'd expect good support and compatibility. Every single one appears to link to a NextCloud GitHub account.

**Comment by skjnldsv** [comment]
> Is there a specific designation for "official" apps? Is it anything under the NextCloud GitHub account?

Yes :)
![image](https://github.com/nextcloud/server/assets/14975046/d33b4a1a-5bba-45a4-9494-9bf2b4e00907)

**Comment by IBBoard** [comment]
Just disabled every single app. Ctrl+F5 refreshed the page. Still can't scroll the list of apps.

Can someone with working scroll tell me which level of element on `/settings/apps` is the one that scrolls and which is the first element to be locked to window size.

**Comment by terrificobjects** [comment]
I am also struggling with this. Everything is up to date. No matter what I do on the backend, nothing is scrolling.

**Comment by IBBoard** [comment]
@terrificobjects - the Custom CSS app with the CSS above is still working for me (on a desktop browser)

**Comment by skyminds** [comment]
Hi - I'm also having the same issue. My Nextcloud instance has been upgraded over the years and is now running v27.1.5 (stable), scrolling seems disabled. It looks theme-related but switching to another theme (dark/light) does not solve the issue.

**Comment by rmfalco89** [comment]
for what it's worth, my fresh installation (docker image) has the same problem from Safari on macos, but not from chrome.

**Comment by pm112** [comment]
Experiencing the Problem on the Apps Page on Safari/Firefox on Mac OS in Win VM it works.

**Comment by fate8383** [comment]
the same problem, does not scroll down or up on safari...

**Comment by Jefferson-tan** [comment]
Broken for me as well, the workaround provided by IBBoard works.
> ```
> #content {
>     width: 100%
> }
> :root {
>     --body-height: calc(100% - env(safe-area-inset-bottom) - 50px);
> }
> ```

**Comment by susnux** [comment]
Cannot reproduce this with Nextcloud 32+
