### ISSUE TITLE
[Bug]: Default Nextcloud Icon appears when file sharing  via link (embeds) see attached picture

### ISSUE THREAD

**Issue by MRFU510N88** [nextcloud/server#36802]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Screenshot 2023-02-21 212746 (2)](https://user-images.githubusercontent.com/35142900/220463290-d376201d-7d64-4685-8b8b-2c229e23cd46.png)

As above appears in all embeds whether sharing by discord, Whatsapp, Messenger, Facebook, Chrome and so on.

To confirm on the theming page all icons and logos have been set to my custom png image with a size of 32x32 and 256x256. In all other ways the logos/favicon appears as it should, but seems to have dissappeared with embeds since the latest NC edition 25.0.3.

### Steps to reproduce

1. share a file via link.
2. logo appears when sent.
3.

### Expected behavior

custom favicon/logo should appear.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.5.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - drawio: 2.1.0
  - encryption: 2.13.0
  - external: 5.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.1
  - impersonate: 1.11.0
  - integration_github: 1.0.15
  - integration_google: 1.0.9
  - integration_whiteboard: 0.0.14
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.4
  - money: 0.15.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - recommendations: 1.4.0
  - registration: 2.1.0
  - related_resources: 1.0.3
  - richdocuments: 7.1.1
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.6.0
  - snowflakestheme: 1.0.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - terms_of_service: 2.1.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - unsplash: 2.2.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.8
  - workflowengine: 2.7.0
Disabled:
  - analytics: 4.7.2
  - audioplayer: 3.3.1
  - breezedark: 25.0.0
  - carnet: 0.24.6
  - electronicsignatures: 2.0.3
  - end_to_end_encryption: 1.11.1
  - extract: 1.3.5
  - files_antivirus: 4.0.2
  - flow_notifications: 1.5.0
  - forms: 3.1.0
  - health: 1.6.1
  - jsloader: 1.5.0
  - phonetrack: 0.7.4
  - quicknotes: 0.8.5
  - radio: 1.0.3
  - socialsharing_email: 2.5.0
  - suspicious_login: 4.2.1
  - talk_matterbridge: 1.25.2
  - user_ldap
  - video_converter: 1.0.5
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Should be fixed with 25.0.4

**Comment by MRFU510N88** [comment]
> Should be fixed with 25.0.4

Do you know when 25.0.4 is going to stable branch?

**Comment by szaimen** [comment]
The release is plannefd for this thursday

**Comment by MRFU510N88** [comment]
> The release is plannefd for this thursday

Thanks for getting back to me, If you look at the icon, there is a faint black line round the outer edge in some parts. This has also been a thing im assuming because the background isnt correctly sized was this reworked/commented on?

**Comment by MRFU510N88** [comment]
> The release is plannefd for this thursday

I have just updated to nextcloud 25.0.4 the problem persists, no change.

**Comment by Sk4hnt42** [comment]
I can confirm that this **issue persists** after Upgrading to 25.0.4.

**Comment by jonathanwerle** [comment]
Same problem here with Nextcloud 26.0.1
