### ISSUE TITLE
[Bug]: Show grid toggle is not fixed and causes style break

### ISSUE THREAD

**Issue by HannesJo0139** [nextcloud/server#37022]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

NC version 25.0.4. Fresh setup (linuxserver.io docker container) shows the following behavior. When I scroll down in files list, the button to activate grid view  moves out of screen and where it was there is kind of a hole now so you can see part of file list details where it should be barely visible.. See screenshot right under the rounded light corner in the upper right.
I'm using MacOs if that is important info.

<img width="1267" alt="Bildschirm­foto 2023-03-02 um 23 14 58" src="https://user-images.githubusercontent.com/42114183/222586242-6b88284e-c0ca-4eb0-bac4-52dab4ad82c3.png">

### Steps to reproduce

1.
2.
3.

### Expected behavior

..

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
default apps
```

**Comment by HannesJo0139** [comment]
Additional info: It happens on MacOs only. Using Windows the button pos is fixed and everything is fine.

**Comment by arnowelzel** [comment]
I can confirm that this happens in Windows as well.

My fix with [CustomCSS](https://apps.nextcloud.com/apps/theming_customcss):

```
#view-toggle {
  position: fixed;
}
```

**Comment by HannesJo0139** [comment]
Ok that is really weird. On my Windows 11 Google Chrome the btn is fixed even after deleting browser data..

**Comment by arnowelzel** [comment]
> Ok that is really weird. On my Windows 11 Google Chrome the btn is fixed even after deleting browser data..

Are you sure that you cleared the cache? If Chrome seems to work, try Edge or another browser which never has seen Nextcloud ever before. I can reproduce this at any time - disable the CSS fix, clear cache and the toggle button moves up again when scrolling since its position is clearly not fixed.

**Comment by HannesJo0139** [comment]
Hmm, somehow deleting all browser data seems to not delete all browser data lol. You are right. Edge, Firefox, Chrome - It is broken everywhere :)

**Comment by solracsf** [comment]
This has been fixed by https://github.com/nextcloud/server/pull/37895
Report back if not (published on next version)
