### ISSUE TITLE
[Bug]: `Overwrite` header is missing, leading to deleted file

### ISSUE THREAD

**Issue by Altahrim** [nextcloud/server#40906]
### Bug description

When using a case-insensitive file-system, renaming a file `test` to `Test` delete both files.

When renaming a file, the behaviour is the following:
 - check if source exists,
 - check if destination exists,
   - if yes, the destination file is deleted unless header `Overwrite: F` was provided. In later case, the call fail,
   - if no, continue
 - move file
In version `27`, the file isn't deleted because the header `Overwrite: F` is sent
The header should be restored in `master`.

### Steps to reproduce

1. use case-insensitive file-system like APFS, NTFS on Windows or ext4 with casefold option
2. create a file or a directory named `test`
3. rename it to `Test`
4. refresh
5. Both files `test` and `Test` are deleted (same on file-system)

### Expected behavior

`test` should be renamed to `Test` and not deleted.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
@Altahrim should this not be handled in the backend?
Sounds like we should check that source and origin are not the same files (by id) before deleting. I guess this is not handled by default by Sabre, but should be possible with a sabre files plugin?

**Comment by Altahrim** [comment]
It changes a bit on case insensitive FS.
If you have a file `test` it is in DB with name `test`. When trying to rename it to `TEST`, it seems to exists in FS (case-insensitive) but not in DB (case-sensitive). So we don't have an ID for both.
The issue with changed case on case-insensitive FS should be partially fixed now.

My concern is about the destructive action by default.
If no header is sent, we consider we should destroy a file or a directory is case of conflict. I would prefer an explicit ask for overwrite. So I though it will be safer to stick with behaviour from 27 and before.

It could be changed at backend level too but it's the default behaviour in Sabre: https://github.com/nextcloud/3rdparty/blob/e6c45c6c0d4f92ffec621446fcc3b34584772b13/sabre/dav/lib/DAV/Server.php#L728-L736

**Comment by susnux** [comment]
Ah yes makes sense we only have `test` in database but for FS `TEST` is the same.
I was thinking we have like the inode number which is the same for both files and thus it should not override.

Maybe this could be a check on the files plugin of sabre? To check `fileinode(source) === fileinode(dest)` and fail if true?

> My concern is about the destructive action by default.

I agree users should be asked before overriding. There should be a warning on the frontend and if confirmed a second request without the header is send.

**Comment by justinladwig** [comment]
The problem still seems to exist in version 28.0.4 if you change the upper and lower case of a file or folder name via the Windows client. As described, the original file or folder with all files is removed in the file system.
