### ISSUE TITLE
[Bug]: The counting language is corrupted

### ISSUE THREAD

**Issue by nhanlx89** [nextcloud/server#42674]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Untitled](https://github.com/nextcloud/server/assets/90684647/c6822b4c-3d02-4524-9816-54872837784b)
There is a problem with the Vietnamese language error as shown in the picture I sent
For English, it appears 1 folder and 2 files. but for Vietnamese, it does "{đếm} tệp và {đếm} thư mục"
/

### Steps to reproduce

1.Login to the website
2.And see the error
3.Notify the manufacturer

### Expected behavior

I need it to work properly and not have language errors anymore

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.angiang.dcs.vn"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "http:\/\/files.angiang.dcs.vn",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "vi",
        "force_language": "vi",
        "default_locale": "vi_VN",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "default_phone_region": "VN",
        "theme": "",
        "loglevel": 2,
        "skeletondirectory": "",
        "htaccess.RewriteBase": "\/",
        "app_install_overwrite": [
            "files_markdown",
            "ldapcontacts"
        ],
        "maintenance": false,
        "updater.release.channel": "stable",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - ldapcontacts: 2.0.5
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - snappymail: 2.32.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 27.0.1)
  - dashboard: 7.8.0 (installed 7.7.0)
  - encryption: 2.16.0
  - files_external: 1.20.0 (installed 1.19.0)
  - files_reminders: 1.1.0 (installed 1.0.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.16.0)
  - support: 1.11.0 (installed 1.10.0)
  - survey_client: 1.16.0 (installed 1.15.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - weather_status: 1.8.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/templates/layout.guest.php
- files
	- INVALID_HASH
		- img/app.svg
- activity
	- INVALID_HASH
		- img/activity.svg
- photos
	- INVALID_HASH
		- img/app.svg
- ldapcontacts
	- INVALID_HASH
		- img/app.svg

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/templates/layout.guest.php] => Array
                        (
                            [expected] => 9ddacc8c83bd550db899dd98b5ab7b04116b4183c023a5a9d4c640602ffd115b09882b3cd939d2384c6fa19db2a35f33c1515c94fd9a04646d0ebaf4cded3751
                            [current] => 9841d3b4babae2836e8f4c2fb096fda8a538a0b547db2144a18c624af70961aa970ec0412f58023628afd5eafe6545e82402aecc00320147a654491c0b481a84
                        )

                )

        )

    [files] => Array
        (
            [INVALID_HASH] => Array
                (
                    [img/app.svg] => Array
                        (
                            [expected] => fd38168a066c0d3042c9424e1938b366f46785046b997fe5d326f5f2915727b8d5de031a1058da03de98743f9318b8657c351388837e9bce38e588103666421f
                            [current] => c51dca6d82d3907ee7852b2113437dd3247d6f29cb14305a47dd7e0674111cc31daa2d311f3bad7e45ed681b2728ab897e8ee994cbea296eadac4436c8f1df23
                        )

                )

        )

    [activity] => Array
        (
            [INVALID_HASH] => Array
                (
                    [img/activity.svg] => Array
                        (
                            [expected] => 38d74c9d11ebdc6692623401119631969b2db6461b4d56928ebcccf4c867d8b53d8e3b589bd1856872c2cb65dce7b877adf8b6c53565aa0a5061cd9921a025e5
                            [current] => d3b3b0b059a4e2bcd1c23ea60ea6183f0e19740b6a3389cd407a2396fbe6b5229a09a4571f7101a0d1cd527550e43621337d4f9341e498768502fe2c9ea67bfd
                        )

                )

        )

    [photos] => Array
        (
            [INVALID_HASH] => Array
                (
                    [img/app.svg] => Array
                        (
                            [expected] => 6b1e6cdccd2ec9775b8183db1acabe1739a467b13a4c1556c1fa16faf170ad3bf767928197d7b22d75aaaaa533389cc0bf98e43b0c8975a65c017170709166a9
                            [current] => bc329a0eef34ab324e5af216005c3f194c1c7b8174581ff5df6cb12839149ea714a15dd99c1782175584cc3d32b8c829bd8b4969e7b3a4e2b96bafe4d7360ba1
                        )

                )

        )

    [ldapcontacts] => Array
        (
            [INVALID_HASH] => Array
                (
                    [img/app.svg] => Array
                        (
                            [expected] => b1747ed1a5e2bc6826752f2ace142a4ba26dad457b6ea494731651d60823525950716e83d09f8d71795cf4736fd95fc7acfc87525b481a2dc7cd218c08461f32
                            [current] => 8ceeb3f8a3eba7dd9baeed5bd67aafad7e13f6f9a74c1b04f793445ca5a8e308e789d0a091a9e56035e844f7f940f9e46aa7b3c4acd132039155df788a0a0195
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
{"reqId":"AxBtZW0U7c5z1wUDMmEs","level":3,"time":"2024-01-08T00:32:06+00:00","remoteAddr":"172.16.9.254","user":"admin","app":"index","method":"GET","url":"/index.php/apps/files/?dir=/&fileid=263977","message":"Call to a member function getPath() on null in file '/var/www/html/vptu/apps/files/lib/Controller/ViewController.php' line 240","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.1.1","exception":{"Exception":"Exception","Message":"Call to a member function getPath() on null in file '/var/www/html/vptu/apps/files/lib/Controller/ViewController.php' line 240","Code":0,"Trace":[{"file":"/var/www/html/vptu/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/vptu/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/vptu/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/vptu/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/vptu/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Call to a member function getPath() on null","Code":0,"Trace":[{"file":"/var/www/html/vptu/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/html/vptu/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/vptu/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/vptu/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/vptu/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/vptu/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/vptu/apps/files/lib/Controller/ViewController.php","Line":240},"message":"Call to a member function getPath() on null in file '/var/www/html/vptu/apps/files/lib/Controller/ViewController.php' line 240","exception":[],"CustomMessage":"Call to a member function getPath() on null in file '/var/www/html/vptu/apps/files/lib/Controller/ViewController.php' line 240"},"id":"659e5eea0725a"}
```

### Additional info

NO

**Comment by solracsf** [comment]
This must be fixed at Transifex.
https://app.transifex.com/nextcloud

Feel free to fix it.

**Comment by nhanlx89** [comment]
> This must be fixed at Transifex. https://app.transifex.com/nextcloud
> 
> Feel free to fix it.

How can I test it?

**Comment by skjnldsv** [comment]
@nhanlx89 you can't test it, you need to fix it on transifex and then the bot will automatically sync it with this repo and it will be available on the upcoming release

**Comment by nhanlx89** [comment]
> I fixed some, but please have a deeper look. I also pinged the translators to be careful

Oke tks you bro

**Comment by toreonify** [comment]
Pull request #42734 was backported to 28.0.2 (milestone set to 28.0.2), but I'm still having the exact same issue.

Another post of the same bug is on the forum:
https://help.nextcloud.com/t/problems-with-russian-translation-after-upgrade-to-28-0-2/180631

![Screenshot_20240206_153900](https://github.com/nextcloud/server/assets/10438627/be903ffc-7841-4649-8df8-21f3aab36c2a)

P.S. button for creating new files is also not translated, like in original bug description
