### ISSUE TITLE
[Bug]: v28 - Your webserver does not serve `.mjs` files using the JavaScript MIME type...

### ISSUE THREAD

**Issue by rchaconmolero** [nextcloud/server#42989]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrade from 28.0.1 to 28.0.2 RC1 appears in security and setup warning page: 
There are some errors regarding your setup.
Your webserver does not serve `.mjs` files using the JavaScript MIME type. This will break some apps by preventing browsers from executing the JavaScript files. You should configure your webserver to serve `.mjs` files with either the `text/javascript` or `application/javascript` MIME type.

### Steps to reproduce

1. Upgrade vie Web GUI.
2. No error in upgrade process.
3. There are some errors regarding your setup.
Your webserver does not serve `.mjs` files using the JavaScript MIME type. This will break some apps by preventing browsers from executing the JavaScript files. You should configure your webserver to serve `.mjs` files with either the `text/javascript` or `application/javascript` MIME type.

### Expected behavior

No messages about "Your webserver does not serve `.mjs` files using the JavaScript MIME type."

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
# sudo -u www-data php /var/www/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "next01d.canal-sur.interno"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.0",
        "overwrite.cli.url": "https:\/\/next01d.canal-sur.interno\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "default_phone_region": "ES",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpstreamoptions": {
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "beta",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "twofactor_admin"
        ],
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "Europe\/Madrid",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile_audit": "\/var\/log\/nextcloud\/nextcloud.log",
        "trashbin_retention_obligation": "auto, 7",
        "versions_retention_obligation": "auto, 7",
        "allow_user_to_change_display_name": false,
        "activity_expire_days": 1,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 30,
        "session_lifetime": 86400,
        "remember_login_cookie_lifetime": "0",
        "session_keepalive": "false",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 17
    }
}
```

### List of activated Apps

```shell
# sudo -u www-data php /var/www/nextcloud/occ app:list
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_automatedtagging: 1.18.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - groupfolders: 16.0.3
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0
  - files_retention: 1.16.0 (installed 1.16.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.16.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2 (installed 8.0.0-alpha.0)
  - weather_status: 1.8.0 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by joshtrichards** [comment]
Are you saying you know with certainty the test should pass in your environment?

Can you confirm things that require `mjs` are fully functioning: 
- Does the Activity page function?
- Does *Administration settings->Logging* show current log entries?

**Comment by rchaconmolero** [comment]
Yes. Activity and logging show current logs entries.

![log](https://github.com/nextcloud/server/assets/44724925/d4bfcf19-14cc-4ad6-a8ea-0036bf4a2078)
![Activity](https://github.com/nextcloud/server/assets/44724925/7ef24a25-e966-4c88-aae9-2d39ac189120)

**Comment by solracsf** [comment]
What is the output of:

`curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs`

**Comment by susnux** [comment]
@rchaconmolero  this would be interessting because what that test does is testing to access your instance and check the returned mime type. Meaning if your server can not resolve its own host name it will fail here.

> What is the output of:
> 
> `curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs`

**Comment by joshtrichards** [comment]
> Meaning if your server can not resolve its own host name it will fail here.

Specifically*: At least one of Nextcloud's configured `trusted_domains` must be accessible (via its URL) from the Nextcloud app server itself.

*Or at least that's my take from my first read though of this recently added code

**Comment by rchaconmolero** [comment]
The response to "https://next01d.canal-sur.interno/apps/settings/js/esm-test.mjs"    
is:

/**
 * This is a dummy file for testing webserver support of JavaScript modules.
 */

export default 'Hello'

**Comment by solracsf** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/42994 in 28.0.2 (not RC).

**Comment by pandusen** [comment]
I can confirm the same issue, after update: 28.0.1 to 28.0.2 RC1

My output from curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs:

HTTP/1.1 200 OK
Date: Sun, 21 Jan 2024 11:11:18 GMT
Server: Apache/2.4.57 (AlmaLinux) OpenSSL/3.0.7
Strict-Transport-Security: max-age=63072000
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1; mode=block
Upgrade: h2
Connection: Upgrade
Last-Modified: Sun, 21 Jan 2024 07:11:10 GMT
ETag: "6d-60f6f6af88f68"
Accept-Ranges: bytes
Content-Length: 109
Cache-Control: max-age=15778463
Content-Type: text/javascript

**Comment by solracsf** [comment]
For those with the problem, can you please:

> Also it would be really helpful if you could **set the logging level to debug** and send the logfile here, or at least, search the log for an entry like the following and send that complete entry if it exists:
>
>`Can not connect to local server for checking JavaScript modules support`

**Comment by pandusen** [comment]
I am simultaneously also have the "Could not load log entries" error.
Currently investigating.

**Comment by solracsf** [comment]
@pandusen can you post the full RAW stack trace from the log reader app?

![image](https://github.com/nextcloud/server/assets/12234510/831640d3-dedd-49db-8449-d965ee52fbe3)

**Comment by pandusen** [comment]
Sure
_(I have replaced fqdn and username.)_

**Could not detect any host:**
`{"reqId":"Za0hieI4tzKF-QVLu1D6wwAA1iE","level":0,"time":"2024-01-21T13:52:11+00:00","remoteAddr":"192.168.0.30","user":"user","app":"settings","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Can not connect to local server for checking JavaScript modules support","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.2.0","exception":{"Exception":"OCP\\Http\\Client\\LocalServerException","Message":"Could not detect any host","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/Http/Client/Client.php","line":260,"function":"preventLocalAddress","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/html/nextcloud/apps/settings/lib/SetupChecks/JavaScriptModules.php","line":67,"function":"head","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":49,"function":"run","class":"OCA\\Settings\\SetupChecks\\JavaScriptModules","type":"->"},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":303,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Http/Client/Client.php","Line":192,"message":"Can not connect to local server for checking JavaScript modules support","exception":[],"url":"cloud.nextcloud.tld/apps/settings/js/esm-test.mjs","CustomMessage":"Can not connect to local server for checking JavaScript modules support"},"id":"65ad22baddbdd"}`

**Host violates local access rules:**
`{"reqId":"Za0hieI4tzKF-QVLu1D6wwAA1iE","level":0,"time":"2024-01-21T13:52:11+00:00","remoteAddr":"192.168.0.30","user":"user","app":"settings","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Can not connect to local server for checking JavaScript modules support","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.2.0","exception":{"Exception":"OCP\\Http\\Client\\LocalServerException","Message":"Host violates local access rules","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/Http/Client/Client.php","line":261,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/apps/settings/lib/SetupChecks/JavaScriptModules.php","line":67,"function":"head","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":49,"function":"run","class":"OCA\\Settings\\SetupChecks\\JavaScriptModules","type":"->"},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":303,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","Line":150,"message":"Can not connect to local server for checking JavaScript modules support","exception":[],"url":"https://cloud.nextcloud.tld/apps/settings/js/esm-test.mjs","CustomMessage":"Can not connect to local server for checking JavaScript modules support"},"id":"65ad22badfee9"}`

**Comment by rchaconmolero** [comment]
{"reqId":"gyjwFmfci2qcrrnrMlA6","level":0,"time":"2024-01-21T15:24:40+01:00","remoteAddr":"10.236.138.4","user":"adminnext","app":"settings","method":"GET","url":"/settings/ajax/checksetup","message":"Can not connect to local server for checking JavaScript modules support","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0","version":"28.0.2.0","exception":{"Exception":"OCP\\Http\\Client\\LocalServerException","Message":"Could not detect any host","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":260,"function":"preventLocalAddress","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/JavaScriptModules.php","line":67,"function":"head","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":49,"function":"run","class":"OCA\\Settings\\SetupChecks\\JavaScriptModules","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":303,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Http/Client/Client.php","Line":192,"message":"Can not connect to local server for checking JavaScript modules support","exception":[],"url":"next01d.canal-sur.interno/apps/settings/js/esm-test.mjs","CustomMessage":"Can not connect to local server for checking JavaScript modules support"},"id":"65ad296c9a981"}

**Comment by solracsf** [comment]
@susnux should we add a 

`'nextcloud' => ['allow_local_address' => true]`

to the httpClient params?

https://github.com/nextcloud/server/blob/1612d025cf21ac0ae70327c46dd59be66c096627/apps/settings/lib/SetupChecks/JavaScriptModules.php#L67

**Comment by susnux** [comment]
> @susnux should we add a
> 
> `'nextcloud' => ['allow_local_address' => true]`
> 
> to the httpClient params?
> 
> https://github.com/nextcloud/server/blob/1612d025cf21ac0ae70327c46dd59be66c096627/apps/settings/lib/SetupChecks/JavaScriptModules.php#L67

Yes! I wonder why it did work when I tested it. This will probably resolve this issue!

**Comment by solracsf** [comment]
@pandusen please try https://github.com/nextcloud/server/pull/42999 and report back if possible.

**Comment by rchaconmolero** [comment]
In my case, with 'allow_local_address' => true, in config.php does not resolve the problem.

**Comment by solracsf** [comment]
Have you all tried the PR, or just edited the config.php file?

**Comment by scttstrck** [comment]
I did both. I edited line 67 in apps/settings/lib/SetupChecks/JavaScriptModules.php , which was then formatted into multiple lines, and I added line 78.

**Comment by susnux** [comment]
> I did both. I edited line 67 in apps/settings/lib/SetupChecks/JavaScriptModules.php , which was then formatted into multiple lines, and I added line 78.

Can you please look at your log and send the log message?

> Also it would be really helpful if you could set the logging level to debug and send the logfile here, or at least, search the log for an entry like the following and send that complete entry if it exists:
>
> Can not connect to local server for checking JavaScript modules support

As this should now be a different one

**Comment by solracsf** [comment]
Ok I'm out of ideas here, and I can't reproduce the error on my test instances 😭 

```
curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs
```

But, as long as the `Content-Type` returned by the above comand is either `application/javascript` or `text/javascript`, this warning/error is purely cosmetic and everything works as expected 👍

**Comment by pandusen** [comment]
The PR by it selv, cleared the error in the Nextcloud dashboard.
Adding the line in config.php, makes no difference.
For good measure i copied the edited loop from my JavaScriptModeules.php, in case i mistyped, and just broke the checking
function.
```
foreach ($testURLs as $testURL) {
			try {
				$client = $this->clientService->newClient();
				$response = $client->head($testURL, [
					'connect_timeout' => 10,
					'nextcloud' => [
						'allow_local_address' => true,
					],
				]);
				if (preg_match('/(text|application)\/javascript/i', $response->getHeader('Content-Type'))) {
					return SetupResult::success();
				}
			} catch (\Throwable $e) {
				$this->logger->debug('Can not connect to local server for checking JavaScript modules support', ['exception' => $e, 'url' => $testURL]);
				return SetupResult::warning($this->l10n->t('Could not check for JavaScript support. Please check manually if your webserver serves `.mjs` files using the JavaScript MIME type.'));
			}
		}
```

**Comment by susnux** [comment]
@pandusen so I understand it correctly, if using the code from the pull request the error is gone?

**Comment by pandusen** [comment]
@susnux Yes, in my instance, the error is gone after editing updating the code. It is neither in Dashboard or Logfile at Debug level.
(Seemingly, I dont even have to add anything to the Nextcloud config.php)

**Comment by susnux** [comment]
ok thank you :)

**Comment by theoriginalguy** [comment]
After upgrading to 28.02 RC3 I noticed that there is no support for self-signed certificates and the behavior is to leave an unclear-able warning message:

"Could not check for JavaScript support. Please check manually if your webserver serves .mjs files using the JavaScript MIME type."

Can you add a flag in the JavaScriptModeules.php to support self-signed certificates? Something like:
'nextcloud' =>
            'allow_local_address' => true,
            'ignore_ssl_certificate' => true,
],

OR 

'nextcloud' =>
            'allow_local_address' => true,
            'allow_self_signed_certs' => true,
],

**Comment by WechuTM** [comment]
> After upgrading to 28.02 RC3 I noticed that there is no support for self-signed certificates and the behavior is to leave an unclear-able warning message:
> 
> "Could not check for JavaScript support. Please check manually if your webserver serves .mjs files using the JavaScript MIME type."
> 
> Can you add a flag in the JavaScriptModeules.php to support self-signed certificates? Something like: 'nextcloud' => 'allow_local_address' => true, 'ignore_ssl_certificate' => true, ],
> 
> OR
> 
> 'nextcloud' => 'allow_local_address' => true, 'allow_self_signed_certs' => true, ],

@theoriginalguy  I think this is a good solution

**Comment by susnux** [comment]
> After upgrading to 28.02 RC3 I noticed that there is no support for self-signed certificates and the behavior is to leave an unclear-able warning message:

Different issue, handled in https://github.com/nextcloud/server/issues/43153

**Comment by peternormann** [comment]
For those that experience this issue and use `nginx` as reverse proxy:

I had the same issue and tested with  `esm-test.mjs` command above:
```
$ curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs
HTTP/2 200 
server: nginx
date: Thu, 01 Feb 2024 14:19:31 GMT
content-type: application/octet-stream
content-length: 109
last-modified: Thu, 01 Feb 2024 08:37:38 GMT
etag: "65bb5852-6d"
strict-transport-security: max-age=63072000; includeSubDomains;  preload
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
accept-ranges: bytes
```

Noting that the `content-type` is `application/octet-stream` being my default mime-type for extensions,  `nginx` obviously doesn't have the .mjs' extension in the mime.types file.

I fixed the issue by adding the .mjs extension to nginx.conf like this: 

```
http {
	...
	
	include /etc/nginx/mime.types;

	types {
	    application/javascript mjs;
	}

	default_type application/octet-stream;
	
	...
}
```

Credits: https://github.com/storybookjs/storybook/issues/20157#issuecomment-1500456820

**Comment by cpu2910** [comment]
> For those that experience this issue and use `nginx` as reverse proxy:
> 
> I had the same issue and tested with `esm-test.mjs` command above:
> 
> ```
> $ curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs
> HTTP/2 200 
> server: nginx
> date: Thu, 01 Feb 2024 14:19:31 GMT
> content-type: application/octet-stream
> content-length: 109
> last-modified: Thu, 01 Feb 2024 08:37:38 GMT
> etag: "65bb5852-6d"
> strict-transport-security: max-age=63072000; includeSubDomains;  preload
> referrer-policy: no-referrer
> x-content-type-options: nosniff
> x-download-options: noopen
> x-frame-options: SAMEORIGIN
> x-permitted-cross-domain-policies: none
> x-robots-tag: noindex, nofollow
> x-xss-protection: 1; mode=block
> accept-ranges: bytes
> ```
> 
> Noting that the `content-type` is `application/octet-stream` being my default mime-type for extensions, `nginx` obviously doesn't have the '.mjs' extension in the mime.types file.
> 
> I fixed the issue by adding the .mjs extension to nginx.conf like this:
> 
> ```
> http {
> 	...
> 	
> 	include /etc/nginx/mime.types;
> 
> 	types {
> 	    application/javascript mjs;
> 	}
> 
> 	default_type application/octet-stream;
> 	
> 	...
> }
> ```
> 
> Credits: [storybookjs/storybook#20157 (comment)](https://github.com/storybookjs/storybook/issues/20157#issuecomment-1500456820)

After fixing the mime-type issue as described above, my nginx still won't deliver .mjs correctly.

In the /etc/nginx/sites-enabled/your-vhost.conf I had to add mjs also:
Look for this and add mjs to location:

```
# Adding the cache control header for js, css and map files
    # Make sure it is BELOW the PHP block
    location ~ \.(?:css|**mjs**|js|woff2?|svg|gif|map|png|jpg|ico)$ {
```

**Comment by joshtrichards** [comment]
Both changes are also fully covered in the Admin Manual:

https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

**Comment by Dubbeldrank** [comment]
> > For those that experience this issue and use `nginx` as reverse proxy:
> > I had the same issue and tested with `esm-test.mjs` command above:
> > ```
> > $ curl -I https://your.nextcloud.tld/apps/settings/js/esm-test.mjs
> > HTTP/2 200 
> > server: nginx
> > date: Thu, 01 Feb 2024 14:19:31 GMT
> > content-type: application/octet-stream
> > content-length: 109
> > last-modified: Thu, 01 Feb 2024 08:37:38 GMT
> > etag: "65bb5852-6d"
> > strict-transport-security: max-age=63072000; includeSubDomains;  preload
> > referrer-policy: no-referrer
> > x-content-type-options: nosniff
> > x-download-options: noopen
> > x-frame-options: SAMEORIGIN
> > x-permitted-cross-domain-policies: none
> > x-robots-tag: noindex, nofollow
> > x-xss-protection: 1; mode=block
> > accept-ranges: bytes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Noting that the `content-type` is `application/octet-stream` being my default mime-type for extensions, `nginx` obviously doesn't have the '.mjs' extension in the mime.types file.
> > I fixed the issue by adding the .mjs extension to nginx.conf like this:
> > ```
> > http {
> > 	...
> > 	
> > 	include /etc/nginx/mime.types;
> > 
> > 	types {
> > 	    application/javascript mjs;
> > 	}
> > 
> > 	default_type application/octet-stream;
> > 	
> > 	...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Credits: [storybookjs/storybook#20157 (comment)](https://github.com/storybookjs/storybook/issues/20157#issuecomment-1500456820)
> 
> After fixing the mime-type issue as described above, my nginx still won't deliver .mjs correctly.
> 
> In the /etc/nginx/sites-enabled/your-vhost.conf I had to add mjs also: Look for this and add mjs to location:
> 
> ```
> # Adding the cache control header for js, css and map files
>     # Make sure it is BELOW the PHP block
>     location ~ \.(?:css|mjs|js|woff2?|svg|gif|map|png|jpg|ico)$ {
> ```

I applied these changed to my mime.types file and vhost and the error was gone. Thanks!

**Comment by cowanmax** [comment]
Many thanks for this solution. I have the same case in nginx.
I added:
`	**application/javascript				  mjs;**`
in /etc/nginx/mime.types
and in vhost config:
`location ~ \.(?:css|**mjs**|js|svg|gif|png|jpg|ico|wasm|tflite|map)`

**Comment by hardingt** [comment]
Same issue here
I don't use nginx

I've tried with 'allow_local_address' => true into the config.php and no luck, going to remove it

FWIW:
<img width="834" alt="Screenshot 2024-02-02 at 9 23 19 AM" src="https://github.com/nextcloud/server/assets/11567315/b999b03b-b8a1-43a5-9d3e-a5ba6fa147c9">
<img width="490" alt="Screenshot 2024-02-02 at 9 22 31 AM" src="https://github.com/nextcloud/server/assets/11567315/dfa4c84c-3f16-4258-b3cd-f1adc211c828">

and

```
me@me ~ % curl -I https://mydomain/apps/settings/js/esm-test.mjs
HTTP/1.1 200 OK
Date: Fri, 02 Feb 2024 14:26:12 GMT
Server: Apache/2.4.41 (Ubuntu)
Strict-Transport-Security: max-age=15552000; includeSubDomains
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1; mode=block
Last-Modified: Fri, 02 Feb 2024 13:55:53 GMT
ETag: "6d-6106678759834"
Accept-Ranges: bytes
Content-Length: 109
Cache-Control: max-age=15778463
Content-Type: text/javascript
```

**Comment by hardingt** [comment]
Should I make a new bug report @susnux , it looks like this one is closed (I admit I didn't notice this when I commented)

**Comment by joshtrichards** [comment]
@hardingt Not sure your installation environment, but what happens when you run that `curl` command from the Nextcloud app container/server itself?

**Comment by susnux** [comment]
@hardingt are you running 28.0.2? If not please update as the fixes are included in that version.
If you use self signed certificates you would have to wait for 28.0.3 and just ignore the warning.

**Comment by hardingt** [comment]
Running 28.0.2, it's when I first noticed the issue

I'm not sure how to run the curl command from the app server itself, when I do it just hangs, is there a specific path I should be using instead of https://mydomain/apps/settings/js/esm-test.mjs?

```
root@nextcloud:/var/www/nextcloud/config# curl -I https://mydomain/apps/settings/js/esm-test.mjs

```
I usually cancel it after 30 seconds.

**Comment by susnux** [comment]
Maybe try `-v` flag to show where it hangs?

Also you might need the `index.php/` part within the URL, depending on the configuration of your server?

You could also enable debug log level (`'loglevel' => 0`) and post the log entry from the failed setup check.

**Comment by Aaron-von-Awesome** [comment]
Also getting this error after updating from 28.0.1 to 28.0.2

**Comment by vasyugan** [comment]
I was his by this after upgrading NC 27.6 to 28.2

I've solved this for me by modifying the file /etc/nginx/mime.type,
changing the line
 
`application/javascript                js;`
to 
`application/javascript                js mjs;`

If a change to the webserver config is required, then there should be instructions to to so

**Comment by joshtrichards** [comment]
@vasyugan 
> If a change to the webserver config is required, then there should be instructions to to so

There are. See the Admin Manual (https://docs.nextcloud.com). The nginx config in the manual for the last two major releases includes it and it was also noted in the first release that required it in the release notes section of the Admin Manual. It's been required since NC27, but impacts more things in NC28 so a lot of folks didn't notice until now. :-)

**Comment by hardingt** [comment]
@joshtrichards 
I see it here:
<img width="630" alt="image" src="https://github.com/nextcloud/server/assets/11567315/7eb8b9ed-951c-4847-9ae0-0cd9068c6eaa">
and here
<img width="748" alt="image" src="https://github.com/nextcloud/server/assets/11567315/3aef3bdb-456e-4099-a419-67b085f49e72">
but both reference nginx, many of us aren't using nginx it seems from the logs posted here.

@susnux I'll take a look tomorrow with the suggestions you given. My guess is that my dns isn't set up to redirect my domain name to local host, and I'm not savvy enough to know what setting that up would do to the SSL cert:

`curl: (60) SSL: no alternative certificate subject name matches target host name 'localhost'`

I'll see about turning on the debug log.

**Comment by joshtrichards** [comment]
@hardingt 

> but both reference nginx, many of us aren't using nginx it seems from the logs posted here.

It's irrelevant for Apache since we provide an updated `.htaccess` with each release. And we don't provide configs for any other web servers.

**Comment by hendricksond** [comment]
I'm using apache. After updating to 28.0.2 today I'm getting the error:

```
Could not check for JavaScript support. Please check manually if your webserver serves `.mjs` files using the JavaScript MIME type.
```

Output of `curl -I https://DOMAIN/apps/settings/js/esm-test.mjs`:

```
HTTP/1.1 200 OK
Date: Fri, 02 Feb 2024 18:57:01 GMT
Server: Apache/2.4.57 (Debian)
Strict-Transport-Security: max-age=15552000; includeSubDomains
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1; mode=block
Upgrade: h2,h2c
Connection: Upgrade
Last-Modified: Thu, 01 Feb 2024 09:37:38 GMT
ETag: "6d-6104ebefcdc80"
Accept-Ranges: bytes
Content-Length: 109
Vary: Accept-Encoding
Cache-Control: max-age=15778463
Content-Type: text/javascript
```

**Comment by spiezmaestro** [comment]
I was having the same issue with 28.0.2 on Apache. I used to connect to Apache directly, but have now pfSense in front of it. It appeared, that the certificate on Apache expired (did not notice as I connect via pfSense and ignore cert issues from the backend). This was however causing issues with the check for .mjs. After updating the certificate, the error was gone.

**Comment by susnux** [comment]
> If a change to the webserver config is required, then there should be instructions to to so

As Josh already mentioned, this is in the Admin manual since Nextcloud 27.

Please see here for the self-signed certificate issue: https://github.com/nextcloud/server/issues/43153

**Comment by BurtGummer** [comment]
> You can safely ignore the warning if curl -I https://DOMAIN/apps/settings/js/esm-test.mjs shows content type text/javascript

I have the same problem and curl shows "content type text/javascript", but I hate ignoring warnings, if this warning is so insignificant, there should be an option to hide this warning and still get the green tick.

**Comment by MortRainey** [comment]
Why is this closed? Its not resolved? I Have tryed every tip here and nothing works. Letsencrypt Cert, nginx and nginx as Proxy. 

i don't know why, but i have two instances and one of them has this warning. The other not.

**Comment by hardwareadictos** [comment]
Same issue here. Can someone reopen the issue? We've freezed our production environmrnt on 28.0.1, which doesn't face this issue.

**Comment by BurtGummer** [comment]
> > Same issue here. Can someone reopen the issue? We've freezed our production environmrnt on 28.0.1, which doesn't face this issue.
> 
> It isn't Nextcloud issue, you probably need to reconfigure your webserver.

However, this does not appear to be the case, as the curl command is executed correctly. Even if I use

`AddType text/javascript .js .mjs`

in my

`/etc/apache2/mods-enabled/mime.conf`

the message does not go away. I also try js and mjs without . Does not change anything.

**Comment by susnux** [comment]
Please **read** before posting: https://github.com/nextcloud/server/issues/42989#issuecomment-1925312887

> If this warning is so insignificant, there should be an option to hide this warning and still get the green tick.

It is a warning and is meaning your instance can not check that it serves files correctly, so in any case if it is show there **is** an error with your webserver configuration, but if the curl command shows the correct output then it means just your server is misconfigured (you do not trust your own certificate, your DNS resolving is broken, etc).

> Why is this closed? Its not resolved?

The initial issue is resolved with 28.0.2. Another aspect is handled by https://github.com/nextcloud/server/issues/43153
If you face a different issue than #43153 than **open a new issue WITH debug log messages** so we can dig into the issue.

> We've freezed our production environmrnt on 28.0.1, which doesn't face this issue.

Probably not a good reason as 28.0.2 provides a bunch of fixes, even one for this.

> > It isn't Nextcloud issue, you probably need to reconfigure your webserver.
>
> However, this does not appear to be the case, as the curl command is executed correctly.

The first part is probably correct, this is a webserver issue, IF the curl command shows the correct output probably your server is misconfigured, meaning FROM within your server it CAN NOT connect to itself.
Meaning if your webserver is running on example.com than your webserver needs to be able to connect to example.com (itself). If it can not check that you configured DNS correctly, set `trusted_domains` correctly.


But as already said: **Before post, read this (1).
It does not help if you just reply with "I am also affected" that does not provide any information, instead please at least include the log messages from `nextcloud.log` when setting `loglevel` to `0`.

(1): https://github.com/nextcloud/server/issues/43153

**Comment by hardwareadictos** [comment]
> Please **read** before posting: [#42989 (comment)](https://github.com/nextcloud/server/issues/42989#issuecomment-1925312887)
> 
> > But if I enter this command from localhost
> 
> @BurtGummer thats the issue your webserver ("localhost") is misconfigured you can not resolve your own DNS.
> 
> > If this warning is so insignificant, there should be an option to hide this warning and still get the green tick.
> 
> It is a warning and is meaning your instance can not check that it serves files correctly, so in any case if it is show there **is** an error with your webserver configuration, but if the curl command shows the correct output then it means just your server is misconfigured (you do not trust your own certificate, your DNS resolving is broken, etc).
> 
> > Why is this closed? Its not resolved?
> 
> The initial issue is resolved with 28.0.2. Another aspect is handled by #43153 If you face a different issue than #43153 than **open a new issue WITH debug log messages** so we can dig into the issue.
> 
> > We've freezed our production environmrnt on 28.0.1, which doesn't face this issue.
> 
> Probably not a good reason as 28.0.2 provides a bunch of fixes, even one for this.
> 
> > > It isn't Nextcloud issue, you probably need to reconfigure your webserver.
> > 
> > 
> > However, this does not appear to be the case, as the curl command is executed correctly.
> 
> The first part is probably correct, this is a webserver issue, IF the curl command shows the correct output probably your server is misconfigured, meaning FROM within your server it CAN NOT connect to itself. Meaning if your webserver is running on example.com than your webserver needs to be able to connect to example.com (itself). If it can not check that you configured DNS correctly, set `trusted_domains` correctly.
> 
> But as already said: **Before post, read this (1). It does not help if you just reply with "I am also affected" that does not provide any information, instead please at least include the log messages from `nextcloud.log` when setting `loglevel` to `0`.
> 
> (1): #43153

Sorry, maybe i didn't explain it correctly, my test server is now on 28.0.2 which has this .mjs warning issue while my production server which is on 28.0.1 isn't suffering from it. That's why we are keeping our production on 28.0.1.

**Comment by joshtrichards** [comment]
> Sorry, maybe i didn't explain it correctly, my test server is now on 28.0.2 which has this .mjs warning issue while my production server which is on 28.0.1 isn't suffering from it. That's why we are keeping our production on 28.0.1.

@hardwareadictos That's not surprising since the check was added in v28.0.2. :-) But it doesn't change the fact that it's a check added for a good reason. Troubleshooting steps have been provided several times above.

**Comment by jameskimmel** [comment]
> In the /etc/nginx/sites-enabled/your-vhost.conf I had to add mjs also: Look for this and add mjs to location:

Sorry @Dubbeldrank for asking you directly, but you seem one of the few people that is using NGINX as a proxy in front of the apache Nextcloud instance. 

I added changed my mime.types like this:

```
    # disabled because of nextcloud    
    #application/javascript                           js;
    text/javascript                                  js mjs;
```
and my nginx.conf has this in it:

```
    # MIME
    include                mime.types;
    default_type           application/octet-stream;

```

my vhost for nextcloud looks like this: 

```
    # reverse proxy
    location / {
        proxy_pass            http://internal_IPv4_apache/;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;

    }
```

But I will still get 
`content-type: text/html; charset=UTF-8`

Would you mind sharing you setup a little bit more or do you see my error?

**Comment by cpu2910** [comment]
Hope this will help , because in my config it works:
```
/etc/nginx/mime.types:
application/javascript                js mjs;
```
And in my vhost-file there is a line (location...), where I added mjs :
```
# Adding the cache control header for js, css and map files
# Make sure it is BELOW the PHP block
location ~ \.(?:css|mjs|js|woff2?|svg|gif|map|png|jpg|ico)$ {
```

**Comment by jameskimmel** [comment]
Thanks cpu, but that is exactly where I am stuck. What comes after { ?
In my understanding, I am already proxying everything with` location /`
Do I just do the same with location ~ ?
Something like this?

```
    location ~ \.(?:css|mjs|js|woff2?|svg|gif|map|png|jpg|ico)$ {
        proxy_pass            http://internal_IPv4_apache/;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;
    }
```

**Comment by joshtrichards** [comment]
Hi @jameskimmel:

> using NGINX as a proxy in front of the apache Nextcloud instance

If you're truly using Nginx in front of Apache, then it sounds like your real issue is that your Apache environment isn't set up to use the distributed `.htaccess` that comes with each Nextcloud Server release (and automatically updated as needed). It already includes the appropriate configuration for handling `mjs` files. So you need to isolate what is different about your environment that doesn't match one of the documented installation methods. 

Please shift this discussion for deeper troubleshooting to the Help Forum - https://help.nextcloud.com - so that developer inboxes aren't getting filled up with each comment here. :-)

**Comment by hendricksond** [comment]
> # HELP, I am also affected by this
> 
>     1. Please make sure you are not using self signed certificates and your certificates are not expired.

I do not use self-signed certs. My certs are not expired.

>     2. Make sure you can connect from your web server to your web server, meaning if you have custom DNS then your server must be able to resolve its domain name (one of the `trusted_domains`).

My server can connect to itself.

>     3. If you use NGinx please read the current [admin documentation](https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html) on how to add `.mjs` support.

I use apache2.

>     4. You can safely ignore the warning if `curl -I https://DOMAIN/apps/settings/js/esm-test.mjs` shows content type `text/javascript`

Then, how do I get the warning to go away? I would like it to come back if this configuration breaks for some reason, but always having it there as a false positive is not helpful.

**Comment by cpu2910** [comment]
> Thanks cpu, but that is exactly where I am stuck. What comes after { ? In my understanding, I am already proxying everything with` location /` Do I just do the same with location ~ ? Something like this?
> 
> ```
>     location ~ \.(?:css|mjs|js|woff2?|svg|gif|map|png|jpg|ico)$ {
>         proxy_pass            http://internal_IPv4_apache/;
>         proxy_set_header Host $host;
>         include               nginxconfig.io/proxy.conf;
>     }
> ```

I'm using the configuration described here:
https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

**Comment by hardwareadictos** [comment]
> https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html

Just for the ones deploying nextcloud on docker with nginx proxy, just deployed this version of nginx.conf (mine was quite outdated): https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf

And error just went away:

![image](https://github.com/nextcloud/server/assets/20403906/0a16dc45-b893-4244-b3d6-786f6492c210)

**Comment by molotov44** [comment]
I was able to fix the error message; there was still a wrong host entry in /etc/hosts. With "PUBLICIP your.nextcloud.com" the error message has now disappeared. Just a little tip, maybe check the host file :)

**Comment by deadmen0** [comment]
> I was able to fix the error message; there was still a wrong host entry in /etc/hosts. With "PUBLICIP your.nextcloud.com" the error message has now disappeared. Just a little tip, maybe check the host file :)

Yes, if you use Unix with Docker and revers proxy is install in another VM. 
Unix where install docker and start NC probably has been the same hostname with PUBLICIP fqdn and NC get ip 127.0.1.1 for curl. 
You need change hostname Unix or add in docker NC "echo "PUBLICIP our.nextcloud.com" >> /etc/hosts"

Easy way diagnostic this problem is call "curl -I https://our.nextcloud.com/apps/settings/js/esm-test.mjs" with external VM if you get content-type: text/javascript, you have problem with hosts file.

**Comment by allolatr** [comment]
The test for .mjs  file fails also on a site  protected with ssl client certificate, as it cannot  use any.

**Comment by janipewter** [comment]
I have this issue in my Nextcloud due to my setup using Docker containers and reverse proxy, the main URL for the Nextcloud instance is not accessible by the Docker container itself.

```
root@98dde04210c0:/# curl -I https://my.nextcloud.tld/apps/settings/js/esm-test.mjs
curl: (7) Failed to connect to my.nextcloud.tld port 443 after 3111 ms: Couldn't connect to server
```

This is because `my.nextcloud.tld` resolves to the IP address of the reverse proxy in my LAN subnet, which the Nextcloud docker container cannot reach because it does not have access to my LAN. However, the Nextcloud docker can access itself by its container hostname:

```
root@98dde04210c0:/# curl -I http://nextcloud/apps/settings/js/esm-test.mjs
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 08 Mar 2024 20:28:36 GMT
Content-Type: text/javascript
Content-Length: 109
Last-Modified: Sat, 02 Mar 2024 03:02:18 GMT
Connection: keep-alive
ETag: "65e296ba-6d"
Cache-Control: public, max-age=15778463, 
Accept-Ranges: bytes
```

Note that this does not have HTTPS though. I tried to add this as a trusted domain in the config in the hope that it might try to use it in the Javascript check but it doesnt:

```
  'trusted_domains' => 
  array (
    0 => 'nextcloud',
    1 => 'my.nextcloud.tld',
  ),

```

Is there anything else I can do?

**Comment by susnux** [comment]
You could set `my.nextcloud.tld` to resolve to localhost on your docker container (`/etc/hosts`)

**Comment by janipewter** [comment]
> You could set `my.nextcloud.tld` to resolve to localhost on your docker container (`/etc/hosts`). Or try `overwrite.cli.url` (see admin docs).

Thanks, the first option does work, but won't this be overwritten whenever the Docker image is updated? Not a sustainable fix I think.

I already have overwrite cli url set to the public URL of the Nextcloud so I can't change this.

**Comment by janipewter** [comment]
OK - seems I can add host-specific DNS override for the container with the argument `--add-host=my.nextcloud.tld:127.0.0.1`

I think this is sufficient to fix the issue

**Comment by HH-boncon** [comment]
> OK - seems I can add host-specific DNS override for the container with the argument `--add-host=my.nextcloud.tld:127.0.0.1`
> 
> I think this is sufficient to fix the issue

Hello everyone.
I'm writing this just to share my solution based on the above post with the sole hope that it may help somebody should they get as stuck as I was.
I realise that the issue doesn't have (probably) much implication on the functionality of nextcloud, but the look of it did really angry me. Mind you that I'm in no way a specialist or a pro, or whatever.
My setup is a docker compose stack like so: caddy (as proxy) -> nginx -> nextcloud-fpm.
The solution that worked for me is adding an extra host in the nextcloud-fpm container like so:

`extra hosts:`
`  - "my.nextcloud.tld:ip address of caddy from the docker network" ` # I have the address set as static. Haven't tried with the service name, perhaps it could work.
 
In docker it would be something like `"--add-host=my.nextcloud.tld:ip address of the proxy"`, I guess.
If this is a stupid solution in some way that I'm unaware of, please ignore it.

Best

**Comment by janipewter** [comment]
> > OK - seems I can add host-specific DNS override for the container with the argument `--add-host=my.nextcloud.tld:127.0.0.1`
> > I think this is sufficient to fix the issue
> 
> Hello everyone. I'm writing this just to share my solution based on the above post with the sole hope that it may help somebody should they get as stuck as I was. I realise that the issue doesn't have (probably) much implication on the functionality of nextcloud, but the look of it did really angry me. Mind you that I'm in no way a specialist or a pro, or whatever. My setup is a docker compose stack like so: caddy (as proxy) -> nginx -> nextcloud-fpm. The solution that worked for me is adding an extra host in the nextcloud-fpm container like so:
> 
> `extra hosts:` ` - "my.nextcloud.tld:ip address of caddy from the docker network"` # I have the address set as static. Haven't tried with the service name, perhaps it could work.
> 
> In docker it would be something like `"--add-host=my.nextcloud.tld:ip address of the proxy"`, I guess. If this is a stupid solution in some way that I'm unaware of, please ignore it.
> 
> Best

Hi, have you checked that this fix persists after a reboot? As I believe by default, Docker issues IP addresses in the Docker network randomly, so there is no guarantee your caddy container will get the same Dockernet IP every time.

**Comment by HH-boncon** [comment]
It does persist a reboot.
As I mentioned, the caddy container has a static ip - I used it to get onlyoffice-ds working under the same caddy (for the automatic ssl certificate).
The whole setup is on its own docker network.
Now I wonder if it would work with the caddy service name instead of ip address.

**Comment by MrPenguin07** [comment]
Just quickly confirming this on my end.
Haven't had time to fully diagnose yet, however unlike it seems many here my setup differs;
I run nextcloud via turnkey LXC container under proxmox.
Also my container uses haproxy for reverse proxy.

I hope to find time to pin this down and report back in the coming days.

**Comment by janipewter** [comment]
> Just quickly confirming this on my end. Haven't had time to fully diagnose yet, however unlike it seems many here my setup differs; I run nextcloud via turnkey LXC container under proxmox. Also my container uses haproxy for reverse proxy.
> 
> I hope to find time to pin this down and report back in the coming days.

Not sure what there is to confirm? This occurs when Nextcloud cannot reach itself by the URL you have configured for it. Considering this is most likely the case in setups where people are using reverse proxies, which you are doing, it's almost certainly the cause of your issue.

**Comment by Satalink** [comment]
I've noticed 
shell:  `curl -I https://cloud.satalink.net/apps/settings/js/esm-test.mjs`  gets 400 err response.  

browser:  `https://cloud.satalink.net/apps/settings/js/esm-test.mjs`   gets  
`/**
 * This is a dummy file for testing webserver support of JavaScript modules.
 */
export default 'Hello'`

I'm not doing reverse proxy but wonder if there's a difference between curl and the browser..?

**Comment by Satalink** [comment]
On my instance, the fix was to disable CloudFlare proxy.  The proxy was transforming text/javascript to text/html.   There's potentially a "worker" solution for this in CloudFlare, but I did not pursue it.

It is also noteworthy to pay attention to apache `<IfModule ...>`  lines.   

Some instances of Apache use `<IfModule mod_mime.c>`  while others use `<IfModule mime_module>`

**Comment by ondrejlohnisky** [comment]
### Possible solution for nginx.
I am running nextcloud on nginx and updating this part of the nginx nextcloud server config **fixed** this issue.:
```
location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=15778463, $asset_immutable";
        access_log off;     # Optional: Don't log access to assets

        location ~ \.wasm$ {
            default_type application/wasm;
        }

        location ~ \.mjs$ {
            default_type text/javascript;
        }

    }

```
_I hope it helps someone_ **!**

**Comment by Danielsc87** [comment]
Just in case anyone wants a fix for this error on openLiteSpeed server. 
i got this error on fresh install 
vultr cyberpanel VPS
openlightspeed server. 1.7.19 
Ubuntu 20.04.6 LTS
[Nextcloud Hub 7] (28.0.4)

Go to this folder /usr/local/lsws/conf
edit this file mime.properties, by adding
mjs     = application/javascript
![image](https://github.com/nextcloud/server/assets/59422629/31709cd4-0b46-468c-ac48-b574d0c8ffd9)

Restart server and off you go

![1141980e9218a8612bf1136bccf9a8a3b331ff70_2_247x500](https://github.com/nextcloud/server/assets/59422629/b9633654-6050-4831-aa79-b9c9c254638c)

**Comment by jlhollowell** [comment]
Thanks [ondrejlohnisky](https://github.com/ondrejlohnisky)

You're contribution here finally led me to a solution. I had to remove $asset_immutable but doing so finally resolved the issue for me. 

location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=15778463";
        access_log off;     # Optional: Don't log access to assets

        location ~ \.wasm$ {
            default_type application/wasm;
        }

        location ~ \.mjs$ {
            default_type text/javascript;
        }

    }

**Comment by joshtrichards** [comment]
@jlhollowell & @ondrejlohnisky: If adjusting `$asset_immutable` fixed things for you, please confirm your Nginx config matches our docs and is up-to-date: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

 I've seen some tutorials floating around where people appear to attempt to correct what they thing is a typo in the earlier $asset_immutable definition. But doing that is what breaks the later reference to it. The correct config (full can be pulled from the link just mentioned) is below:

```
# Set the `immutable` cache control options only for assets with a cache busting `v` argument
map $arg_v $asset_immutable {
    "" "";
    default ", immutable";
}
```
[...]
```
        add_header Cache-Control                     "public, max-age=15778463$asset_immutable";
```

**Comment by Destripador** [comment]
> ### Possible solution for nginx.
> 
> I am running nextcloud on nginx and updating this part of the nginx nextcloud server config **fixed** this issue.:
> 
> ```
> location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map)$ {
>         try_files $uri /index.php$request_uri;
>         add_header Cache-Control "public, max-age=15778463, $asset_immutable";
>         access_log off;     # Optional: Don't log access to assets
> 
>         location ~ \.wasm$ {
>             default_type application/wasm;
>         }
> 
>         location ~ \.mjs$ {
>             default_type text/javascript;
>         }
> 
>     }
> ```
> 
> _I hope it helps someone_ **!**

this fix my problem @ondrejlohnisky  thanks

**Comment by jhonyesg** [comment]
la solucion me funciono quitando el asset_immutable, tambien como tenia errores de carga del pdf, de txt, junto una lentitud la cual con esta regla logre hacer que fuera mas fluida # Combined location block for static files including .mjs
    location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|txt|log)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=15778463";
        access_log off;     # Optional: Don't log access to assets

        location ~ \.wasm$ {
            default_type application/wasm;
        }

        location ~ \.mjs$ {
            default_type text/javascript;
        }
        
        location ~ \.txt$ {
            default_type text/plain;
        }

        location ~ \.log$ {
            default_type text/plain;
        }

    }

**Comment by susnux** [comment]
This issue was fixed for all supported Nextcloud versions.
If you have a similar problem, please open a **new** issue.
Otherwise for general discussion, please use https://help.nextcloud.com/
