### ISSUE TITLE
[Bug]: Upload of multiple files in Edge not possible

### ISSUE THREAD

**Issue by SHellSys** [nextcloud/server#43074]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When dragging multiple files into Nextcloud for upload only one file will be uploaded if I use Edge. On Firefox, all files will be uploaded.

### Steps to reproduce

1. Open target folder in Nextcloud in Edge
2. Drag multiple files for upload onto the upload area
3. Check which files have been uploaded

### Expected behavior

All files should be uploaded.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "\/var\/www\/html\/nextcloud\/core\/comp",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 172800,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "filelocking.enabled": "true",
        "trashbin_retention_obligation": "auto,1",
        "versions_retention_obligation": "disabled",
        "maintenance_window_start": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "maintenance": false,
        "defaultapp": "files",
        "theme": "",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - comments: 1.18.0 (installed 1.2.0)
  - dashboard: 7.8.0 (installed 7.5.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.2.0)
  - files_automatedtagging: 1.18.0 (installed 1.18.0)
  - files_pdfviewer: 2.9.0 (installed 1.2.1)
  - files_retention: 1.17.0 (installed 1.17.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - nextcloud_announcements: 1.17.0 (installed 1.1)
  - polls: 6.0.1 (installed 6.0.1)
  - support: 1.11.0 (installed 1.8.0)
  - survey_client: 1.16.0 (installed 1.0.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.2.0)
  - twofactor_totp: 10.0.0-beta.2
  - weather_status: 1.8.0 (installed 1.5.0)
```

**Comment by skjnldsv** [comment]
Hey, thanks fr the reprt :)
When you say on Edge, have you tried other browsers and they're working? Or you only tried it on Edge

**Comment by bravedave** [comment]
I've just upgrade to 28.02 and am seeing a similar issue

If I upload using the New > Upload files method - no issue
If I upload via Drag & Drop, only the first file is uploaded

I'm using Brave, and have checked in Chrome - same result

Brave is Version 1.62.156 (latest) on Win 11

**Comment by skjnldsv** [comment]
I can reproduce the issue
Let's wait for https://github.com/nextcloud/server/pull/43267 and move on from here! :rocket:

**Comment by stijink** [comment]
Same here for the stable release 28.0.2 on Chrome 121/Mac.

**Comment by nickian** [comment]
After updating, I can also only upload one file at a time with drag and drop. Also, now it only lets me drop files at the top of the page, not anywhere on the page. Much worse user experience suddenly.

**Comment by bravedave** [comment]
> After updating, I can also only upload one file at a time with drag and drop. Also, now it only lets me drop files at the top of the page, not anywhere on the page. Much worse user experience suddenly.

I think this too - moving on from the implementation issues - reducing the drop zone to the top of the page is a worse user experience - Nextcloud is a place to store files - that is the KPI - this is a negative impact on it's primary KPI.

**Comment by arnowelzel** [comment]
I agree that the current solution using a "drag & drop" area is a worse experience compared to how it was before.

Having a visual indicator as feedback that the Nextcloud file manager will accept the dropped files as upload is OK, but only accepting them in a limited "drag here" area is the complete opposite to how desktop file managers work. Older version of Nextcloud accepted files anway in the viewport and not just in certain spots.

**Comment by skjnldsv** [comment]
This is really not the place to discuss this folks :)
Please open a thread on the forum, thanks! :pray:

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by krzys-h** [comment]
I have the same issue as well. It seems like it only affects logged in users - uploading to public share links works fine.

**Comment by AInteriorB** [comment]
Can confirm. One of the main functions of nextcloud and still a problem one month later. Dropping a folder with files is also no longer possible.

And I do agree @arnowelzel that the desicion to change the dropping area to a very small area one must aim is incomprehensible.

**Comment by LM-vb** [comment]
This bug is still present in 28.0.3 (Edge + Chrome, Win 10).

**Comment by susnux** [comment]
> This bug is still present in 28.0.3 (Edge + Chrome, Win 10).

Yes as you can see the bug is still open (!) meaning it is **not** resolved. This is a blink engine issue and we need to find a workaround for broken blink browsers like Chrome, Chromium, Edge and Opera. In the meantime use Firefox or wait for this issue to be resolved.

**Comment by AndyXheli** [comment]
I can confirm this issue also NC28.0.3 any update then this may be fixed. This is a important functionality

**Comment by szaimen** [comment]
Can reproduce this also on nc29.0.0b1

**Comment by AInteriorB** [comment]
Can also confirm the bug. One of nextcloud's key features and still a problem over a month later.

And I do agree @arnowelzel that the desicion to change the dropping area to a very small area is incomprehensible. Time needed to upload files is much slower after the changes.

**Comment by camouflage81** [comment]
When drag and drop a file, the system no longer checks whether it already exists. The file on the server is simply overwritten.

**Comment by AInteriorB** [comment]
Closed as completed ... with all the good suggestions marked as spam ignored ...

🙄

**Comment by susnux** [comment]
This issue is about drag-drop only uploading one file and this issue is fixed now :)
Feel free to open new issues with bug reports or feature requests but it makes no sense to put that into a completely unrelated issue report.

**Comment by D3nnis3n** [comment]
> This issue is about drag-drop only uploading one file and this issue is fixed now :) Feel free to open new issues with bug reports or feature requests but it makes no sense to put that into a completely unrelated issue report.

This issue is not fixed in 28.0.3.

**Comment by skjnldsv** [comment]
With 2 clicks you can see that the fix is within 28.0.4
https://github.com/nextcloud/server/pull/44273

**Comment by SergioRius** [comment]
I'm on 29.0.5 and this issue still reproduces for me on Firefox-based browser (Floorp) and Chrome-based browser (Vivaldi).
I would bet that I didn't happen with the last of 28s.

**Comment by susnux** [comment]
> I'm on 29.0.5 and this issue still reproduces for me on Firefox-based browser (Floorp) and Chrome-based browser (Vivaldi).

29.0.5 with Firefox - can not reproduce drag-and-drop two files and both are uploaded.
Regardless if dropped on drop zone or a folder.

Same with Chromium 128 used with Nextcloud 29.0.5. Try to clear your cache and look in the browser dev tools for error messages.

**Comment by SergioRius** [comment]
Trying to upload 5 files to a new empty folder.

1. Five images to upload
Note: From Linux, KDE Ubuntu to Floop (Firefox)
![image](https://github.com/user-attachments/assets/34e03f3c-6cda-458e-9f55-5c4437da09e8)

2. Dragging to the upload deck
Note: The folder is contained between a group shared folder.
![image](https://github.com/user-attachments/assets/ab2215ba-0c27-4587-b4b7-9260635a91df)

3. The following notifications appear: ("File not found" and "File upload success")
![image](https://github.com/user-attachments/assets/b6507ef3-2e5a-494b-8d71-80676a072c30)

4. Only the first image uploaded.
![image](https://github.com/user-attachments/assets/daf64605-417a-41da-bbc2-043dde60f0bc)

5. Errors on console.
![image](https://github.com/user-attachments/assets/17720463-3d63-499d-bb01-18c98c96ed22)

To me it seems that they all appear after the upload.
I'm investigating the one for duplicated setting, but it's a Vue trace. Anyways I think it could be related to the configuration of PHP OPcache, that I override on ".../nextcloud/php/php-local.ini" (linuxserver docker), but still complains in admin about not being configured above the default.

The upload problem happens with files and folders, independently from it's size. I it always reproduces after the update to 29.x.x

**Comment by susnux** [comment]
@SergioRius could you retry now with 29.0.6 and if that does not work also show your network tab from the dev tools?

**Comment by SergioRius** [comment]
> @SergioRius could you retry now with 29.0.6 and if that does not work also show your network tab from the dev tools?

Thanks for your help, @susnux .
As the new version was published some minutes ago I deployed and did another test with it. Unfortunately it didn't work:
![imagen](https://github.com/user-attachments/assets/0f6ddd49-9195-4222-b149-7dff5a4de8a5)
The file names uploaded are DSC00334.JPG, IMG_20190422_164256.jpg and IMG_20190422_164311.jpg in a new folder at the root. 
The previous error I mentioned about a file missing, it's confirmed that it's totally unrelated. I happens sometimes when I enter a folder that has images.
I usually have plenty of errors from preview generator and recognize in the log. Perhaps it has to do with this upload problem? As I see that there's a PG error in the console after the first file is uploaded, and then almost nothing more...

![imagen](https://github.com/user-attachments/assets/2689878c-3c20-4aeb-a6e6-e678e63230f4)
![imagen](https://github.com/user-attachments/assets/81289d53-3f4b-4e02-84fa-11750cffd37d)

I'll disable recognize, PG and try again. If I don't post any results is that I also did fail.

**Comment by susnux** [comment]
Those errors are about preview generation and should be unrelated. From the network tab there is also only one PUT. Meaning the upload is either aborted or the browser only passed one file for upload.

Could you please check for debug log messages in the dev tools?

BTW: I had this error once with Firefox - restarting Firefox helped as somehow Firefox was not correctly fetching the dragged files.

**Comment by SergioRius** [comment]
> Could you please check for debug log messages in the dev tools?

You mean the debug console? It's only throwed the error reported before:
```
A setting with the same name is already registered Settings.js:41:11
    register Settings.js:41
    render main.js:58
    mounted FilesListHeader.vue:41
    VueJS 21
        cn
        $n
        insert
        C
        xi
        _update
        a
        get
        run
        ra
        kn
        vn
    (Asíncrono: promise callback)
        fn
        kn
        ia
        update
        notify
        set
        set value
        set
        Oe
    updateNodes files.ts:77
    E pinia.mjs:1380
    fetchContent FilesList.vue:321
    onUpload FilesList.vue:392
    VueJS 4
        cn
        n
        cn
        $emit
    onUploadCompletion index-DNLyAvkP.mjs:1323
    _notifyAll index-DNLyAvkP.mjs:395
    n index-DNLyAvkP.mjs:666
    add index.js:180
    #x index.js:118
    #L index.js:149
    start index.js:218
    start index-DNLyAvkP.mjs:361
    qt DropService.ts:143
    onDrop DragAndDropNotice.vue:138
    VueJS 27
        cn
        n
        _wrapper
    (Asíncrono: EventListener.handleEvent)
        jr
        kt
        Pr
        _
        h
        xi
        _update
        a
        get
        e
        mount
        $mount
        init
        h
        h
        E
        E
        xi
        _update
        a
        get
        run
        ra
        kn
```
It would be nice if that error notification function showed the setting key `e.name` that it's supposedly duplicated.

And there's another error about recommendation not able to load a preview. I suppose bc it's too fast to ask for it and still hasn't been generated.

> BTW: I had this error once with Firefox - restarting Firefox helped as somehow Firefox was not correctly fetching the dragged files.

Unfortunately I've even rebooted the computer and made no change.

**Comment by Knusper** [comment]
Just to make some noise, I also have the same issue with Firefox and KDE Dolphin.  Drag & Drop of multiple files to other file providers just works - so it must be on nextcloud side...

**Comment by SergioRius** [comment]
As a followup, since my last update I've migrated to nextcloud-aio, still at v29.
The problem still persists on Firefox based browsers, but using Vivaldi (Chromium based) I can upload more than one file. The Aio install is one build beyond the docker install, so I don't know if as to do with it working on chrome.

**Comment by b-jordanov** [comment]
I’m experiencing the same issue with Firefox and KDE Dolphin. Dragging and dropping multiple files works fine with other file providers, so the problem seems to be on the Nextcloud's side.

**Comment by Knusper** [comment]
Seems to be an issue on Firefox side
https://bugzilla.mozilla.org/show_bug.cgi?id=1914742
