### ISSUE TITLE
[Bug]: linksharing by mail broken with "always ask for password"

### ISSUE THREAD

**Issue by c-0815** [nextcloud/server#44269]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

after upgrading to 27.1.7.2 sharing to external users by mail doesn't work anymore, it doesn't matter if password enforcement is enabled.
"User receives message: "Error creating the share: Passwords are enforced for link and mail shares!

### Steps to reproduce

1. in Administrationmenu-> Sharing "Always ask for a password" is enabled, "Enforce password protection" is disabled
2. in Administrationmenu->Security Password Policy settings are 0 or disabled
(it doesn't matter if passwort policy is active)
4. create a folder and got to the sahring menu as user. Type in external mail and fill out the sharing properties
5. the password is hidden
6.  submit "save share"
7. "User receives message: "Error creating the share: Passwords are enforced for link and mail shares!
8.  the share hasn't created :-(

only with disabled option "Always ask for a password" I the share is created

### Expected behavior

a share by mail is created and no error message occures

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

.

**Comment by c-0815** [comment]
error occures in 28.0.3 too

**Comment by c-0815** [comment]
I discovered that the bug doesn't occure when I diable all default share permissions. So its a combination of the password settings above and these default share permissions. this happens in current the  current version 27 and 28. I hope this helps fixing it.

**Comment by blizzz** [comment]
Mh, I cannot reproduce this behavior. These settings should be correct according to your repro steps?

![Screenshot_20240319_171409](https://github.com/nextcloud/server/assets/2184312/a276a5fc-36b9-400e-894e-54cec1411b91)

**Comment by c-0815** [comment]
have you enabled some default share permissions?

**Comment by blizzz** [comment]
> Have you also enabled some default share permissions?

Yes, all were set. 

I can only reproduce it with "Enforce password protection" enabled.

**Comment by c-0815** [comment]
Interesting. In our nextcloud "Enforcing password protection " is enabled. When I checked various combinations, finally this option was disabled and after I additionally disabled all the defaults, the behavior was better. I think there is a bigger problem with the js code of the share menu, because after the update to 27.1.0.7 also the "share by link"  option doesn't refresh after enabling it, but I wasn't sure if this has the same cause, so I didn't mentioned it.
Anyway you reproduced it partly and hopefully it helps to find the bug.
In case I should test something else just ask.

best regards

**Comment by blizzz** [comment]
There is a fix in https://github.com/nextcloud/server/pull/44184 you might when to check this. This issue is then possibly a dup of https://github.com/nextcloud/server/issues/43919.

**Comment by c-0815** [comment]
I doublechecked and agree with you.  Enforcing password protection has to be enabled to trigger it.

**Comment by c-0815** [comment]
No, I discovered the same Problem in 28.0.3.

**Comment by skjnldsv** [comment]
Yep, fixed in upcoming versions 28.0.4

**Comment by c-0815** [comment]
What is with version 27. Any backport plans?

**Comment by c-0815** [comment]
great!!

**Comment by dea-75** [comment]
> Yep, fixed in upcoming versions 28.0.4

I've tried 28.0.4rc1 and the problem persist....

**Comment by chrizzlibaer** [comment]
Updated to 28.0.4 today and still facing this issue.

Do you need any information i can provide to fix this?
Thank you!

**Comment by c-0815** [comment]
I've teset mit 27.1.8
If one of the options at the "Default share permissions" is activated , it works correctly with "enforce password encryption" enabled. This is my current workaround.
If none of them is activated, I seems that a password is set  in the sharing dialog. But before this bug came into the release, a auto-generated password was shown. I only see ************ in the password field.
If I don't replace this **********  with an own password and hit "save share" the error "Error creating the share: Passwords are enforced for link and mail shares!" is shown again.
So in my opinion if no default permission is set the auto-generated password isn't really created. These ******* are misleading.

@chrizzlibear: Is my workaround also possible in 28.0.4?

**Comment by susnux** [comment]
Fixed with next release:

https://github.com/nextcloud/server/pull/44569
