### ISSUE TITLE
[Bug]: Share with e-mail "File Drop" sets permission to "Custom permissions"

### ISSUE THREAD

**Issue by Gerben-W** [nextcloud/server#45853]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a "File Drop" folder using Share with email, the permissions are set to "Custom permissions"
![Screenshot 2024-06-13 at 11 49 26](https://github.com/nextcloud/server/assets/14327528/9a3a58b8-51b1-41cd-aa12-a2fc9da67100)
![Screenshot 2024-06-13 at 12 01 38](https://github.com/nextcloud/server/assets/14327528/eb7eb751-159a-432a-8521-085313a270a6)

### Steps to reproduce

1. Create a folder
2. Share the folder
3. Type the recepient e-mail in the "Search for share recipients" box
4. Select the "File Drop" option
5. Click "Save share"

### Expected behavior

The permissions on this shared folder should be set to "File Drop" in stead of "Custom permissions"

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "maintenance": false,
        "maintenance_window_start": 1,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "logtimezone": "Europe\/Amsterdam",
        "default_phone_region": "NL",
        "allow_user_to_change_display_name": "false",
        "trashbin_retention_obligation": "auto, 30",
        "loglevel": 0,
        "theme": "",
        "app_install_overwrite": [
            "workflow_script",
            "files_retention"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - cloud_federation_api: 1.12.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_accesscontrol: 1.19.1
  - files_automatedtagging: 1.19.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_retention: 1.18.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - oauth2: 1.17.0
  - ocs_api_viewer: 1.0.6
  - password_policy: 1.19.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - systemtags: 1.19.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_saml: 6.1.3
  - viewer: 2.3.0
  - workflow_script: 1.14.1
  - workflowengine: 2.11.0
Disabled:
  - circles: 29.0.0-dev (installed 27.0.0)
  - circlesdb: 1.8.2 (installed 1.8.2)
  - comments: 1.19.0 (installed 1.17.0)
  - dashboard: 7.9.0 (installed 7.7.0)
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.18.0 (installed 2.16.0)
  - notifications: 2.17.0 (installed 2.15.0)
  - photos: 2.5.0 (installed 2.3.0)
  - related_resources: 1.4.0 (installed 1.2.0)
  - support: 1.12.0 (installed 1.10.0)
  - survey_client: 1.17.0 (installed 1.15.0)
  - suspicious_login: 7.0.0
  - text: 3.10.0 (installed 3.8.0)
  - user_ldap: 1.20.0 (installed 1.19.0)
  - user_status: 1.9.0 (installed 1.7.0)
  - weather_status: 1.9.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by skjnldsv** [comment]
Fixed!

**Comment by Gerben-W** [comment]
> Fixed! (cc @Fenn-CS for safety check)

Where can I find the pull request where the fix has been made?

**Comment by Fenn-CS** [comment]
> Where can I find the pull request where the fix has been made?

File drop is not "Request file" (a "new" and improved file drop).... These changes where done over a series of PRs.

**Comment by Gerben-W** [comment]
There has been a few versions deployed since this ticket was closed, but still not able to create a Folder with "File Drop" without manually changing after sharing with an email address.
When Is this expected to be released?

**Comment by skjnldsv** [comment]
@Gerben-W theoritecally 28-30. Which one did you check?
