### ISSUE TITLE
[Bug]: rename file action is not possible and loads document instead

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#45997]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

rename file action is not possible and loads document instead

### Steps to reproduce

https://github.com/nextcloud/server/assets/87175513/74e71687-733a-4617-93bc-69df21f7bf57

### Expected behavior

rename should be possible and document should not load

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by artonge** [comment]
Fixed by https://github.com/nextcloud/server/pull/45984

**Comment by mehlkopf** [comment]
So is this broken in 28.0.7 or was the fix implemented early enough? Would be a deal-breaker for an update IMHO. Thank you!

**Comment by solracsf** [comment]
Both 29.0.3 and 38.0.7 are affected.

**Comment by mehlkopf** [comment]
Thank you for this information, meaning I will not update. Honestly, I think there is something very very wrong with testing and QA of the Files app. In the last year way too many times crucial features were just broken in new versions, with bugs that should have easily be encountered through standardized testing before even shipping beta versions.

**Comment by rodinux** [comment]
Hello, I still see this issue on a 28.0.7 upgrade... Does it means the fix will be present only on next release 28.0.8 ??

**Comment by blitzdesigner** [comment]
same with me, 28.0.7.
When you repeatedly use the rename function and as soon as the name is highlighted you can move with cursor buttons around and rename it. but clicking with mouse will open the file /folder

**Comment by solracsf** [comment]
Fixed in 28.0.8 / 29.0.4.

https://github.com/nextcloud/server/pull/46019
https://github.com/nextcloud/server/pull/46018
