### ISSUE TITLE
[Bug]: Can't create tags

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#46365]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just tried to create a new tag as normal user on c.nc.com but it failed

### Steps to reproduce

1. Open the right sidebar for a folder
2. got to tags
3. enter a tag name and press enter
4. I get a error "Failed to create tag"

### Expected behavior

tag gets created

Note: After reloading the page, the tags are shown. So it seems that we create them in the background but still a error is triggered somewhere in the process

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by intervisionlord** [comment]
Another related (i guess) problem:

1. Go to files
2. Select "tags" in left menu
3. See only ID's of tags (not names)
4. Unable to add or remove tags
![image](https://github.com/user-attachments/assets/61dd2e9b-0f84-4d41-beea-4ffd3cf204d8)

![image](https://github.com/user-attachments/assets/6bd41900-f0bc-4ef1-9286-0a578b1c8f36)

1. Go to administration settings
2. Go to Flow
3. Try to create tag
4. Filed with tag name clears self
5. Button for create tag is unavailable
![image](https://github.com/user-attachments/assets/e3c4c68b-4db6-4903-8bbb-fe51e2bc2fb8)

**Comment by skjnldsv** [comment]
> Another related (i guess) problem:

Fixed already in latests releases

**Comment by skjnldsv** [comment]
Cannot reproduce the issue anymore

**Comment by intervisionlord** [comment]
> > Another related (i guess) problem:
> 
> Fixed already in latests releases

Still not fixed

**Comment by intervisionlord** [comment]
@szaimen Could you please reopen this case? 

> Another related (i guess) problem:
> 
> 1. Go to files
> 2. Select "tags" in left menu
> 3. See only ID's of tags (not names)
> 4. Unable to add or remove tags
>    ![image](https://private-user-images.githubusercontent.com/3979683/350362477-61dd2e9b-0f84-4d41-beea-4ffd3cf204d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTAxOTEsIm5iZiI6MTcyNzI0OTg5MSwicGF0aCI6Ii8zOTc5NjgzLzM1MDM2MjQ3Ny02MWRkMmU5Yi0wZjg0LTRkNDEtYmVlYS00ZmZkM2NmMjA0ZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMDczODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVlNDQ3ZjYxM2M1MGFlYzI4MjIxYzczMzMwOGYwYWY2ZjUyMzhjNzFkNjJlMWZhYjg5MDQyZmM2MDNkMWNjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3xY4jx1cCDB7bdmUs2tCrvPU5CBtoAnLL3wZ_7-h8jU)
> 
> ![image](https://private-user-images.githubusercontent.com/3979683/350362873-6bd41900-f0bc-4ef1-9286-0a578b1c8f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTAxOTEsIm5iZiI6MTcyNzI0OTg5MSwicGF0aCI6Ii8zOTc5NjgzLzM1MDM2Mjg3My02YmQ0MTkwMC1mMGJjLTRlZjEtOTI4Ni0wYTU3OGIxYzhmMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMDczODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc3NjM0MGYyYzA0MjhkZGQ4MjMxZDZiZDdmOGFjN2QwNWVjZWNiZTgzYjlhMGNjYTNjZDdlMmZlNWFkZjc1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._kSGk506w2pl5F03yer7FFa0PnjbFQL3OwuyyItq_Cs)
> 
> 1. Go to administration settings
> 2. Go to Flow
> 3. Try to create tag
> 4. Filed with tag name clears self
> 5. Button for create tag is unavailable
>    ![image](https://private-user-images.githubusercontent.com/3979683/350363624-e3c4c68b-4db6-4903-8bbb-fe51e2bc2fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTAxOTEsIm5iZiI6MTcyNzI0OTg5MSwicGF0aCI6Ii8zOTc5NjgzLzM1MDM2MzYyNC1lM2M0YzY4Yi00ZGI2LTQ5MDMtOGJiYi1mZTUxZTJiYzJmYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMDczODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg5ZmZiZTUwNWIxZjFhMjYzZTdjMTZjODBkYjQ1N2YzY2IzYjBjNWRjMTljNTE3MzRjZDM5YWE1MDQ4NDAxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.M8Yjg-8J2QJ2Wzqqzo96n7hrrOIM8vuzsKg5FLxww1k)

This behavior still exists exactly as described without any changes

**Comment by intervisionlord** [comment]
I can't even delete tags - there is no such option

**Comment by skjnldsv** [comment]
@intervisionlord which version are you using ?

**Comment by intervisionlord** [comment]
> [@intervisionlord](https://github.com/intervisionlord) which version are you using ?

29.0.7
Problem was solved in #48761
