### ISSUE TITLE
[Bug]: App permission for groups - broken group list

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/server#46634]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unable to select group wich can use application
![image](https://github.com/user-attachments/assets/3f091ebc-61f0-4aea-8246-8426ec1abdad)

### Steps to reproduce

1. Go to app wich supports group permissions
2. Set "limit to groups"
3. Click on selector
4. No groups suggested
5. Start to fill this field
6. Relevant group appears
7. Select it
8. Selector does not filled by this group
![image](https://github.com/user-attachments/assets/d202da8b-df4c-48c3-b29b-5c94d3ecff2d)
![image](https://github.com/user-attachments/assets/cfeeef81-ea35-4268-8f20-dcd73f094560)

### Expected behavior

Correct suggestions in selector
Correct adding to selector

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Reproduced. Visually it then breaks that setting for other apps one clicks through.

On the other hand, it seems to actually set the parameter (after reloading the page).

**Comment by intervisionlord** [comment]
> Reproduced. Thanks for reporting.
> 
> Visually it then breaks that setting for other apps one clicks through.
> 
> On the other hand, it seems to actually set the parameter (after reloading the page).

Yes, technicaly the functionality works, this bug affects only appearence (visual part) (sry for my english)

**Comment by joshtrichards** [comment]
@yannicklescure No one is currently. I was just sitting down to bring together a couple interrelated matters:

- this Issue (#46634)
- #39322 
- #20685

I suspect these can all be solved at at once.

Code is here:

https://github.com/nextcloud/server/blob/063d4df47899dc626e025ec1760bccf356f16d9d/apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue#L22

Potentially of note is a similar use case which seems to work reasonably well:

https://github.com/nextcloud/server/blob/063d4df47899dc626e025ec1760bccf356f16d9d/apps/settings/src/components/AdminTwoFactor.vue#L20

It can be found under *Admin->Security* in the UI..

**Comment by yannicklescure** [comment]
@joshtrichards Thank you. I setup a dev environnement and I'll try to give it a shot this week. :)

**Comment by yannicklescure** [comment]
@joshtrichards Sorry to bother in that feed. I successfully fixed the code, however I can't manage to push my branch. Could you help me?

**Comment by yannicklescure** [comment]
@joshtrichards Here's the fix https://github.com/nextcloud/server/pull/48504 :)

**Comment by punkyard** [comment]
hi
in NC 30.0.4 AiO 10.2.0 the issue remains:
- "Limit to group" is unchecked until reload
- can't see groups in list
- with auto-completion, adding a group takes a reload to display the group
- only one group can be added at a time
- renamed groups appear with their initial names

**Comment by sebix** [comment]
I see this issue also in version 32.0.0

**Comment by intervisionlord** [comment]
Yes, the problem is still not solved since it appeared. And still present version by version

**Comment by solracsf** [comment]
This is a pain :)
In the meanwhile, one can manage it trough the CLI:

`occ app:enable -g group1 group2 <appId>`

**Comment by pringelmann** [comment]
I'm working on this, will open PR shortly

**Comment by pringelmann** [comment]
Seems this has already been fixed: https://github.com/nextcloud/server/commit/de3a9ae3273df7cce1cdfa4ee4107ca4f11b7b92

**Comment by solracsf** [comment]
Confirm fixed on v31 and v32
