### ISSUE TITLE
[Bug]: "Update all" button in app store (/settings/apps/updates) has no effect

### ISSUE THREAD

**Issue by leegarrett** [nextcloud/server#49734]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "update all" button doesn't seem to have any effect when clicking it, despite there being three apps with available updates.

### Steps to reproduce

1. Browse to `/settings/apps/updates`. You are greeted with this part of the web page:
![Image](https://github.com/user-attachments/assets/9e6b3048-d055-407b-9a2a-89b232d33809)
2. Click on "update all"
3. This doesn not have any effect. The firefox debug console triggers this exception when clicking the button above:
```
Uncaught (in promise) TypeError: this.update is not a function
    updateAll AppList.vue:321
    i index.js:24
    s index.js:24
    promise callback*98405/w/i/</< index.js:40
    i index.js:58
    i index.js:57
    updateAll AppList.vue:320
    updateAll AppList.vue:320
    VueJS 4
    click NcButton.mjs:232
    VueJS 33
3 AppList.vue:321
```

### Expected behavior

All apps are updated.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "appcodechecker": true,
        "bulkupload.enabled": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbtype": "pgsql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "filelocking.enabled": true,
        "htaccess.RewriteBase": "\/",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logfile": "",
        "loglevel": 2,
        "log_type": "syslog",
        "maintenance": false,
        "maintenance_window_start": 1,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/nextcloud.rocketjump.eu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 1
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "syslog_tag": "nextcloud",
        "theme": "",
        "trusted_domains": [
            "nextcloud.rocketjump.eu"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "version": "30.0.2.2",
        "updater.release.channel": "stable",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.20.0
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.6
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.2
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - lookup_server_connector: 1.18.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - polls: 7.2.5
  - previewgenerator: 5.7.0
  - provisioning_api: 1.20.0
  - recognize: 8.1.1
  - related_resources: 1.5.0
  - richdocuments: 8.5.2
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.2
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - activity: 3.0.0 (installed 2.11.0)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 1.8.0)
  - files_external: 1.22.0
  - firstrunwizard: 3.0.0 (installed 2.7.0)
  - logreader: 3.0.0 (installed 2.8.0)
  - maps: 1.5.0 (installed 1.5.0)
  - nextcloud_announcements: 2.0.0 (installed 1.7.0)
  - photos~: 2.0.0
  - privacy: 2.0.0 (installed 1.2.0)
  - recommendations: 3.0.0 (installed 0.6.0)
  - serverinfo: 2.0.0 (installed 1.8.0)
  - support: 2.0.0 (installed 1.1.0)
  - survey_client: 2.0.0 (installed 1.6.0)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
No logs are triggered when pressing the button, as it does not trigger a HTTP request.
```

**Comment by LM-vb** [comment]
duplicate of #49144

**Comment by leegarrett** [comment]
It's a bit of a sidetrack, but I like to point out that the search function at https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug does not show closed bugs, and #49144 (and duplicates) all got closed.

Might make sense to change the template to include already closed bugs, if the workflow here is to close bugs as soon as they're fixed in devel (and not in the latest stable channel (30.0.2).

**Comment by solracsf** [comment]
> Might make sense to change the template to include already closed bugs

https://github.com/nextcloud/server/pull/49382 ;-)

**Comment by leolivier** [comment]
Hi
This bug is not fully fixed I'm afraid: when there are multiple applications to update like this:
![Image](https://github.com/user-attachments/assets/931b8709-1005-479b-8b91-e93fc426f19d)
Only one them is updated when you click on "update all", and the remaining one(s) are left un updated:
![Image](https://github.com/user-attachments/assets/cee4365d-7765-4484-a042-e82c2e77c99e)

I experienced this twice already... I was unsure the first time so I paid attention the second one and I confirm that 100%
