### ISSUE TITLE
[Bug]: NC31 logs "Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.xx seconds to generate" on every page refresh.

### ISSUE THREAD

**Issue by ghtm2** [nextcloud/server#51621]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Installed NC31, the logs are getting flooded with this on every page refresh:
```
{"reqId":"j8pdPAqNLGYF8f4854Dh","level":3,"time":"2025-03-21T08:24:01+01:00","remoteAddr":"::ffff:93.237.197.xx","user":"admin","app":"no app in context","method":"GET","url":"/apps/dashboard/","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 1.09 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","version":"31.0.2.1","data":[]}
```

### Steps to reproduce

1. Install NC31
2. Choose to install the recommended apps when asked after login
3. Look at the log

### Expected behavior

No message in the log.

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "forbidden_filenames": [
            ".htaccess",
            ".DS_STORE",
            "._.DS_STORE"
        ],
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "logfile": "\/var\/log\/nextcloud\/cloud.log",
        "logfile_audit": "\/var\/log\/nextcloud\/audit.log",
        "logtimezone": "Europe\/Berlin",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "maintenance": false,
        "maintenance_window_start": 1,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.collation": "utf8mb4_german2_ci",
        "mysql.utf8mb4": true,
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloudtest2025",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "s3-eu-central-2.ionoscloud.com",
                "port": 443,
                "use_ssl": true,
                "region": "eu-central-2",
                "use_path_style": false
            }
        },
        "overwrite.cli.url": "https:\/\/mydomain.de",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 11
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "skeletondirectory": "",
        "templatedirectory": "",
        "trusted_domains": [
            "mydomain.de"
        ],
        "updatechecker": false,
        "upgrade.disable-web": true,
        "loglevel": 2,
        "version": "31.0.2.1"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - calendar: 5.2.0
  - circles: 31.0.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contacts: 7.0.4
  - contactsinteraction: 1.12.0
  - dashboard: 7.11.0
  - dav: 1.33.0
  - federatedfilesharing: 1.21.0
  - federation: 1.21.0
  - files: 2.3.1
  - files_downloadlimit: 4.0.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - mail: 4.3.1
  - nextcloud_announcements: 3.0.0
  - notes: 4.11.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - photos: 4.0.0-dev.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - richdocuments: 8.6.3
  - richdocumentscode: 24.4.1302
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - spreed: 21.0.1
  - support: 3.0.0
  - survey_client: 3.0.0
  - systemtags: 1.21.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - updatenotification: 1.21.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - weather_status: 1.11.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - admin_audit: 1.21.0
  - encryption: 2.19.0
  - files_external: 1.23.0
  - suspicious_login: 9.0.1
  - twofactor_nextcloud_notification: 5.0.0
  - twofactor_totp: 13.0.0-dev.0
  - user_ldap: 1.22.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"j8pdPAqNLGYF8f4854Dh","level":3,"time":"2025-03-21T08:24:01+01:00","remoteAddr":"::ffff:93.237.197.xx","user":"admin","app":"no app in context","method":"GET","url":"/apps/dashboard/","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 1.09 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","version":"31.0.2.1","data":[]}
{"reqId":"fNT3Uxzk3oXE5wr1H64O","level":2,"time":"2025-03-21T08:24:21+01:00","remoteAddr":"::ffff:93.237.197.xx","user":false,"app":"no app in context","method":"GET","url":"/login?clear=1","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.4 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","version":"31.0.2.1","data":[]}
{"reqId":"tndGZohJb9ecaa66xGkJ","level":2,"time":"2025-03-21T08:25:18+01:00","remoteAddr":"::ffff:23.27.145.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.42 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux i686; rv:109.0) Gecko/20100101 Firefox/120.0","version":"31.0.2.1","data":[]}
{"reqId":"8ZSZLU4kbvOFnDjIBGyA","level":2,"time":"2025-03-21T08:25:21+01:00","remoteAddr":"::ffff:93.237.197.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.41 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","version":"31.0.2.1","data":[]}
{"reqId":"USgy4LxaqXLBZwQSHX4N","level":2,"time":"2025-03-21T08:26:04+01:00","remoteAddr":"::ffff:44.200.38.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.46 seconds to generate.","userAgent":"Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)","version":"31.0.2.1","data":[]}
{"reqId":"kvyeyshBBeVM4oslwmbH","level":2,"time":"2025-03-21T08:26:58+01:00","remoteAddr":"::ffff:185.213.155.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.44 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36","version":"31.0.2.1","data":[]}
{"reqId":"ZwNYz8OfnW0drW7SGvwN","level":2,"time":"2025-03-21T08:27:03+01:00","remoteAddr":"::ffff:185.213.155.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.48 seconds to generate.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36","version":"31.0.2.1","data":[]}
{"reqId":"xI9sOhgbylZNrszy2346","level":2,"time":"2025-03-21T08:27:13+01:00","remoteAddr":"::ffff:205.169.39.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.51 seconds to generate.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.5938.132 Safari/537.36","version":"31.0.2.1","data":[]}
{"reqId":"B7Sefzf5615uAIDZu1Ms","level":2,"time":"2025-03-21T08:28:52+01:00","remoteAddr":"::ffff:91.84.87.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.4 seconds to generate.","userAgent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36","version":"31.0.2.1","data":[]}
{"reqId":"mCXbPo9pFO4Z6rGCdebX","level":2,"time":"2025-03-21T08:30:43+01:00","remoteAddr":"::ffff:35.89.115.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.55 seconds to generate.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36","version":"31.0.2.1","data":[]}
{"reqId":"t9fmuCWXp2F69lg3q7aQ","level":2,"time":"2025-03-21T08:30:43+01:00","remoteAddr":"::ffff:35.89.115.xx","user":false,"app":"no app in context","method":"GET","url":"/login","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.55 seconds to generate.","userAgent":"Mozilla/5.0 (Linux; Android 8.0.0; SM-G965U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36","version":"31.0.2.1","data":[]}
```

**Comment by mhzawadi** [comment]
Also seeing this log entry on every page load, but with very long times

Nextcloud Server version
31.0.2

Operating system
Debian

PHP engine version
PHP 8.3

Web server
Nginx

Database engine version
10.11.11-MariaDB-0+deb12u1 - Debian 12

```
{"reqId":"uVY3M8Dcu96NHP0qcdSo","level":4,"time":"2025-03-21 22:01:30","remoteAddr":"HOMEIP","user":"USER","app":"no app in context","method":"GET","url":"/apps/deck/","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 3.0299999999999998 seconds to generate.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 OPR/116.0.0.0","version":"31.0.2.1","data":[]}
```

**Comment by aptiko** [comment]
I have the same issue as @mhzawadi with 30.0.7. The times are longer (such as 3s), and it's not a warning, it's usually "fatal" (note that the servers are very slow). I haven't heard any screams from the users however. Maybe it should be downgraded to warning even for the longer times.

There's the same issue in a forum thread, but without any response: https://help.nextcloud.com/t/capabilities-of-oca-cloudfederationapi/219467

**Comment by joshtrichards** [comment]
To any of you reporting this:

> Are you using Federations / remote shares at all?

**Comment by mhzawadi** [comment]
> To any of you reporting this:
> 
> > Are you using Federations / remote shares at all?
> 
> 

None, deleted all remote server trusts

**Comment by aptiko** [comment]
No federations or remote shares here.

**Comment by DantesPop** [comment]
We are experiencing the same issue, no federations or remote shares. 
[Nextcloud Hub 10](https://nextcloud.com/) (31.0.2)
Ubuntu 24.04.2 LTS
PHP 8.3.6
nginx/1.27.3

**Comment by susnux** [comment]
Fixed with https://github.com/nextcloud/server/issues/51621

Will be in 31.0.4 scheduled for May.

**Comment by DantesPop** [comment]
> Fixed with [#51946](https://github.com/nextcloud/server/pull/51946)
> 
> Will be in 31.0.4 scheduled for May.

We have upgraded to 31.0.4, this bug has not been corrected for our instance. 

Version
[Nextcloud Hub 10](https://nextcloud.com/) (31.0.4)

ex:
[no app in context] Error: Capabilities of OCA\CloudFederationAPI\Capabilities took 1.12 seconds to generate.
	GET /
	from 167.71.133.225 by ? at Apr 21, 2025, 3:39:55 PM

**Comment by susnux** [comment]
Due to the out of band release the version number doed not match.

Meaning it is still scheduled for May but version will be 31.0.5.

**Comment by PeteKersker** [comment]
Update: I'm really trying to run Nextcloud as an Intranet without federation. I changed my federation settings to match this vision and the errors dropped down to a few times a day. I think, perhaps, this is working as designed.

**Comment by KrzysztofMaciejewski** [comment]
bug still in in 31.0.6

![Image](https://github.com/user-attachments/assets/0eec6e2c-cc54-4c2e-b65d-fda8c49059ad)

**Comment by susnux** [comment]
> Is there anything I can check/do on my end to help?

You can try

```sh
occ config:app:set --value false --type boolean --lazy core ocm_signed_request_disabled
```

**Comment by KrzysztofMaciejewski** [comment]
> > Is there anything I can check/do on my end to help?
> 
> You can try
> 
> occ config:app:set --value false --type boolean --lazy core ocm_signed_request_disabled

Thanks - done

What doei it mean in human form ? :)

**Comment by susnux** [comment]
> What doei it mean in human form ? :)

It disables the signed OCM requests - so no keys are generated.
My guess is that your machine is not really fast generating cryptographic keys.

**Comment by lssong99** [comment]
Any update on this? My 31.0.7 server also have this issue. Again, no federation sharing capabilities.

**Comment by susnux** [comment]
Can those who are still affected please share on which hardware you run your server?
Because this should be very cheap on most hardware - except maybe rasperry pi.

**Comment by susnux** [comment]
cc @ArtificialOwl for the CloudFederationAPI Capabilities.
This seems to be caused by the added expensive signing stuff

**Comment by PeteKersker** [comment]
We're on a VPS with 12 cores and 47 GB of ram. I'm not sure if it matters, but we authenticate via IMAP with our own email server, which is a separate VPS.

**Comment by as598466** [comment]
Hello!
For several months now, same problem. These constant error messages, even on a fresh installation. VPS: 4 vCores, 8 GB RAM, main storage on S3.
(Debian 12) MariaDB + Nginx + PHP 8.3-FPM.

<img width="2095" height="831" alt="Image" src="https://github.com/user-attachments/assets/8092a084-2869-480a-a1a1-8fa7cbfa9f15" />

**Comment by ThaDaVos** [comment]
I am having the same error message, but instead of `OCA\\CloudFederationAPI\\Capabilities` it's `OCA\\GroupFolders\\AppInfo\\Capabilities` and took 20+ seconds - already created an issue there https://github.com/nextcloud/groupfolders/issues/3915

EDIT: Using `occ config:app:set --value false --type boolean --lazy core ocm_signed_request_disabled` doesn't get rid of it sadly

**Comment by lssong99** [comment]
> Can those who are still affected please share on which hardware you run your server? Because this should be very cheap on most hardware - except maybe rasperry pi.

I am on Synogoly DS720+ with a INTEL Celeron J4125 CPU, 10GB RAM. I believe this is pretty common HW for a home lab and much better than a RPi.

**Comment by susnux** [comment]
Hm I suspected asymmetric key generation to be the problem, but with your hardware this seems to be not the case.
So lets pass it to @ArtificialOwl as the author of the signing feature.

**Comment by ArtificialOwl** [comment]
> cc [@ArtificialOwl](https://github.com/ArtificialOwl) for the CloudFederationAPI Capabilities. This seems to be caused by the added expensive signing stuff

just checked. from my point of view, once the key pair is generated, it should not takes that much to run ...

**Comment by PeteKersker** [comment]
I don't know if it matters, but my main storage is on S3 like @as598466 mentioned.
I'm also on (Ubuntu 22.04) MariaDB + Apache + PHP 8.3-FPM

Here's a snapshot from my logs yesterday, in case it helps:


08/10/25 07:52 PM | Fatal | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 7.02 seconds to generate.
-- | -- | -- | --
08/10/25 07:52 PM | Fatal | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 7.02 seconds to generate.
08/10/25 07:52 PM | Error | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 1.15 seconds to generate.
08/10/25 07:52 PM | Error | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 1.15 seconds to generate.
08/10/25 02:15 PM | Error | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 0.83 seconds to generate.
08/10/25 02:15 PM | Error | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 0.83 seconds to generate.
08/10/25 08:29 AM | Error | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 0.91 seconds to generate.
08/10/25 08:29 AM | Error | no app in context | Capabilities of OCA\CloudFederationAPI\Capabilities took 0.91 seconds to generate.

**Comment by ArtificialOwl** [comment]
The key pairs are managed by [IdentityProofManager](https://github.com/nextcloud/server/blob/520d8beaf54842795fa1277b1831635545d2b035/lib/private/Security/IdentityProof/Manager.php#L103) which store the data in 2 files (public/private) within appdata. On s3 it mights be enough to trigger the warning.

I am curious on the original request that still pops those warning in logs since 31.0.4, but https://github.com/nextcloud/server/pull/51946 should have been enough. Are they still generated when reaching `/login` like it was previously stated in the original message of this thread.

Now, the key pair should only be necessary when requesting the `/ocm-provider/` endpoint, and not as a global capabilities. 
I will move things around.

**Comment by lssong99** [comment]
Not sure if it would help, but my log are filled with those messages. Detailed copy as:

{"reqId":"mjOgFMrQukbXOR0Yh0H6","level":4,"time":"2025-08-12T01:25:27+00:00","remoteAddr":"111.222.111.222","user":"myusername","app":"no app in context","method":"GET","url":"/ocs/v1.php/cloud/capabilities?format=json","message":"Capabilities of OCA\\CloudFederationAPI\\Capabilities took 2.15 seconds to generate.","userAgent":"Mozilla/5.0 (Windows) mirall/3.16.83rc3 (build 20250808) (Nextcloud, windows-10.0.26200 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"31.0.7.1","clientReqId":"35xxxx9121-exx4-4exxx-axxxc-15xxxxxxdc0c","data":[],"id":"689xxxxxxxxbe"}

**Comment by susnux** [comment]
@ArtificialOwl https://github.com/nextcloud/server/pull/51946 only fixed it for the webui. All clients will still request this capability.

**Comment by ArtificialOwl** [comment]
And client wont need the keypair .. maybe the information that the instance will try to sign ocm request. 

However, there is some needed task in here:

- do not use a global `IOCMProvider` in `OCMDiscoveryService`
- manage the generation of the `IOCMProvider` for the local instance outside of `OCA\CloudFederationAPI\Capabilities`
- rewrite the code logic behind `ResourceTypeRegisterEvent`
- ~~deprecate the `ResourceTypeRegisterEvent` and replace with 2 events: one for capabilities (light process), one for the /ocm/ endpoint (heavier process)~~

**Comment by ArtificialOwl** [comment]
@susnux https://github.com/nextcloud/server/pull/54385

**Comment by as598466** [comment]
Since the backport, the issue seems to have disappeared! The logs are clean. Thanks @ArtificialOwl !

**Comment by ThaDaVos** [comment]
Installed 31.0.8 but still seeing the issue in `GroupFolders`:
```
OCA\\GroupFolders\\AppInfo\\Capabilities took 34.09 seconds to generate.
```
https://github.com/nextcloud/groupfolders/issues/3915

**Comment by susnux** [comment]
> Installed 31.0.8 but still seeing the issue in GroupFolders:

Completely unrelated. This is a generic log message that some apps capabilities loaded longer than they should.
So unrelated to this issue and might be reported over there.

**Comment by ThaDaVos** [comment]
> > Installed 31.0.8 but still seeing the issue in GroupFolders:
> 
> Completely unrelated. This is a generic log message that some apps capabilities loaded longer than they should. So unrelated to this issue and might be reported over there.

I reported it there and sadly no activity - hence why I asked it here as the issue seems similar - but thanks for marking my question off topic and I'll wait for response there...

**Comment by PeteKersker** [comment]
I installed 31.0.9 last Thursday and continue with the same issue each day since. This brings up two questions:
1) Was 31.0.9 the correct version to see these changes?
2) Should I be changing anything in my configuration to take advantage of these changes?
Thanks in advance.

**Comment by ThaDaVos** [comment]
@PeteKersker  - quick question - do you also noticed the issue only when logged in with an Admin account?
I notice my whole instance web ui being slow (mine is GroupFolders) but only when the account is an Admin Account

**Comment by PeteKersker** [comment]
> [@PeteKersker](https://github.com/PeteKersker) - quick question - do you also noticed the issue only when logged in with an Admin account? I notice my whole instance web ui being slow (mine is GroupFolders) but only when the account is an Admin Account

I am in a "beta testing" environment with only a few user accounts besides myself. I'm seeing equal log lines between my regular user and admin accounts. I don't notice a difference. (I also use GroupFolders/TeamFolders a lot.)
