### ISSUE TITLE
[Bug]: Can't authenticate when Nextcloud want to confirm password

### ISSUE THREAD

**Issue by Bevito** [nextcloud/server#51637]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi, 
The present issue is similar to #49829  (wich is solved).
A lot of people still have issue with the input box that want to confirm your password.
On our Nextcloud instance, the issue is still present.

I'm very sorry If I broke some rules, about creating a new issue for some issues already reported.

If I can help to resolve the issue, please, let me know.

Best regards.

### Steps to reproduce

1. Log in to Nextcloud with LDAP account
2. Go to personnal parameters
3. Input a new password in Global Credentials area
4. Save
5. Input your password to confirm

### Expected behavior

When Nextcloud asked for password confirmation, the password seems to be wrong.
Nextcloud failed to check password even if your password is correctly input.
Nextcloud send an XHR post to apps/files_external/globalcredentials and Nextcloud report an HTTP error 403.

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 32.0.1 to 32.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "31.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maxZipInputSize": 1073741824,
        "allowZipDownload": true,
        "theme": "",
        "overwrite.cli.url": "https:\/\/cloud.iut-orsay.fr",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "maintenance_window_start": 2,
        "default_language": "fr",
        "default_phone_region": "FR",
        "defaultapp": "files,dashboard",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "enable_previews": false,
        "trusted_domains": [
            "cloud.iut-orsay.fr"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0,
            "timeout": 0
        },
        "onlyoffice": {
            "jwt_secret": "***REMOVED SENSITIVE VALUE***",
            "jwt_header": "AuthorizationJwt"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": "60",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "printer"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - admin_audit: 1.21.0
  - announcementcenter: 7.1.0
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - circles: 31.0.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contactsinteraction: 1.12.0
  - dashboard: 7.11.0
  - dav: 1.33.0
  - federatedfilesharing: 1.21.0
  - federation: 1.21.0
  - files: 2.3.1
  - files_downloadlimit: 4.0.0
  - files_external: 1.23.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - groupfolders: 19.0.4
  - lookup_server_connector: 1.19.0
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - onlyoffice: 9.7.0
  - password_policy: 3.0.0
  - photos: 4.0.0-dev.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - support: 3.0.0
  - survey_client: 3.0.0
  - suspicious_login: 9.0.1
  - systemtags: 1.21.1
  - tasks: 0.16.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - twofactor_totp: 13.0.0-dev.0
  - updatenotification: 1.21.0
  - user_ldap: 1.22.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - weather_status: 1.11.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - drawio: 3.0.3 (installed 3.0.3)
  - encryption: 2.19.0
  - logreader: 4.0.0 (installed 2.14.0)
  - twofactor_nextcloud_notification: 5.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
No specific logs found in nextcloud.log
```

### Additional info

I checked and double checked the password before confirming it : 

![Image](https://github.com/user-attachments/assets/783e60df-f74b-4133-932b-315d24a432b9)

The firefox console when submitting the password. The error seems to be normal.
For some reason, Nextcloud can't verify the password.
I can log in with my account, but I can't authenticate when changing global credentials password.

![Image](https://github.com/user-attachments/assets/a4c994aa-40b3-4b25-9246-5d4810732dd9)

**Comment by skjnldsv** [comment]
Hey, thanks for the additional report :)
Can you describe your setup?
Do you have a reverse proxy? Are you using nginx or apache ?

**Comment by Bevito** [comment]
Hi @skjnldsv, Thanks for your answer.

Nextcloud is installed on a DELL PowerEdge physical server, with Debian Bookworm (12.10 at the moment).
We have Apache2 as a web server and php8.2-fpm for PHP. 
There is no reverse proxy.
Nextcloud is configured with MariaDB, for the database, and LDAP (OpenLDAP) for users authentications.
Redis is installed and configured for memcache distributed and locking and memcache local is configured with APCu.

I don't know what Nextcloud is trying to do, when the input box want to confirm the password. 
I guess, It does not do a connection like the login page ? 
There is a lot of LDAP traffic, so It's kind of difficult to check what is going on.

If you need any others informations, please let me know.

**Comment by v3DJG6GL** [comment]
I have the same problem with OpenID Connect (https://github.com/pulsejet/nextcloud-oidc-login):
Previously, until about 30.0.4, the password popup also appeared from time to time when changing some admin settings. I could then log out and log in again, which made the password popup disappear for a while.
At the moment, when changing some _External Storage_ settings, the password popup always appears, even if I have just logged in again.
Entering the password obviously fails because my OpenID Connect provider manages my passwords.

- Nextcloud: v31.0.2
- Nextcloud OIDC Login: v3.2.2
- Reverse Proxy: Traefik: v3.3.4
- OpenID Connect Provider: Authelia: v4.39.1

**Comment by skjnldsv** [comment]
Thanks for both of your answers.
@Bevito can you confirm you have apache's `mod_env` enabled ?
@v3DJG6GL you also use apache ?

**Comment by cmdrscotty** [comment]
I am also experiencing this issue (30.0.8) can no longer add or modify external storage because it keeps requiring me to reauthenticate for any admin changes (despite already being logged in as admin)

(Minor note, upgrade path to next cloud 31 only shows up as a nightly release and not a stable release via update manager)

**Comment by gregecslo** [comment]
I have nginx, reverse proxy and LDAP auth with MFA plugin.
Also not working.
Nextcloud 31.0.2

**Comment by v3DJG6GL** [comment]
> [@v3DJG6GL](https://github.com/v3DJG6GL) you also use apache ?

No, I use NGINX.

**Comment by skjnldsv** [comment]
Seems like everyone here is using ldap though, no?

**Comment by v3DJG6GL** [comment]
> Seems like everyone here is using ldap though, no?

No, I'm using OIDC (https://github.com/pulsejet/nextcloud-oidc-login) for authentication.

**Comment by skjnldsv** [comment]
Dammit 😅 
I'll keep diving further 👍

**Comment by skjnldsv** [comment]
Okay, as I cannot reproduce, i'll have to ask you some debugging:
Here is a patch to apply to your server

```diff
+++ b/lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php
@@ -82,7 +82,7 @@ class PasswordConfirmationMiddleware extends Middleware {
                        [, $password] = explode(':', base64_decode(substr($authHeader, 6)), 2);
                        $loginResult = $this->userManager->checkPassword($user->getUid(), $password);
                        if ($loginResult === false) {
-                               throw new NotConfirmedException();
+                               throw new \Exception('Password confirmation failed: ' . $authHeader . ' ' . $password);
                        }
 
                        $this->session->set('last-password-confirm', $this->timeFactory->getTime());
```

It will display in your logs the auth header, which should look something like `HJc25bfGERG0v5=`, followed by your password.
Do NOT copy/paste it here, but please do check that it's properly retrieved and that your password is indeed correct.

The only issue I came close to this is where `mod_env` was disabled and the authorization header was not forwarded to the backend. So the controller was always receiving an empty password and could not check if it was the right one.

So I need to check again if this is a similar case on your setups.

**Comment by Bevito** [comment]
Hi @skjnldsv, I will test this this morning.
If you need, I can create a local, or an LDAP account.

Thanks a lot for your time, and all the help.

**Comment by Bevito** [comment]
I applied the patch : thanks.

When I try to change my global credentials password : 

![Image](https://github.com/user-attachments/assets/2e50d785-d5ba-4fb8-a1e9-9fa2f84290bf)

The password on the "auth: Object" line is correct.
The password on the "data" line is correct too (it is just a test to see if I can save it to global credentials)

I get an HTTP error 500 this time : 

![Image](https://github.com/user-attachments/assets/97020f52-7dd5-4203-9afe-1d692e68c636)

Here is the log : 

{"reqId":"T2AUsk0AGI1GsVw50ncz","level":3,"time":"2025-03-28T09:16:18+00:00","remoteAddr":"88.165.110.104","user":"42de26f0-dd0b-1034-8d5d-fbe9e42d9fc5","app":"index","method":"POST","url":"/apps/files_external/globalcredentials","message":"Password confirmation failed: Basic NDJkZTI2ZjAtZGQwYi0xMDM0LThkNWQtZmJlOWU0MmQ5ZmM1OkQwdWJsM0g0cmszbiE= xxxxxxxxxxx","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"31.0.2.1","exception":{"Exception":"Exception","Message":"Password confirmation failed: Basic NDJkZTI2ZjAtZGQwYi0xMDM0LThkNWQtZmJlOWU0MmQ5ZmM1OkQwdWJsM0g0cmszbiE= xxxxxxxxxx","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":73,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\PasswordConfirmationMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":106,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":307,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1025,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php","Line":85,"message":"Password confirmation failed: Basic NDJkZTI2ZjAtZGQwYi0xMDM0LThkNWQtZmJlOWU0MmQ5ZmM1OkQwdWJsM0g0cmszbiE= xxxxxxxx","exception":{},"CustomMessage":"Password confirmation failed: Basic NDJkZTI2ZjAtZGQwYi0xMDM0LThkNWQtZmJlOWU0MmQ5ZmM1OkQwdWJsM0g0cmszbiE= xxxxxxxxxx"}}

I can confirm that my password is indeed, correct in the log.

**Comment by v3DJG6GL** [comment]
> Okay, as I cannot reproduce, i'll have to ask you some debugging:
> Here is a patch to apply to your server. You can directly edit the `lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php` file, around line 82.

Should I also try this patch with my OIDC setup?
Because with my situation, ideally there should be no password prompt appear at all, since - AFAIK - Nextcloud cannot know my OIDC login-based password anyway?
Earlier, until approx. v30.0.4, the password prompt appeared only if the admin user was logged in a longer time without re-authenticating.  I then had to logout and login again which seemed to reset this counter. Although this still was a workaround, I at least could overcome the password prompt.
But currently, I cannot bypass the password prompt in any way...

**Comment by skjnldsv** [comment]
> Because with my situation, ideally there should be no password prompt appear at all, since - AFAIK - Nextcloud cannot know my OIDC login-based password anyway?

Nextcloud can still check if the password you entered is valid.
As a security measure we ask you to confirm sensitive actions. That's why I provided the patch to ensure the password you entered in the prompt is properly understood by Nextcloud security middleware.

Feel free to apply the patch too, but only to check the logs on your side and see if you do recognise your password.
⚠ Do not paste the log here 🙏

**Comment by skjnldsv** [comment]
@artonge something is weird here from the PasswordConfirmationMiddleware.
The password is properly retrieved from the backend, so it's not a header issue.

**Comment by v3DJG6GL** [comment]
> Nextcloud can still check if the password you entered is valid.

How should that be possible? I don't think that is how OIDC works:
All that is managed by my OIDC provider (Authelia): Nextcloud should only receive an authentication token from my OIDC provider if login/authentication is successful.
It wasn't possible back then (v30.0.4) when I was able to bypass the password by logging out and login again: If I entered my OIDC password into that password prompt, it was (as expected) always wrong.

**Comment by skjnldsv** [comment]
@v3DJG6GL I'm lacking the knowledge then :)

**Comment by skjnldsv** [comment]
@v3DJG6GL OIDC cannot validate, you're 100% correct, I asked the engineers in charge to enlight me 💡 
We're investigating, your issue might slightly differ from this thread :)

**Comment by skjnldsv** [comment]
@v3DJG6GL can you also confirm you're facing a 403 when confirming your password?
If not, what error are you experiencing ?

**Comment by v3DJG6GL** [comment]
> [@v3DJG6GL](https://github.com/v3DJG6GL) OIDC cannot validate, you're 100% correct, I asked the engineers in charge to enlight me 💡 We're investigating, your issue might slightly differ from this thread :)

@skjnldsv alright, thanks for the confirmation! :)


> [@v3DJG6GL](https://github.com/v3DJG6GL) can you also confirm you're facing a 403 when confirming your password? If not, what error are you experiencing ?

Yes, I get a 403 when trying to authenticate.

**Comment by v3DJG6GL** [comment]
@skjnldsv 
```
window.backendAllowsPasswordConfirmation
true 
```

**Comment by skjnldsv** [comment]
> ```
> window.backendAllowsPasswordConfirmation
> true 
> ```

@julien-nc @artonge here is the oidc issue!
It's supposed to be false
https://github.com/nextcloud/server/blob/f758f565d4da004ebef97350365a066eee5267fe/lib/private/Template/JSConfigHelper.php#L68-L69

**Comment by Bevito** [comment]
Dear @skjnldsv 

I was wandering If the issue can be mod_env and php-fpm default configuration ? 

In `/etc/php/8.2/fpm/pool.d/www.conf`

`; Clear environment in FPM workers
; Prevents arbitrary environment variables from reaching FPM worker processes
; by clearing the environment in workers before env vars specified in this
; pool configuration are added.
; Setting to "no" will make all environment variables available to PHP code
; via getenv(), $_ENV and $_SERVER.
; Default Value: yes
;clear_env = no`

**Comment by skjnldsv** [comment]
@Bevito the test you did before show that your configuration is correct and Nextcloud is able to receive your password when entered :)
I'm still puzzled on why the password check is wrong though 🤔

**Comment by Bevito** [comment]
Maybe, it's an LDAP password scheme issue ? This is strange, because the login page works.
Actually, we use "{CRYPT}$6$rounds=50000"

**Comment by skjnldsv** [comment]
@Bevito on your nextcloud.log you should see "login fail" error when validating the confirm password dialog, do you see it?
Do you have any related failure in your ldap server logs maybe?

**Comment by Bevito** [comment]
Indeed, I have a "Login Failed" error message : 

{"reqId":"xxxxxxxxxxxxxxxxxxxxxxx","level":2,"time":"2025-03-30T12:58:17+00:00","remoteAddr":"x.x.x.x","user":"x-x-x-8d5d-x","app":"core","method":"POST","url":"/apps/files_external/globalcredentials","message":"Login failed: 'x-x-x-x' (Remote IP: 'x.x.x.x')","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"31.0.2.1","data":{"app":"core"}}

In LDAP logs, I see the error : 

[30-03-2025 15:05:21] slapd debug  conn=4879 op=1 SRCH base="ou=people,dc=iut-orsay,dc=fr" scope=2 deref=0 filter="(&(objectClass=*)(|(uid=x-x-x-x)(mail=x-x-x-x-x)(supannAliasLogin=x-x-x-x-x)))"

Nextcloud used my "Nextcloud uuid" as parameters for the LDAP search, wich failed.
The LDAP query enable users, to login with there login, short login, or mail address.

Thank you very much @skjnldsv we now, know, why this does not work !
I don't think the issue is LDAP config related ( I mean, on my side) ?

**Comment by artonge** [comment]
@Bevito could you check whether this PR addresses your issue: https://github.com/nextcloud/server/pull/51870 ?

**Comment by skjnldsv** [comment]
@artonge I think the oidc is still not fixed though 🤔 

> > ```
> > window.backendAllowsPasswordConfirmation
> > true 
> > ```
> 
> [@julien-nc](https://github.com/julien-nc?rgh-link-date=2025-03-30T10%3A26%3A13.000Z) [@artonge](https://github.com/artonge?rgh-link-date=2025-03-30T10%3A26%3A13.000Z) here is the oidc issue! It's supposed to be false
> 
> [server/lib/private/Template/JSConfigHelper.php](https://github.com/nextcloud/server/blob/f758f565d4da004ebef97350365a066eee5267fe/lib/private/Template/JSConfigHelper.php#L68-L69)
> 
> Lines 68 to 69 in [f758f56](/nextcloud/server/commit/f758f565d4da004ebef97350365a066eee5267fe)
> 
>  if ($backend instanceof IPasswordConfirmationBackend) { 
>  	$userBackendAllowsPasswordConfirmation = $backend->canConfirmPassword($uid);

**Comment by artonge** [comment]
The logic is sound, though: https://github.com/nextcloud/user_oidc/blob/258edd81156dc3f7634f027979a1e8b9361c0268/lib/User/Backend.php#L112-L114

@julien-nc could are you able to have a setup with user_oidc?

**Comment by artonge** [comment]
@julien-nc you can try setting some external storage, password confirmation should kick in without delay.

**Comment by julien-nc** [comment]
@artonge I removed the hack to increase the delay https://github.com/nextcloud/user_oidc/blob/main/lib/Controller/LoginController.php#L554 , logged in via user_oidc and could add an external storage without password confirmation.

**Comment by artonge** [comment]
@v3DJG6GL can you confirm that @julien-nc works for you?

**Comment by v3DJG6GL** [comment]
@artonge sorry, I'm a bit slow right now - what code should I adjust/remove?

**Comment by julien-nc** [comment]
Just to be clear: The only change i made to user_oidc was to make sure I didn't have to wait too long to be in a situation where the password confirmation would normally be asked.
I think it does not matter too much if my change is applied or not. What I was able to confirm is:
* login via user_oidc works with latest server's master branch
* once logged in, when performing an action that should immediately, with no delay, ask for password confirmation (like adding an external storage), no password confirmation was asked

**Comment by razorrazor** [comment]
Same problem here! I am not using LDAP auth, only NC built-in auth system. When I want to add or modify an External Storage, NC ask for my password confirmation and it says "Password wrong" after introduce the admin password. The problem exists since NC 30.0.5 at least.

I'm in a production environment and my customer cannot have his config applied. Please help!

**Comment by skjnldsv** [comment]
You also need to confirm the window backendSupportAuth variable thing is false. Right now it seems for some users it's still true, which makes the password confirmation appear

**Comment by susnux** [comment]
> I am not using LDAP auth, only NC built-in auth system.

In this case you should be able to use your user password. So it is unrelated to this as the database user backend supports password confirmation.

**Comment by razorrazor** [comment]
> > I am not using LDAP auth, only NC built-in auth system.
> 
> In this case you should be able to use your user password. So it is unrelated to this as the database user backend supports password confirmation.

I'm afraid not. When ask for my password, i type it and NC response is "password wrong". I am not the only one with this problem and it has been happening several months ago.

**Comment by skjnldsv** [comment]
> > > I am not using LDAP auth, only NC built-in auth system.
> > 
> > 
> > In this case you should be able to use your user password. So it is unrelated to this as the database user backend supports password confirmation.
> 
> I'm afraid not. When ask for my password, i type it and NC response is "password wrong". I am not the only one with this problem and it has been happening several months ago.

then check your setup and that you have all our recommended headers enabled.
https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#additional-apache-configurations

This ticket is only for people having issues with secondary Users backend, such as LDAP or OIDC :)

**Comment by v3DJG6GL** [comment]
> Just to be clear: The only change i made to user_oidc was to make sure I didn't have to wait too long to be in a situation where the password confirmation would normally be asked. I think it does not matter too much if my change is applied or not. What I was able to confirm is:
> 
>     * login via user_oidc works with latest server's master branch
> 
>     * once logged in, when performing an action that should immediately, with no delay, ask for password confirmation (like adding an external storage), no password confirmation was asked
@artonge  @julien-nc 

I am still affected by this bug, no matter whether I try it immediately after login or not: There's always the password prompt when I try to add/change  _External Storage_ settings:
Setup:
- Nextcloud v31.0.2 (public.ecr.aws/docker/library/nextcloud:31.0.2-fpm)
- Nextcloud OIDC Login v3.2.2: https://github.com/pulsejet/nextcloud-oidc-login (https://apps.nextcloud.com/apps/oidc_login)

It seems as if you're using another OIDC Nextcloud app:  _OpenID Connect user backend_ https://github.com/nextcloud/user_oidc (https://apps.nextcloud.com/apps/user_oidc)
I'll setup this OIDC app and try whether this issue may affects only my currently used OIDC App...

**Comment by v3DJG6GL** [comment]
UPDATE:
After setting up this other OIDC plugin: https://github.com/nextcloud/user_oidc (https://apps.nextcloud.com/apps/user_oidc):
Sadly, there is no change in the mentioned behaviour: Bassword prompt always appears when trying to adjust settings at `https://nextcloud.DOMAIN.TLD/settings/admin/externalstorages`, even when I try it immediately after login.

As already mentioned before: This behaviour ONLY occurs at `externalstorages` settings, it does NOT occur for other settings, e.g. `https://nextcloud.DOMAIN.TLD/settings/admin/security` or `https://nextcloud.DOMAIN.TLD/settings/users`:
Deleting a user works. Here, the password prompt only appears when the last OIDC login was longer ago: Re-authenticate (logout and login again) works here as expected - the Password prompt does not appear after that.

**Comment by SBNA-at-EGC** [comment]
Sorry mate.

Version [Nextcloud Hub 10](https://nextcloud.com/) (31.0.2)

Running on a bare apache server..

Trying to connect to an external smb share.   Logging in with ldap that allows me to log in.
Tried both a ldap and internal account, but just keeps refusing my password.  

Need to auth to the smb shares using the login credentials.

Irritatingly, had nextcloud  (same version) installed on another machine for testing,  and that seemed fine..



[core] Warning: Login failed: '22FA34A1-8E2F-40BA-9B0C-D87333E22D41' (Remote IP: '10.250.18.138')
	POST /nextcloud/index.php/apps/files_external/globalstorages
	from 10.250.18.138 by 22FA34A1-8E2F-40BA-9B0C-D87333E22D41 at Apr 7, 2025, 12:43:28 PM
[PHP] Error: Undefined array key 1 at /mnt/d2/nextcloud/lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php#82
	POST /nextcloud/index.php/apps/files_external/globalstorages
	from 10.250.18.138 by 22FA34A1-8E2F-40BA-9B0C-D87333E22D41 at Apr 7, 2025, 12:43:28 PM

**Comment by supr4s** [comment]
I have exactly the same case on a dozen servers with the same profile: 

- LDAP authentication
- Automatic mounting of a drive via an SMB share
- Impossible to modify the parameters of an already mounted drive: a password is constantly requested. User password, administration password, administrator application password (for skipping 2FA) : incorrect password. Blocked from changing parameters

**Comment by skjnldsv** [comment]
Closing, fixed in https://github.com/nextcloud/server/pull/50465

**Comment by supr4s** [comment]
I confirm the fix, thank you @skjnldsv !

**Comment by skjnldsv** [comment]
You can thank @zorn-v :)

**Comment by alphasixsevenkali** [comment]
This is stupid, several months and no fix for this

**Comment by v3DJG6GL** [comment]
@skjnldsv 
I've just updated my Nextcloud instance to v31.0.5 and I am still experiencing this issue:
When changing settings at `https://nextcloud.DOMAIN.TLD/settings/admin/externalstorages`, I still get prompted for a password!

Setup:

- Nextcloud v31.0.5
- Nextcloud User OIDC v7.2.0: https://apps.nextcloud.com/apps/user_oidc (https://github.com/nextcloud/user_oidc)

**Comment by v3DJG6GL** [comment]
UPDATE: ok, it seems I can now enter _any_ random password and it gets accepted. So the problem is kind of fixed. Although a bit strange that it still appears, but accepts all random characters as password...

**Comment by griffi-gh** [comment]
Same issue using the Nextcloud OIDC Login app + Nextcloud 31.0.5

There's seemingly no way to disable this confirmation popup

![Image](https://github.com/user-attachments/assets/dedf2220-f97f-468f-8a6b-bf3052ba4774)

**Comment by skjnldsv** [comment]
@griffi-gh check my last comments in https://github.com/nextcloud/server/pull/50465 please

**Comment by skjnldsv** [comment]
Let's continue in https://github.com/nextcloud/server/issues/53472
I escalated the issue
