### ISSUE TITLE
[Bug]: Shared folder path resolves to null

### ISSUE THREAD

**Issue by pascal260303** [nextcloud/server#53934]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have a shared folder that is internally shared between users. For files directly in that Folder the path becomes null which results in this error message when opening the folder from the user that the folder is shared with:
```
[webdav] Fehler: OC\Files\Storage\Wrapper\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/View.php on line 1528
	PROPFIND /remote.php/dav/files/pascal/Filme/
	von 2a02:8070:8981:b640:6708:8517:4476:bf56 von pascal um 14.07.2025, 16:02:53
```
I replaced `$content['path']` on line 1528 in file `lib/private/Files/View.php` with `$content['path'] ?? ''` as a workaround and also had to apply the same fix in `lib/private/legacy/OC_Helper.php` on line 514.

Now opening the shared folder works, but I don't know if this should be fixed on another layer or is already fixed in master (I have Nextcloud version 31.0.7).

### Steps to reproduce

1. Create a folder with some files directly in it not subfolders
2. Share it with another internal user or group
3. Try to open the shared folder from the other user

### Expected behavior

The folder opens normally

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 32.0.1 to 32.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "***REMOVED SENSITIVE VALUE***",
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "default_phone_region": "DE",
        "version": "31.0.7.1",
        "overwrite.cli.url": "https:\/\/nextcloudpi\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/tmp\/nextcloud\/",
        "ldap_log_file": "\/var\/log\/nextcloud\/nextcloud_ldap.log",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "maintenance_window_start": "4",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "log_type": "file",
        "app_install_overwrite": {
            "0": "duplicatefinder",
            "1": "impersonate",
            "2": "files_automatedtagging",
            "4": "nextcloudpi",
            "5": "previewgenerator",
            "6": "extract",
            "7": "maps"
        },
        "theme": "",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "5ad324349d54b364515ab62db0c5e1ee",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - admin_audit: 1.21.0
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - calendar: 5.3.5
  - cloud_federation_api: 1.14.0
  - contacts: 7.1.5
  - dav: 1.33.0
  - deck: 1.15.1
  - federatedfilesharing: 1.21.0
  - federation: 1.21.0
  - files: 2.3.1
  - files_automatedtagging: 2.0.0
  - files_downloadlimit: 4.0.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - files_zip: 2.1.0
  - firstrunwizard: 4.0.0
  - impersonate: 2.0.0
  - integration_deepl: 1.3.1
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - maps: 1.5.0
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - notify_push: 1.1.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - photos: 4.0.0
  - previewgenerator: 99.99.99
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recognize: 9.0.3
  - related_resources: 2.0.0
  - richdocuments: 8.7.2
  - richdocumentscode_arm64: 25.4.202
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - support: 3.0.0
  - survey_client: 3.0.0
  - systemtags: 1.21.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - twofactor_totp: 13.0.0-dev.0
  - updatenotification: 1.21.0
  - user_ldap: 1.22.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - circles: 31.0.0 (installed 25.0.0)
  - comments: 1.21.0 (installed 1.15.0)
  - contactsinteraction: 1.12.0 (installed 1.11.0)
  - dashboard: 7.11.0 (installed 7.4.0)
  - encryption: 2.19.0
  - files_external: 1.23.0
  - nextcloudpi: 0.0.2 (installed 0.0.1)
  - recommendations: 4.0.0 (installed 1.3.0)
  - suspicious_login: 9.0.1 (installed 9.0.1)
  - twofactor_nextcloud_notification: 5.0.0 (installed 3.8.0)
  - weather_status: 1.11.0 (installed 1.5.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"aHUNatkL_lnY2QZby1pGTgAACgo","level":3,"time":"2025-07-14T14:00:10+00:00","remoteAddr":"2a02:8070:8981:b640:6708:8517:4476:bf56","user":"pascal","app":"files","method":"GET","url":"/ocs/v2.php/apps/files/api/v1/folder-tree?path=%2F&depth=1","message":"OC\\Files\\Storage\\Wrapper\\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/View.php on line 1528","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0","version":"31.0.7.1","exception":{"Exception":"TypeError","Message":"OC\\Files\\Storage\\Wrapper\\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/View.php on line 1528","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1528,"function":"getOwner","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"function":"OC\\Files\\{closure}","class":"OC\\Files\\View","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1524,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":81,"function":"getDirectoryContent","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ApiController.php","line":266,"function":"getDirectoryListing","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ApiController.php","line":311,"function":"getChildren","class":"OCA\\Files\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":200,"function":"getFolderTree","class":"OCA\\Files\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":49,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":7,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","Line":183,"message":"OC\\Files\\Storage\\Wrapper\\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/View.php on line 1528","exception":[],"CustomMessage":"OC\\Files\\Storage\\Wrapper\\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/View.php on line 1528"},"id":"687516286fd50"}
```

**Comment by JanBoehme** [comment]
I'm experiencing the same problem after upgrading from 31.0.6 to 31.0.8. In our case it concerned a seemingly random folder down the tree on a group folder. The error message in the log is identical.

Applying the suggested fix solved the issue here, too.

**Comment by frayos** [comment]
Same issue here in 31.0.8

Will open a support ticket / workaround helped, thank you !

**Comment by frayos** [comment]
FYI similar error in : `/var/www/nextcloud/lib/private/Files/Node/HookConnector.php`

```
"method":"MOVE","url":"/remote.php/dav/uploads/xxxxx/3994711066/.file",
"message":"{\"Exception\":\"TypeError\",\"Message\":\"OC\\\\Files\\\\Node\\\\HookConnector::getNodeForPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/Node/HookConnector.php
```

Workaround is more complicated didn't implement it yet

**Comment by nathanael-h** [comment]
Hello, I tried to apply the patch suggested on 31.0.9 but did not found where to put it in `lib/private/legacy/OC_Helper.php` around line 514.

**Comment by frayos** [comment]
@nathanael-h workaround is on line 550 in 31.0.8 in /var/www/nextcloud/lib/private/legacy/OC_Helper.php
You can find it by looking for "getOwner" there are not many references, was : 
` $ownerId = $storage->getOwner($path);`
and it ends up to be corrected to : 
` $ownerId = $storage->getOwner($path ?? '');`

**Comment by frayos** [comment]
**For the community / not guaranteed nor advised by Tech Support**

Tracing other required changes : 
Issue : 
`Exception\":\"Exception\",\"Message\":\"OCA\\\\Circles\\\\Model\\\\ShareWrapper::getCircle(): Return value must be of type OCA\\\\Circles\\\\Model\\\\Circle, null returned in file '/var/www/nextcloud/apps/circles/lib/Model/ShareWrapper.php' line 263`
File : "/var/www/nextcloud/apps/circles/lib/Model/ShareWrapper.php"
Line 262
Before : 
`  public function getCircle(): Circle {`
After
`  public function getCircle(): ?Circle {`

To make it allow null 


Issue : 
`Exception\":\"TypeError\",\"Message\":\"OC\\\\Files\\\\Node\\\\HookConnector::getNodeForPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/Node/HookConnector.php on line 173\",\"Code\":0,\"Trace\":[{\"file\":\"/var/www/nextcloud/lib/private/Files/Node/HookConnector.php\",\"line\":173`
File : "/var/www/nextcloud/lib/private/Files/Node/HookConnector.php"
Line 206
Before : 
```
        private function getNodeForPath(string $path, bool $isDir = false): Node {
                $info = Filesystem::getView()->getFileInfo($path);
```
After 
```
        private function getNodeForPath(?string $path, bool $isDir = false): Node {
                $path = $path ?? ''; // Handle null by converting to empty string
                $info = Filesystem::getView()->getFileInfo($path);

```

Issue (consequence of first above) : 
`"{\"Exception\":\"Exception\",\"Message\":\"Call to a member function getInheritedMembers() on null in file '/var/www/nextcloud/apps/circles/lib/ShareByCircleProvider.php' line 674`
File : "/var/www/nextcloud/apps/circles/lib/ShareByCircleProvider.php"
Line 674 
Before : 
`foreach ($circle->getInheritedMembers() as $member) { `
After : 
`                        foreach ($circle->getInheritedMembers() ?? [] as $member) {`

**Comment by icewind1991** [comment]
Can you try applying https://github.com/nextcloud/server/commit/24470d388a69225b9148d13cf8e34df1e26e70e5 and than provide any entry from the nextcloud log containing "Formatted cache entry outside of jail".

This should hopefully help narrow down the root cause

**Comment by werk21** [comment]
1. Same bug as reported here in a random shared dir of a user. Also my client said that some subdirs and files are shared externally by link.
2. updated from 31.08 to 31.0.9 had no effect.
3. Added solution form bugreport "fixed" it.

> Can you try applying [24470d3](https://github.com/nextcloud/server/commit/24470d388a69225b9148d13cf8e34df1e26e70e5) and than provide any entry from the nextcloud log containing "Formatted cache entry outside of jail".
> 
> This should hopefully help narrow down the root cause

I added this patch. Nothing in the logs (loglevel 0). Before and after i applied the solution from bugreport.

HTH.

**Comment by frayos** [comment]
@icewind1991 , 
I tried the patch as well, didn't print anything in the log when reproducing, before or after rolling back the changes I did.

To be noted in my case, the systematic way I found to reproduce is to try to delete a folder as a end user who received it by some Circle sharing

My current error is : getCircle(): Return value must be of type OCA\\\\Circles\\\\Model\\\\Circle, null returned  
```
"message":"{\"Exception\":\"TypeError\",\"Message\":\"OCA\\\\Circles\\\\Model\\\\ShareWrapper::getCircle(): Return value must be of type OCA\\\\Circles\\\\Model\\\\Circle, null returned\",\"Code\":0,\"Trace\":[{\"file\":\"/var/www/nextcloud/apps/circles/lib/ShareByCircleProvider.php\",\"line\":673,\"function\":\"getCircle\",\"class\":\"OCA\\\\Circles\\\\Model\\\\ShareWrapper\",\"type\":\"->\",\"args\":[]},{\"file\":\"/var/www/nextcloud/lib/private/Share20/Manager.php\",\"line\":1700,\"function\":\"getAccessList\",\"class\":\"OCA\\\\Circles\\\\ShareByCircleProvider\",\"type\":\"->\",\"args\":[[{\"__class__\":\"OC\\\\Files\\\\Node\\\\File\"},{\"__class__\":\"OC\\\\Files\\\\Node\\\\LazyFolder\"},{\"__class__\":\"OC\\\\Files\\\\Node\\\\LazyFolder\"},{\"__class__\":\"OC\\\\Files\\\\Node\\\\LazyFolder\"}],true]},{\"file\":\"/var/www/nextcloud/lib/private/Share20/ShareHelper.php\",\"line\":33,\"function\":\"getAccessList\",\"class\":\"OC\\\\Share20\\\\Manager\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Files\\\\Node\\\\LazyFolder\"},true,true]},{\"file\":\"/var/www/nextcloud/apps/activity/lib/FilesHooks.php\",\"line\":584,\"function\":\"getPathsForAccessList\",\"class\":\"OC\\\\Share20\\\\ShareHelper\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Files\\\\Node\\\\File\"}]},{\"file\":\"/var/www/nextcloud/apps/activity/lib/FilesHooks.php\",\"line\":152,\"function\":\"getUserPathsFromPath\",\"class\":\"OCA\\\\Activity\\\\FilesHooks\",\"type\":\"->\",\"args\":[\"/odr/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\",\"tpomeon\"]},{\"file\":\"/var/www/nextcloud/apps/activity/lib/FilesHooks.php\",\"line\":103,\"function\":\"addNotificationsForFileAction\",\"class\":\"OCA\\\\Activity\\\\FilesHooks\",\"type\":\"->\",\"args\":[\"/odr/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\",\"file_deleted\",\"deleted_self\",\"deleted_by\"]},{\"file\":\"/var/www/nextcloud/apps/activity/lib/FilesHooksStatic.php\",\"line\":43,\"function\":\"fileDelete\",\"class\":\"OCA\\\\Activity\\\\FilesHooks\",\"type\":\"->\",\"args\":[\"/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\"]},{\"file\":\"/var/www/nextcloud/lib/private/legacy/OC_Hook.php\",\"line\":85,\"function\":\"fileDelete\",\"class\":\"OCA\\\\Activity\\\\FilesHooksStatic\",\"type\":\"::\",\"args\":[{\"run\":true,\"path\":\"/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\"}]},{\"file\":\"/var/www/nextcloud/lib/private/Files/View.php\",\"line\":1322,\"function\":\"emit\",\"class\":\"OC_Hook\",\"type\":\"::\",\"args\":[\"OC_Filesystem\",\"delete\",{\"run\":true,\"path\":\"/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\"}]},{\"file\":\"/var/www/nextcloud/lib/private/Files/View.php\",\"line\":1194,\"function\":\"runHooks\",\"class\":\"OC\\\\Files\\\\View\",\"type\":\"->\",\"args\":[[\"delete\"],\"/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\"]},{\"file\":\"/var/www/nextcloud/lib/private/Files/View.php\",\"line\":676,\"function\":\"basicOperation\",\"class\":\"OC\\\\Files\\\\View\",\"type\":\"->\",\"args\":[\"unlink\",\"/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\",[\"delete\"]]},{\"file\":\"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php\",\"line\":508,\"function\":\"unlink\",\"class\":\"OC\\\\Files\\\\View\",\"type\":\"->\",\"args\":[\"/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\"]},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php\",\"line\":197,\"function\":\"delete\",\"class\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File\",\"type\":\"->\",\"args\":[]},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php\",\"line\":281,\"function\":\"delete\",\"class\":\"Sabre\\\\DAV\\\\Tree\",\"type\":\"->\",\"args\":[\"files/sauthier/odr (2)/ODR_administratif/03_Missions_D\\u00e9placements/SIFAC - Proc\\u00e9dure d\\u00e9rogatoire - XXXXYYYFILENAMEXXXX.docx\"]},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php\",\"line\":89,\"function\":\"httpDelete\",\"class\":\"Sabre\\\\DAV\\\\CorePlugin\",\"type\":\"->\",\"args\":[{\"__class__\":\"Sabre\\\\HTTP\\\\Request\"},{\"__class__\":\"Sabre\\\\HTTP\\\\Response\"}]},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":472,\"function\":\"emit\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\",\"args\":[\"method:DELETE\",[{\"__class__\":\"Sabre\\\\HTTP\\\\Request\"},{\"__class__\":\"Sabre\\\\HTTP\\\\Response\"}]]},{\"file\":\"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Server.php\",\"line\":49,\"function\":\"invokeMethod\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\",\"args\":[{\"__class__\":\"Sabre\\\\HTTP\\\\Request\"},{\"__class__\":\"Sabre\\\\HTTP\\\\Response\"}]},{\"file\":\"/var/www/nextcloud/apps/dav/lib/Server.php\",\"line\":401,\"function\":\"start\",\"class\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server\",\"type\":\"->\",\"args\":[]},{\"file\":\"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php\",\"line\":21,\"function\":\"exec\",\"class\":\"OCA\\\\DAV\\\\Server\",\"type\":\"->\",\"args\":[]},{\"file\":\"/var/www/nextcloud/remote.php\",\"line\":145,\"args\":[\"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php\"],\"function\":\"require_once\"}],\"File\":\"/var/www/nextcloud/apps/circles/lib/Model/ShareWrapper.php\",\"Line\":263,\"message\":\"OCA\\\\Circles\\\\Model\\\\ShareWrapper::getCircle(): Return value must be of type OCA\\\\Circles\\\\Model\\\\Circle, null returned\",\"exception\":{},\"CustomMessage\":\"OCA\\\\Circles\\\\Model\\\\ShareWrapper::getCircle(): Return value must be of type OCA\\\\Circles\\\\Model\\\\Circle, null returned\"
```

**Comment by icewind1991** [comment]
Please try the following patch: https://github.com/nextcloud/server/pull/56291/commits/68091bbce34abec88cdd6927a44ebdf5f3cd7124 and https://github.com/nextcloud/server/pull/56291/commits/6a2f593a56ddab0387b7986568810f14d077f193 and see if there is a log item with "contains item with null path".

If so, please provide:

 - the full log entry
 - the output of `occ info:file <path mentioned in the log line>`
 - the output of `occ info:file <fileid mentioned in the log line>`
 - any log entry containing "is not inside jail path"

**Comment by icewind1991** [comment]
While we haven't been able to find a root cause where, but it seems that running `occ files:repair-tree` will fix the issue.

If somebody is able to find steps that re-triggers the issue after resolving it with the `occ` command that please post it here.

**Comment by solracsf** [comment]
@icewind1991 despite the errors:

```
# occ files:repair-tree
Found 0 file entries with an invalid path
```
So nothing has been fixed.

Also, after applying the mentioned commits, no log entry containing "is not inside jail path" is logged.

**Comment by doobry-systemli** [comment]
We have the same problem on an instance (31.0.12). As far as we know, all affected files are in group folders. Even `info:file` throws the exception:

```
occ info:file 1374341
receipts
  fileid: 1374341
  mimetype: httpd/unix-directory
  modified: December 15, 2025, 4:41:03 PM UTC
  size: 4.8 MB
  etag: 69403a1f4c830
An unhandled exception has been thrown:
TypeError: OC\Files\Storage\Wrapper\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/cloud.domain.tld/lib/private/Files/View.php on line 1528 and defined in /var/www/cloud.domain.tld/lib/private/Files/Storage/Wrapper/Wrapper.php:183
Stack trace:
#0 /var/www/cloud.domain.tld/lib/private/Files/View.php(1528): OC\Files\Storage\Wrapper\Wrapper->getOwner()
#1 [internal function]: OC\Files\View->{closure:OC\Files\View::getDirectoryContent():1524}()
#2 /var/www/cloud.example.tld/lib/private/Files/View.php(1524): array_map()
#3 /var/www/cloud.example.tld/lib/private/Files/Node/Folder.php(81): OC\Files\View->getDirectoryContent()
#4 /var/www/cloud.example.tld/core/Command/Info/File.php(93): OC\Files\Node\Folder->getDirectoryListing()
#5 /var/www/cloud.example.tld/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\Info\File->execute()
#6 /var/www/cloud.example.tld/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#7 /var/www/cloud.example.tld/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/cloud.example.tld/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#9 /var/www/cloud.example.tld/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#10 /var/www/cloud.example.tld/console.php(87): OC\Console\Application->run()
#11 /var/www/cloud.exampel.tld/occ(33): require_once('...')
```

@icewind1991 does this help with tracking down the problem?

**Comment by doobry-systemli** [comment]
@icewind1991 we didn't run `occ files:repair-tree` yet. Shall we wait with it so we potentially can do further debugging steps with the broken folders on our instance?

**Comment by EchedelleLR** [comment]
> FYI similar error in : `/var/www/nextcloud/lib/private/Files/Node/HookConnector.php`
> 
> ```
> "method":"MOVE","url":"/remote.php/dav/uploads/xxxxx/3994711066/.file",
> "message":"{\"Exception\":\"TypeError\",\"Message\":\"OC\\\\Files\\\\Node\\\\HookConnector::getNodeForPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/Node/HookConnector.php
> ```
> 
> Workaround is more complicated didn't implement it yet

I am affected by this issues. If I understand, the workaround is applying the patch you mentioned?

**Comment by fabo-dev** [comment]
> While we haven't been able to find a root cause where, but it seems that running `occ files:repair-tree` will fix the issue.
> 
> If somebody is able to find steps that re-triggers the issue after resolving it with the `occ` command that please post it here.

Running `occ files:repair-tree` fixed the problem. The command found 4 file entries with an invalid path and repaired them. Now the group folder opens correctly. Nextcloud version 31.0.13

**Comment by sorbaugh** [comment]
Either this or a very similar issue has been fixed in recent groupfolder versions, so I'm suspecting this is no longer an issue.

**Comment by julien-nc** [comment]
@sorbaugh Can you point to some PRs? I could check in which releases the potential fix has been included.

**Comment by nathanael-h** [comment]
So it looks like the issue might happen when a user move a folder shared internally to another user, from one groupfolder to another groupfolder. I did not happen to reproduce the issue myself. But the fix was to apply this PR https://github.com/nextcloud/server/pull/58285 (as I'm running v32.0.3 I applied this backport https://github.com/nextcloud/server/pull/58377 ) and to run some occ commands. `occ files:repair-tree` and `occ groupfolders:scan <id-of-groupfolder> -vvv`.

**Comment by salmart-dev** [comment]
> > FYI similar error in : `/var/www/nextcloud/lib/private/Files/Node/HookConnector.php`
> > ```
> > "method":"MOVE","url":"/remote.php/dav/uploads/xxxxx/3994711066/.file",
> > "message":"{\"Exception\":\"TypeError\",\"Message\":\"OC\\\\Files\\\\Node\\\\HookConnector::getNodeForPath(): Argument #1 ($path) must be of type string, null given, called in /var/www/nextcloud/lib/private/Files/Node/HookConnector.php
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Workaround is more complicated didn't implement it yet
> 
> I am affected by this issues. If I understand, the workaround is applying the patch you mentioned?

Just merged a fix for the HookConnector TypeError during MOVE: https://github.com/nextcloud/server/pull/58660

**Comment by susnux** [comment]
I have a report about this happened again even after https://github.com/nextcloud/server/pull/58660 was applied.

> OC\Files\Storage\Wrapper\Wrapper::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/html/nextcloud/XXXX/lib/private/Files/View.php on line 1528

**Comment by salmart-dev** [comment]
> I have a report about this happened again even after [#58660](https://github.com/nextcloud/server/pull/58660) was applied.
> 
> > OC\Files\Storage\Wrapper\Wrapper::getOwner(): Argument [#1](https://github.com/nextcloud/server/issues/1) ($path) must be of type string, null given, called in /var/www/html/nextcloud/XXXX/lib/private/Files/View.php on line 1528

The HookConnector problem is a separate issue. I hid all reports that are not the issue with the `getOwner` call receiving null instead of a path as "Off-topic" as they are.

Regarding the original report: OP does not have `groupfolders` enabled, so this is probably not related. Not sure about circles, as OP has the app disabled.

**Comment by salmart-dev** [comment]
> So it looks like the issue might happen when a user move a folder shared internally to another user, from one groupfolder to another groupfolder. I did not happen to reproduce the issue myself. But the fix was to apply this PR [#58285](https://github.com/nextcloud/server/pull/58285) (as I'm running v32.0.3 I applied this backport [#58377](https://github.com/nextcloud/server/pull/58377) ) and to run some occ commands. `occ files:repair-tree` and `occ groupfolders:scan <id-of-groupfolder> -vvv`.

You definitely were onto something here: I was able to reproduce the issue combining groupfolders and shares and it turned out there was an issue in the CacheJail/CacheWrapper code and provided a fix: https://github.com/nextcloud/server/pull/59252

Once the changes are included in a released version, it should be enough to run `occ files:repair-tree` and the issue should not reappear.

On that note, if someone is willing to apply a patch on their instance and confirm this fixes the issue for good, it would be greatly appreciated!

**Comment by Alwaysin** [comment]
For information - I didn't see it mentioned in the comments - this affects retention policies. We have this happening when the app is trying to delete an expired file and so is not doing so. I had to disable files_versions in order for the job to complete successfully but this is not an ideal solution.
It looks like a fix has been released and backported to 33 but in 33.0.5 it is still present.
Repair-tree returned nothing:
```
#sudo -u partage php occ files:repair-tree
Found 0 file entries with an invalid path

```

**Comment by LMonert** [comment]
We are still experiencing this issue on an instance running 33.0.5. The setup ist the same as described in https://github.com/nextcloud/server/issues/59993 :

1. User A shares a folder internally with either a group containing User B or directly with User B
2. User B shares a public link with full permissions for a subfolder of User A's internally shared folder
3. Someone with the public link can now upload a file or download files, but when deleting files, this will lead to an error message / HTTP 500 in the browser console

From the logs: "OC\Files\View::getOwner(): Argument #1 ($path) must be of type string, null given, called in /var/www/html/lib/private/Files/Filesystem.php on line 690"

There still must be some issue left since the changes from https://github.com/nextcloud/server/pull/59252 should already be applied in 33.0.5. I also ran the repair tree command which did not find any entries to fix.

**Comment by icewind1991** [comment]
I cannot reproduce the issue with those steps, can you try applying https://github.com/nextcloud/server/commit/daab182 and then post the log (full json) that should get logged
