### ISSUE TITLE
NC12.0.0 + PHP-fpm + Calender-App = 100% CPU usage

### ISSUE THREAD

**Issue by hollerauer** [nextcloud/server#5653]
Issue was originally posted [here](https://github.com/nextcloud/calendar/issues/530).

There are two forum topics about this malfunction:

1. https://help.nextcloud.com/t/php-fpm-using-100-cpu/14731/6
2. https://help.nextcloud.com/t/after-update-11-0-3-to-12-final-from-beta-chan-calendar-loading-infinitly-and-php-fpm-100-cpu-usage/12876/1

**Comment by mvdnes** [comment]
After a *LOT* of stepping, I have found the cause in my case.

For me, there is a recurring event in my calendar with the following rule:
```php
array (
  'FREQ' => 'YEARLY',
  'BYYEARDAY' => '360',
  'INTERVAL' => '1',
)
```
This recurrence is wrong and highly unusual. It is december 26 on normal years, and december 25 on leap years.

When determining the next event a bug occurs here: [RRuleIterator]. 

`$this->currentDate` can (and *is* in my case) a `DateTimeImmutable`, so the calls to `setDate`, `add` and `sub` do not do anything. They should be of the form `$date = $date->setDate(...)`.

Changing this seems to relieve all my errors.
I would like to submit a pull request for this bugfix, but am unsure where. 

[RRuleIterator]: https://github.com/nextcloud/3rdparty/blob/cae79927de50c6ab0bf77e5653015b6579ae2aea/sabre/vobject/lib/Recur/RRuleIterator.php#L594-L600

**Comment by mvdnes** [comment]
I have submitted a PR at fruux/sabre-vobject#383.

**Comment by loconox** [comment]
I confirm that this seems to solve my issue too.

**Comment by nekudo** [comment]
Confirmed. Solves the 100% load (endless loop) issue as described here: https://help.nextcloud.com/t/after-update-11-0-3-to-12-final-from-beta-chan-calendar-loading-infinitly-and-php-fpm-100-cpu-usage/12876

**Comment by mikelupe** [comment]
Confirmed. Thanks for the fix.

**Comment by Sailing74** [comment]
I can confirm the issue is still in Nextcloud 12.0.3, and this fix resolves the issue for me.

**Comment by BlackIkeEagle** [comment]
Will nextcloud patch their version of vobject with https://github.com/sabre-io/vobject/pull/383 ? Or do we wait forever on sabre to merge this?

**Comment by BlackIkeEagle** [comment]
@here, since the fix is merged in sabre/vobject, could nextcloud make use of the 4.1.4 version ?

**Comment by cl445** [comment]
Workaround for now: 
edit `./3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php`
and change the three lines like this commit does: [here](https://github.com/sabre-io/vobject/pull/383/commits/83d7367c1ac0c6d8c04bb74c8fdcb1a5efa0c958)

**Comment by mikelupe** [comment]
This issue hasn't changed and still is around in NC 12.0.5 and I guess as well in 13.x. Are there plans to officially integrated the "workarounds"?

**Comment by g4b0** [comment]
I can confirm that the issue is still present in NC 13.0.1, and the workaround seems to solve.
I hope it will be included into the next NC stable version

**Comment by jinnko** [comment]
This issue is still affecting NC 13.0.2.  I have confirmed the changes from sabre-io/vobject#383 fixes it for me using the latest official nextcloud docker container.
Given this is low hanging fruit for an extremely annoying problem, what would it take to get this resolved for the next point release of NC 13?

**Comment by martinsauter** [comment]
It would really be nice if this was fixed... I'm not looking forward to edit php files after an update so calendar functionality remains usable.

**Comment by nekudo** [comment]
Just updated to 13.0.4 and error is still there...

**Comment by tessus** [comment]
https://github.com/nextcloud/3rdparty/tree/master/sabre has to be updated to the latest sabre code.
Unfortunately sabre is pretty much dead and I believe the nc devs just do not know how to proceed.

In any case an update to the 3rdparty repo with the latest sabre code would help a lot.

**Comment by tessus** [comment]
@mvdnes you could try to create another PR for the [3rdparty repo](https://github.com/nextcloud/3rdparty).

**Comment by mvdnes** [comment]
It's up at nextcloud/3rdparty#123

**Comment by tessus** [comment]
awesome, fingers crossed that the nc devs merge it soon ;-)

**Comment by nekudo** [comment]
14.0.1 - still not fixed even though patch is available for a long time... :(

**Comment by LeoVerto** [comment]
This should be fixed in 15.0.0: https://github.com/nextcloud/3rdparty/commit/085494c2ad5c3757f9f1c11945f786d63fb2d40f

**Comment by danielkesselberg** [comment]
Thank you for heads up :+1:
