### ISSUE TITLE
Login button without border/color distinction after upgrading to 12.0.3

### ISSUE THREAD

**Issue by Bubu** [nextcloud/server#6857]
### Steps to reproduce
1. Use Nextcloud 12.0.3
2. Remove the Login Image inside the theming app
3. Use any theme color, or keep the default

### Expected behaviour
Login button has a distinctive background like in any version before.

### Actual behaviour
Login button has no border and no different background. It's really not a button anymore and you wouldn't guess it's clickable from the design.

![screenshot at 2017-10-17 18-09-31](https://user-images.githubusercontent.com/105185/31676442-ea03dd3a-b367-11e7-844f-fdf066b6aaa6.png)
![screenshot at 2017-10-17 18-11-36](https://user-images.githubusercontent.com/105185/31676448-ebe073de-b367-11e7-9ea9-56d9ead71305.png) #

**Comment by Tsuroerusu** [comment]
I am also experiencing this problem. To me it is actually a pretty large regression in the theming app, because I use a bit of branding for some of my customers, and it looks really unprofessional with the button seeming almost invisible because of the lack of a differentiating color.

**Comment by Tsuroerusu** [comment]
Another problem that this bug is causing is that with the default theming settings, the login button does not get its mouse-over effect.

**Comment by BandonRandon** [comment]
I'm new to Nextcloud but this almost feels like an esthetic thing to me and less like a bug. However, if the functionality itself has been changed from an earlier version I can see how that can feel like a bug and be something that may need fixing. 

A few quick notes:

1) users can always press the enter key to login even if they don't see the login "button"
2) I use the custom CSS app and added a simple gradient background which is one way to make the button appear:

<img width="1613" alt="screen shot 2017-11-28 at 2 38 55 am" src="https://user-images.githubusercontent.com/150348/33315440-96481780-d3e5-11e7-80c1-bc75a3d31023.png">
3) Apply a background image to the login page via login background. 

Looks like this is the line where the colour is being applied and If it's determined this is a regression I think this could be a great first commit/patch as a way I can contribute to the project:
 https://github.com/nextcloud/server/blob/master/apps/theming/css/theming.scss#L93

From the commit history I see @MorrisJobke  changed things in https://github.com/nextcloud/server/commit/f5aea79bd774f68eac5e2843cb1fe29a3b8f5182 

Looks like the intention was to have a single boarder around the buttons but for them to match the background color of the login. See: https://github.com/nextcloud/server/pull/6370

If that's the case I'll work on getting a quick CSS patch.

**Comment by Tsuroerusu** [comment]
@BandonRandon In versions prior to 12.0.3 it would generate a colour lighter than the background colour for the login button.

Here's an example from one of my servers:
![login](https://user-images.githubusercontent.com/9139161/33316078-fa9a32fc-d432-11e7-94be-3e0f43f627e7.png)

This is waaaay better, because you can an actual button, visually, and not what looks like just a link. I definitely think this is a regression, and I would really hope it could be fixed soon. For my theming it ruins things. Or at least have it be optional, so I could choose to have a varying colour for the login button (Which I suspect most people would want to do) or have it be the same as the background colour.

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by MorrisJobke** [comment]
This was fixed in master with https://github.com/nextcloud/server/commit/2e6d1a3453abf6dda86b981b7e69ae77079a9d01

**Comment by Tsuroerusu** [comment]
@MorrisJobke I just took a look at that commit which you describe, and I then proceeded to look at the theming.scss file in 12.0.3, but the code is the same as the changed code in master. Unless I am seeing something wrong, this was actually broken by that commit, and not fixed, or do you mean to say that this change was intentional, ie. to not show login button with a colour distinct from the page background?

**Comment by MorrisJobke** [comment]
Fix is in #7322
