### ISSUE TITLE
Searching in a large folder makes the browser unresponsive

### ISSUE THREAD

**Issue by CamZie** [nextcloud/server#6861]
### Steps to reproduce
1. Searching using the search button, in a large folder (8.4 GB) which contains 7716 files.
2. The Installation freezes when typing one string on the search button.
3. Browser becomes unresponsive.
 
### Expected behaviour
It should find the files matching the string I wrote on the search button.

### Actual behaviour
Typing one string on the search button freezes the browsers firefox, chrome and safari in a Linux or Mac OS X computers.

### Server configuration

**Operating system**: Debian 8 (jessie)

**Web server:** nginx 1.12.1

**Database:** MariaDB 10.0.32

**PHP version:** 5.6.30

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from version 9.0.55

**Where did you install Nextcloud from:** The Nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 0,
        "activity_expire_days": 180,
        "trashbin_retention_obligation": "auto,90",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** gluster

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox, Chrome and Safari

**Operating system:** Linux and Mac OS X

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Could not follow since the browser becomes unresponsive. I only receive the error that the browser takes too long too load so I had to kill the process

</details>

**Comment by nickvergessen** [comment]
I tested it with 1k Files.

It doesnt actually freeze for me, but it takes quite some time to load the list and react again.
I guess the JS filtering takes up all the resources?

**Comment by nickvergessen** [comment]
Here is a zip with 6k files: [test2.zip](https://github.com/nextcloud/server/files/1398189/test2.zip)

Uploading takes ~20mins for me and yes, jQuery dies when searching:
![bildschirmfoto vom 2017-10-19 13-47-36](https://user-images.githubusercontent.com/213943/31769483-2a7ef2ec-b4d4-11e7-9f22-a6c447c39f43.png)

**Comment by CamZie** [comment]
@nickvergessen Thank you for reproducing the problem, this is exactly what happened on our side. Do you by any chance know if this issue will be fixed on the next release? If not, is there any workaround for this problem?

**Comment by nickvergessen** [comment]
Not really, until now no one took over the issue or had a look how to fix it.

**Comment by CamZie** [comment]
Is there any updates or news for this issue?

**Comment by CamZie** [comment]
I upgraded my installation to Nextcloud 13.0.1 hoping that the problem would be fixed, since I read in the changelog that there is significant improvement in the speed and the search functionality. Unfortunately, the issue still persists.

**Comment by acs-ferreira** [comment]
## Errors also while browsing



### Steps to reproduce
1. Define PHP `post_max_size` and `upload_max_size` to 1024M
2. Upload more than 3000 pictures at root using Object Storage as Primary Storage
3. Try to browse WebGUI

### Expected behaviour
Browsing is smooth

### Actual behaviour
Chrome and Firefox crashes, or, some CSS is lost and a message about server limits appears.

![image](https://user-images.githubusercontent.com/12234510/72280643-174a4300-3639-11ea-85d8-973ca3f43479.png)


### Server configuration

**Operating system:** Windows 10 (client)

**Web server:** 18.04 under Nginx+Apache

**Database:** MariaDB10.2

**PHP version:** 7.3.13

**Nextcloud version:** (see Nextcloud admin page) 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fressh

**Where did you install Nextcloud from:** download.nextcloud.com

**Signing status:** No errors have been found.

No browser or nextcloud errors in logs.

**Comment by skjnldsv** [comment]
Fixed nc20

**Comment by adrianbj** [comment]
@skjnldsv - I am having issues with this. I just installed NC today, so it's the latest version. When things were initially set up, the search was very fast, but now I have copied across ~3TB of files to a group folder and done an `occ files:scan --all`. I was testing the search as the scan index was being built and it kept getting slower and slower as it went, to the point where it became non-functional. The `search?term=` XHR requests end up taking minutes to complete but if I do a simple:
```
SELECT * FROM oc_filecache WHERE name LIKE '%searchterm%'
```
the results are returned in less than a second, so it's certainly not the query that's the issue, but I am not really sure why the request takes so long. Please let me know if there is any other info I can provide or if you'd like me to post a new issue.

Thanks.

**Comment by intcreator** [comment]
I'm using Nextcloud 23. I have a folder with over 41,000 files in it and when I search the browser becomes unresponsive until I force close it with task manager. navigating and searching the data storage folder using Windows Explorer is very fast. for me this issue does not appera to be fixed in Nextcloud 20 so the issue should be reopened

**Comment by abacuslifedev** [comment]
I am having the same issue as @intcreator using NextCloud 23.... this issue should be reopened.

**Comment by germainm** [comment]
Using latest nextcloud and issue still present. 

You can easily trigger the problem : 

go in a folder with thousand files. start a search (with glass). it will become unresponsive. 

javascript seems the issue because the cpu is running at max during that time. 

it could be optimisation problem?

if I start the search from another directory with only some files, the search doesn't lag. 

Fulltextsearch is enabled fyi

**Comment by germainm** [comment]
I changed the appdata location and it improved loading time a lot. 

There's no option to change it, so I had to symlink it.

**Comment by Traace** [comment]
Bug still exists... I'm using NC23. Around 3500 PDFs in Folder

Please reopen the issue @skjnldsv

**Comment by bilibilinan** [comment]
Bug still exists with with NC 24.0.5.
Freeze when you input the 2nd character of file name.

**Comment by fcharlaix-opendsi** [comment]
This issue is still present with Nextcloud v26.0.1.

Tested with two Chrome browsers and Firefox, all of them got a warning from the page being unresponsive.

@skjnldsv cloud you reopen this issue please ?

**Comment by platelminto** [comment]
Still an issue in Nextcloud v29.0.4.

I don't understand how this isn't a priority - aren't large folders full of files an expected usecase for a cloud service? If this isn't just a bug, adding pagination or some sort of lazy loading would fix it. (In particular, I encountered this when trying to move some files into a large directory through the web interface, which freezes everything as it first tries to load the entire directory's contents).

I know it still takes development time, but at least have an Open issue for it so someone can take a look at it (I would be happy to try, for example). This isn't resolved
