### ISSUE TITLE
Log in: Access forbidden, CSRF check failed

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#754]
1. Have 2 tabs with Nextcloud open
2. Log out of one and refresh the other one too
3. Log in again on the first one
4. Go to the other tab and log in there too
5. Get this:
![capture du 2016-08-01 08-57-51](https://cloud.githubusercontent.com/assets/925062/17439160/eb42b616-5b26-11e6-8dde-738753d59ad8.png)

This should not happen as the credentials were put in correctly. It’s a very cryptic error message where actually I should be logged in. @LukasReschke @MorrisJobke – ideally also to backport if it’s not too big.

**Comment by MorrisJobke** [comment]
@LukasReschke has a patch locally available and will create a PR soon

**Comment by jancborchardt** [comment]
@LukasReschke yo! We should fix this for Nextcloud 10. It happens all the damn time :\

**Comment by AndyScherzinger** [comment]
@jancborchardt According to Lukas you will get this if you review https://github.com/nextcloud/android/issues/188 and https://github.com/nextcloud/android/pull/204 :grin:

**Comment by LukasReschke** [comment]
> @jancborchardt According to Lukas you will get this if you review nextcloud/android#188 and nextcloud/android#204 😁

^ This 🙈

**Comment by jancborchardt** [comment]
@AndyScherzinger done ;)

**Comment by ridexbuilder** [comment]
Still happening on 2 different installations.
PHP Version: 7.3.9/Nextcloud 17.0.0 and
PHP Version: 7.3.10/Nextcloud 16.0.5.1

**Comment by jancborchardt** [comment]
@ridexbuilder since this issue is closed for so long and a lot of things changed, could you open a new issue for this? And more info like logs will be needed.

**Comment by ridexbuilder** [comment]
Sorry, too busy with other stuff to debug. Was making the point that this still happens.
