### ISSUE TITLE
public upload failed if  'quota_include_external_storage' => true,

### ISSUE THREAD

**Issue by riegercloud** [nextcloud/server#801]
1. Set 'quota_include_external_storage' => true to avoid wrong quota calculation
![01](https://cloud.githubusercontent.com/assets/20593693/17531645/16d41712-5e7d-11e6-857d-13d6140531ae.PNG)
![02](https://cloud.githubusercontent.com/assets/20593693/17531564/b0d85dce-5e7c-11e6-9db9-37fc533bcff5.PNG)

2. Open a public share ([https://nc.c-rieger.de/s/4GIdafRvyFu1BoX]) 
![03](https://cloud.githubusercontent.com/assets/20593693/17531769/a82d0c5a-5e7d-11e6-8b2d-835b4e88c8c2.PNG)

and try to upload files<br>
3. any public upload will fail, the spinning wheel never disappears
![public upload](https://cloud.githubusercontent.com/assets/20593693/17531659/2a562140-5e7d-11e6-8e19-445676f10254.PNG)

### Expected behaviour
Uploading files (anonymous) to your nextcloud should be possible if you provide a public upload share

### Actual behaviour
hanging uploads, any upload fail

### Server configuration
**Operating system**:
 Ubuntu 16.04.1 LTS as well on a virtual box as on odroid c2

**Web server:**
nginx 1.11.3

**Database:**
MariaDB 10.0.25

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

**http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0

Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
  - user_saml
```
**sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "oc7a55z9gucu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "192.168.y.x"
        ],
        "datadirectory": "\/var\/nc_data",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "9.0.53.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "Europe\/Berlin",
        "filesystem_check_changes": 1,
        "knowledgebaseenabled": false,
        "quota_include_external_storage": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "cron_log": true,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "debug": false,
        "appstore.experimental.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "theme": "",
        "maintenance": false
    }
}
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
**no**, no external storage but nas storage is mounted to users directory via /etc/fstab  =>

> //192.168.y.x/sharename /var/nc_data/myuser/files cifs user,uid=33,rw,suid,credentials=/home/myuser/.smbcredentials,iocharset=utf8,file_mode=0770,dir_mode=0770 0 0

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Edge, Firefox 48
**Operating system:**
Ubuntu and Windows 10

### Logs
nextcloud.log
{"reqId":"WBqaJrKd6ZbIIpg510bp","remoteAddr":"192.168.y.x","app":"PHP","message":"Error: Call to a member function getQuota() on null at \/var\/www\/nextcloud\/lib\/private\/util.php#289","level":3,"time":"2016-08-09T21:47:11+02:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php","user":"--"}
{"reqId":"ifxug710752+h1hC5q5\/","remoteAddr":"192.168.y.x","app":"admin_audit","message":"Login attempt: \"myuser\"","level":1,"time":"2016-08-09T21:48:21+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/calendars\/myuser\/default\/","user":"--"}
{"reqId":"MlUm7BNHXkgtS5JCC\/+a","remoteAddr":"192.168.y.x","app":"admin_audit","message":"Login attempt: \"myuser\"","level":1,"time":"2016-08-09T21:48:21+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/myuser\/default\/","user":"--"}
{"reqId":"ifxug710752+h1hC5q5\/","remoteAddr":"192.168.y.x","app":"admin_audit","message":"Login successful: \"myuser\"","level":1,"time":"2016-08-09T21:48:21+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/calendars\/myuser\/default\/","user":"myuser"}
{"reqId":"MlUm7BNHXkgtS5JCC\/+a","remoteAddr":"192.168.y.x","app":"admin_audit","message":"Login successful: \"myuser\"","level":1,"time":"2016-08-09T21:48:21+02:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/myuser\/default\/","user":"myuser"}
{"reqId":"\/7SBJB6k\/ESfLFJPg\/G2","remoteAddr":"192.168.y.x","app":"PHP","message":"Error: Call to a member function getQuota() on null at \/var\/www\/nextcloud\/lib\/private\/util.php#289","level":3,"time":"2016-08-09T21:49:34+02:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php","user":"--"}

![public upload](https://cloud.githubusercontent.com/assets/20593693/17531275/789843da-5e7b-11e6-92c7-3945d6022970.jpg)

If i set **'quota_include_external_storage' => false,** the wrong quota calculation appears (Your storage is almost full (98%)) 
![01](https://cloud.githubusercontent.com/assets/20593693/17531558/a60862cc-5e7c-11e6-8b49-1d12c3c1b32b.PNG)
but the upload would succeed.
The quota will be displayed correctly if this setting is set to true immediately:
![02](https://cloud.githubusercontent.com/assets/20593693/17531597/e549a0a4-5e7c-11e6-8c0d-669ae05bd4ef.PNG)

I can reproduce this behaviour on a test (virtual) machine and as well on a productive odroid c2 machine. I am looking forward to your responses.

Cheers, Carsten
(https://www.c-rieger.de/ <- nextcloud installation guide)

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by icewind1991** [comment]
What is the quota set at for the user?

**Comment by riegercloud** [comment]
I set the quota to 1.5 TB
![00](https://cloud.githubusercontent.com/assets/20593693/17623138/d497b736-609e-11e6-94c2-74668eac8056.PNG)
i still tried to 'enable_functions = disk_free_space, disk_total_space' but w/o success.
If you are interested i can share my environment via teamviewer to one of you?!

**Comment by icewind1991** [comment]
#847 should fix the quota calculation with `'quota_include_external_storage' => false`

**Comment by icewind1991** [comment]
#848 for public link upload with `'quota_include_external_storage' => true`

**Comment by riegercloud** [comment]
regarding to #848 
- i changed /var/www/nextcloud/lib/private/helper.php
- i set the quota to 1.5TB 
- config.php:
 'filesystem_check_changes' => 1,
 'quota_include_external_storage' => true,

The public upload still failed with a spinning wheel.

**Comment by riegercloud** [comment]
regarding to #847 

fixed with new helper.php - thank you very much

![upload_succeeded2](https://cloud.githubusercontent.com/assets/20593693/17700582/b3d79e82-63c6-11e6-9f83-3d5bc641068f.PNG)

![quota](https://cloud.githubusercontent.com/assets/20593693/17700593/c6eedcf6-63c6-11e6-9047-64f641f16ac5.PNG)

**Comment by rullzer** [comment]
#847 and #848 are merged => closing

**Comment by riegercloud** [comment]
In Nextcloud 11 beta2 the issue regarding the calculation of user quota re-occurs.
Wasn't it fixed in NC11?

**Comment by riegercloud** [comment]
i made a fresh installation and it works like a charme!
