### ISSUE TITLE
On 32-bit server, streaming files >2GiB does not work

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/server#9405]
I first posted this issue in nextcloud/files_videoplayer#55.

### Steps to reproduce
1. Upload a video bigger than 2 gibibytes
2. Attempt to stream it, in browser

### Expected behaviour
The video streams

### Actual behaviour
The video does not stream. 
When opened in the browser outside of the integrated video player, the video downloads completely and does not play after. Downloading and playing the video works fine.

### Server configuration

**Operating system**: Raspbian 9 (32-bit)

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.23

**PHP version:** PHP 7.0.27

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.4

**Where did you install Nextcloud from:** Tarball

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.6.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - audioplayer: 2.3.0
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - checksum: 0.4.0
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
            "example.cc",
            "server1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "loglevel": 2,
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "maintenance": false,
        "theme": "",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 59.0.2

**Operating system:** Ubuntu 16.04.4

#### Web server error log
<details>
<summary>Web server error log</summary>
There were no errors, but here is the request:

```
192.168.1.4 - - [06/May/2018:20:13:14 +0200] "GET /remote.php/webdav/Downl
oads/Archiv/Test%20File.m4v?downloadStartSecret=zxhynatos7r 
HTTP/1.1" 200 22486657 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.
0) Gecko/20100101 Firefox/59.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"ywrrpYXyRRfFZbfJM3jo","level":3,"time":"2018-05-06T18:13:09+00:00","remoteAddr":"192.168.1.4","user":"christopher","app":"PHP","method":"GET","url":"\/remote.php\/webdav\/Downloads\/Archiv\/Film\/Test%20File.m4v","message":"fseek() expects parameter 2 to be integer, string given at \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php#177","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.2.1"}

```
</details>

**Comment by karottenbaum** [comment]
The issue persists with Nextcloud 13.0.4.

**Comment by skjnldsv** [comment]
Still occuring @karottenbaum ?

**Comment by karottenbaum** [comment]
The issue still occurs with 16.0.1.
The environment has, however, changed:

* **OS:** Armbian stretch (32-bit)
* **Web server:** Apache 2.4.25-3+deb9u7
* **Database:** MariaDB 10.1.38
* **PHP version:** PHP-FPM 7.3.6
* **Nextcloud version:** 16.0.1
* **Browser version:** Firefox 67.0
* **Client OS:** Ubuntu 18.04

The error I was encountering has disappeared from the Nextcloud log.
In the developer tools, I see that a request for bytes 0- is made, but the server only returns ~32KB. After this, the browser starts requesting the first few MB of the next file.

**Comment by skjnldsv** [comment]
I mean can we actually fix it?
Isn't it a hardware limitation?

**Comment by arsylum** [comment]
I am facing and researching a similar issues on a raspberry pi model 4, which is armv7l (32bit)

the cause seems to be out of bounds numbers that are > `PHP_INT_MAX` which commonly is `2147483647` on 32 bit arch. unusual about OP's error message is that it reports an unexpected string, instead of a float which would normally result from an oob integer (quote php docs:)
> If PHP encounters a number beyond the bounds of the integer type, it will be interpreted as a float instead.

vs: `fseek() expects parameter 2 to be integer, string given`
in my log messages the parameter 2 is reported to be a float instead.

**nevertheless it seems to be a pretty safe bet that both cases are due to the 32bit limitation and therefore it seems unlikely that this will be ever resolved via the software**

(using something like the php BC Math extension might be thinkable but I assume would result in a huge performance hit)

that's my very limited insight on this so far, hope it can be of some use, though someone more qualified and familiar with the nexctloud code surely could give more well-founded input

**Comment by karottenbaum** [comment]
On Nextcloud 17.0.1, streaming is still broken for files >2GB.

**Comment by karottenbaum** [comment]
Still broken on Nextcloud 17.0.2 + php-fpm 7.3.12 + apache2 2.4.25 + MariaDB 10.1.41.

**Comment by skjnldsv** [comment]
Ping @icewind1991  @blizzz @rullzer @nickvergessen

**Comment by karottenbaum** [comment]
Still broken for most files on Nextcloud 17.0.3 + php-fpm 7.3.14 + apache2 2.4.25 + MariaDB 10.1.41. 
I recently found one file which at least begins to play, I'm still figuring out why that one works.

**Comment by JonasDaWi** [comment]
I have the same problem on my odroid hc2

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by karottenbaum** [comment]
I couldn't tell you, because I now use a 64-bit system - however, I assume it is. 
Whether to fix it would probably need a technical discussion though, as this seems to be a language limitation and therefore could only be resolved via a library and lots of additional code.

**Comment by szaimen** [comment]
Thanks for the feedback! I assume it isn't worth the trouble because more and more devices are getting 64-bit support. 
We should in this case but definitely document in the system requirements that 64-bit is needed for Nextcloud.

---

cc @nextcloud/server-triage some thoughts on this?
